import {useEffect,useState} from 'react';
import {api,hasToken,setToken} from './api';
import ModelServices from './ModelServices';
import {SystemCapabilities} from './SystemCapabilities';

import {BenchmarkAdminSettings,SkillImport} from './BenchmarkStudio';

const tabs=[['models','模型与服务'],['bindings','功能模型绑定'],['media','媒体 API'],['benchmark','对标数据 API'],['skills','提示词与 Skills'],['users','用户管理'],['audit','操作记录']];
const purposes=[['prompt_optimize','提示词优化'],['writing','文案创作'],['profile','身份访谈'],['brand','品牌访谈'],['benchmark','对标分析']];
export default function AdminApp(){
 const [auth,setAuth]=useState(hasToken()),[state,setState]=useState<any>(null),[data,setData]=useState<any>(null),[tab,setTab]=useState(location.hash.slice(1)||'models'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[form,setForm]=useState<any>(null),[bindings,setBindings]=useState<any>({}),[media,setMedia]=useState<any[]>([]);
 const load=async()=>{const [s,d]=await Promise.all([api('/state'),api('/admin/state')]);if(s.user.role!=='admin')throw new Error('仅管理员可进入管理后台');setState(s);setData(d);const catalog=await api('/studio/catalog');setMedia(catalog.tools);setBindings({...Object.fromEntries(catalog.tools.map((c:any)=>[c.id,c.binding])),...d.bindings})};
 useEffect(()=>{const expired=()=>{setAuth(false);setState(null);setData(null)};window.addEventListener('session-expired',expired);return()=>window.removeEventListener('session-expired',expired)},[]);
 useEffect(()=>{if(!auth)return;void load().catch(e=>setError(e.message));const timer=setInterval(()=>{void api('/state').then(setState).catch(e=>setError(e.message))},5000);return()=>clearInterval(timer)},[auth]);
 const run=async(fn:()=>Promise<any>,message='已保存')=>{setBusy(true);setError('');try{const r=await fn();await load();setNotice(r?.kind==='job'?'验证任务已提交':message);return r}catch(e:any){setError(e.message);throw e}finally{setBusy(false)}};
 const action=(fn:()=>Promise<any>,message?:string)=>{void run(fn,message).catch(()=>{})};
 const t={state,list:(kind:string)=>state?.objects.filter((x:any)=>x.kind===kind)||[],action,setForm};
 useEffect(()=>{const changed=()=>setTab(location.hash.slice(1)||'models');window.addEventListener('hashchange',changed);return()=>window.removeEventListener('hashchange',changed)},[]);
 const logout=()=>{void api('/auth/logout',{}).then(()=>{setToken('');setAuth(false);setState(null);setData(null);setError('')}).catch(e=>setError(e.message))};
 if(!auth)return <div className="admin-login"><form onSubmit={async e=>{e.preventDefault();setError('');setBusy(true);try{const r=await api('/auth/login',Object.fromEntries(new FormData(e.currentTarget)));if(r.user.role!=='admin'){setToken(r.token);await api('/auth/logout',{});setToken('');throw new Error('此账户没有管理权限，请使用管理员账户')}setToken(r.token);setAuth(true)}catch(e:any){setError(e.message)}finally{setBusy(false)}}}><small>TIJIAN ADMIN</small><h1>管理后台</h1><p>配置服务、创作方法与平台功能。</p><label className="field">管理员邮箱<input name="email" type="email" autoComplete="username" required/></label><label className="field">密码<input name="password" type="password" autoComplete="current-password" required/></label>{error&&<p role="alert" className="form-error">{error}</p>}<button className="primary" disabled={busy}>{busy?'登录中…':'登录管理后台'}</button><a href="/">返回创作工作台</a></form></div>;
 const providerForm=(p:any,reload:()=>Promise<any>)=>({title:'编辑模型服务',fields:[{key:'title',label:'服务名称',value:p.title,required:true},{key:'base_url',label:'Base URL',type:'url',value:p.base_url,required:true},{key:'api_key',label:'替换 API Key（留空保留）',type:'password'},{key:'protocol',label:'协议',value:p.protocol,options:[{value:'chat',label:'Chat Completions'},{value:'responses',label:'Responses API'}]}],submit:'保存连接',action:async(v:any)=>{await api('/admin/providers',{...v,id:p.id});await reload()}});
 return <div className="admin-shell"><aside className="admin-sidebar"><h1>梯见 · 管理</h1><p>ADMIN CONSOLE</p>{tabs.map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>{setTab(key);location.hash=key;setNotice('');setError('')}}>{label}</button>)}<a href="/">打开创作工作台 ↗</a><button onClick={logout}>退出后台</button></aside><main className="admin-main"><header><h2>{tabs.find(x=>x[0]===tab)?.[1]||'管理后台'}</h2><span>配置仅供管理员维护；修改后作用于后续创作任务。</span></header>{error&&<p role="alert" className="form-error">{error}</p>}{notice&&<p role="status" className="admin-notice">{notice}</p>}{!data?<p>正在检查管理权限…</p>:<>
 {tab==='models'&&<ModelServices t={t} data={data} load={load} providerForm={providerForm}/>}
 {tab==='bindings'&&<section className="surface"><p>文本功能绑定已验证上架模型；媒体功能绑定专用接口。AI 生图也可绑定 CPA 等兼容 Images 的图片模型。</p>{purposes.map(([key,label])=><label className="field" key={key}>{label}<select value={bindings[key]||''} onChange={e=>setBindings({...bindings,[key]:e.target.value})}><option value="">未绑定</option>{data.models.filter((m:any)=>m.verified&&m.published&&m.capability==='text').map((m:any)=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label>)}<h3>图片、视频与音频</h3>{media.map((c:any)=><label className="field" key={c.id}>{c.title}<select value={bindings[c.id]||''} onChange={e=>setBindings({...bindings,[c.id]:e.target.value})}><option value="">停用 / 未绑定</option><option value={'service:'+(['text_image','image_edit','text_video','image_video'].includes(c.id)?'aliyun':c.id==='compose'?'shotstack':'hifly')}>{['text_image','image_edit','text_video','image_video'].includes(c.id)?'阿里云百炼':c.id==='compose'?'Shotstack':'飞影数字人'}（媒体 API）</option>{['text_image','image_edit'].includes(c.id)&&data.models.filter((m:any)=>m.verified&&m.published&&m.capability==='image').map((m:any)=><option key={m.id} value={m.id}>{m.title} · Images 接口</option>)}</select><small>{c.configured?'当前可提交任务':'当前不可用：检查媒体 API 密钥或模型上架状态'}</small></label>)}<button className="primary" disabled={busy} onClick={()=>action(()=>api('/admin/bindings',bindings))}>保存功能绑定</button></section>}
 {tab==='media'&&<MediaProviders/>}
 {tab==='benchmark'&&<BenchmarkAdminSettings/>}
 {tab==='skills'&&<><SkillImport/><SystemCapabilities/></>}
 {tab==='users'&&<section className="surface"><table><thead><tr><th>用户</th><th>邮箱</th><th>角色</th><th>状态</th></tr></thead><tbody>{data.users.map((u:any)=><tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td>{u.role==='admin'?'管理员':'创作者'}</td><td><button disabled={u.id===state.user.id||busy} onClick={()=>action(()=>api('/admin/users/'+u.id,{active:!u.active},'PATCH'))}>{u.active?'已启用 · 停用':'已停用 · 启用'}</button></td></tr>)}</tbody></table></section>}
 {tab==='audit'&&<section className="surface"><table><thead><tr><th>时间</th><th>操作</th><th>对象</th></tr></thead><tbody>{data.audit.map((x:any)=><tr key={x.id}><td>{new Date(x.created).toLocaleString('zh-CN')}</td><td>{x.action}</td><td>{x.target||'全局配置'}</td></tr>)}</tbody></table></section>}
 </>}{form&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label={form.title}><h2>{form.title}</h2><p>{form.description}</p><form onSubmit={e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));void run(()=>form.action(values)).then(()=>setForm(null)).catch(()=>{})}}>{form.fields.map((f:any)=><label className="field" key={f.key}>{f.label}{f.options?<select name={f.key} defaultValue={f.value}>{f.options.map((o:any)=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==='textarea'?<textarea name={f.key} defaultValue={f.value} required={f.required}/>:<input name={f.key} defaultValue={f.value} type={f.type||'text'} required={f.required} autoComplete={f.type==='password'?'new-password':'off'}/>}</label>)}{error&&<p className="form-error">{error}</p>}<div className="button-row"><button type="button" disabled={busy} onClick={()=>setForm(null)}>取消</button><button className="primary" disabled={busy}>{form.submit||'保存'}</button></div></form></section></div>}</main></div>;
}

function MediaProviders(){
 const providers=[{id:'hifly',name:'飞影数字人',base:'https://hfw-api.hifly.cc',docs:'https://api.hifly.cc/hifly.html',site:'https://hifly.cc/intro/api.html'},{id:'aliyun',name:'阿里云百炼',base:'https://dashscope.aliyuncs.com',docs:'https://help.aliyun.com/zh/model-studio/',site:'https://bailian.console.aliyun.com/'},{id:'shotstack',name:'Shotstack 视频合成',base:'https://api.shotstack.io',docs:'https://shotstack.io/docs/api/',site:'https://shotstack.io/pricing/'}];
 const [selected,setSelected]=useState('hifly'),[data,setData]=useState<any>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const load=()=>api('/studio/settings').then(setData);
 useEffect(()=>{void load().catch(e=>setError(e.message))},[]);
 const provider=providers.find(x=>x.id===selected)!;
 const records=Array.isArray(data?.providers)?data.providers:Object.entries(data?.providers||{}).map(([id,v]:any)=>({id,...v}));
 const saved=records.find((x:any)=>(x.id||x.provider)===selected);
 return <section className="surface"><h2>媒体生成服务</h2><p>前台根据可用接口展示参数。保存连接不会执行付费生成；实际费用与能力以供应商账户为准。</p><label className="field">服务<select value={selected} onChange={e=>{setSelected(e.target.value);setError('');setNotice('')}}>{providers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><p><a href={provider.site} target="_blank" rel="noreferrer">开通与费用说明 ↗</a> · <a href={provider.docs} target="_blank" rel="noreferrer">官方接口文档 ↗</a></p><p>{saved?.configured||saved?.has_key?'服务端已保存密钥':'尚未配置密钥'} · 实际调用结果请在创作任务中检查</p><form key={selected+(saved?.base_url||'')} onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const d=Object.fromEntries(new FormData(form));setBusy(true);setError('');setNotice('');try{await api('/studio/settings',{provider:selected,base_url:d.base_url,api_key:d.api_key||undefined,enabled:d.enabled==='on',...(selected==='shotstack'?{environment:d.environment}:{})});(form.elements.namedItem('api_key') as HTMLInputElement).value='';await load();setNotice('已保存连接配置；未执行付费测试。')}catch(e:any){setError(e.message)}finally{setBusy(false)}}}><label className="field">API 地址<input name="base_url" type="url" required defaultValue={saved?.base_url||provider.base}/></label><label className="field">API Key（留空保留原密钥）<input name="api_key" type="password" autoComplete="new-password"/></label>{selected==='shotstack'&&<label className="field">环境<select name="environment" defaultValue={saved?.environment||'stage'}><option value="stage">沙盒 stage</option><option value="v1">正式 v1（按账户计费）</option></select></label>}<label className="switch-row"><input name="enabled" type="checkbox" defaultChecked={saved?.enabled??true}/>启用此服务</label><button className="primary" disabled={busy}>{busy?'保存中…':'加密保存配置'}</button></form>{error&&<p role="alert" className="form-error">{error}</p>}{notice&&<p role="status">{notice}</p>}</section>;
}
