import ArticleImagePicker from './ArticleImagePicker';
import {useEffect,useRef,useState} from 'react';
import {api,getToken,download} from './api';
import Markdown from './Markdown';
import {readerArticleText} from './wechat-rich';
import {JobFeedback,activeJob} from './OperationFeedback';
import './article-editor.css';
export default function ArticleEditor({asset,t}:{asset:any;t:any}){
 const key='studio-content-edit:'+t.state.user.id+':'+asset.id;
 const cache=(()=>{try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}})();
 const [body,setBody]=useState(cache?.body??asset.body??asset.text??''),[version,setVersion]=useState(cache?.version??asset.version),[saved,setSaved]=useState(asset.body??asset.text??''),[mode,setMode]=useState('preview'),[expanded,setExpanded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[pictures,setPictures]=useState<string|null>(null);
 const [suggestionOpen,setSuggestionOpen]=useState(false),[selectedContext,setSelectedContext]=useState<{body:string;start:number;end:number;text:string}|null>(null),[manualPrompt,setManualPrompt]=useState(()=>localStorage.getItem('article-picture-manual:'+t.state.user.id+':'+asset.id)||''),[suggestedPrompt,setSuggestedPrompt]=useState(''),[suggestionJob,setSuggestionJob]=useState<any>(null),[suggestionSubmitting,setSuggestionSubmitting]=useState(false);
 const textarea=useRef<HTMLTextAreaElement>(null),selection=useRef({start:body.length,end:body.length}),pointerSelection=useRef<{start:number;end:number}|null>(null),suggestionLock=useRef(false),dirty=body!==saved;
 const actualWords=Array.from(body.replace(/!\[[^\]]*\]\([^)]+\)/g,'').replace(/\s/g,'')).length;
 const suggestionKey='article-picture-suggestion:'+t.state.user.id+':'+asset.id;
 useEffect(()=>{if(!dirty){setBody(asset.body||asset.text||'');setSaved(asset.body||asset.text||'');setVersion(asset.version)}},[asset.version]);
 useEffect(()=>{const jobId=localStorage.getItem(suggestionKey);if(jobId)void api('/jobs/'+jobId).then(j=>{setSuggestionJob(j);setSuggestionOpen(true);if(j.status==='done')setSuggestedPrompt(j.result?.suggested_prompt||'')}).catch(()=>localStorage.removeItem(suggestionKey))},[suggestionKey]);
 useEffect(()=>{try{localStorage.setItem('article-picture-manual:'+t.state.user.id+':'+asset.id,manualPrompt)}catch{setError('手写提示词暂存失败，请检查本机存储空间')}},[manualPrompt,asset.id,t.state.user.id]);
 useEffect(()=>{if(!activeJob(suggestionJob))return;let live=true,timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const next=await api('/jobs/'+suggestionJob.id);if(!live)return;setSuggestionJob(next);if(next.status==='done')setSuggestedPrompt(next.result?.suggested_prompt||'');else if(activeJob(next))timer=setTimeout(poll,900)}catch(e:any){if(live){setError('配图建议状态查询失败：'+e.message);timer=setTimeout(poll,3000)}}};timer=setTimeout(poll,900);return()=>{live=false;clearTimeout(timer)}},[suggestionJob?.id,suggestionJob?.status,suggestionKey]);
 const change=(v:string)=>{setBody(v);setNotice('');try{localStorage.setItem(key,JSON.stringify({body:v,version}))}catch{setError('草稿暂存失败，请及时保存')}};
 const insert=(before:string,after='',position?:number)=>{const {start,end}=position===undefined?selection.current:{start:position,end:position};change(body.slice(0,start)+before+body.slice(start,end)+after+body.slice(end));setMode(mode==='preview'?'split':mode);requestAnimationFrame(()=>{textarea.current?.focus();textarea.current?.setSelectionRange(start+before.length,end+before.length)})};
 const action=async(fn:()=>Promise<void>)=>{if(busy)return;setBusy(true);setError('');try{await fn()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const save=()=>action(async()=>{const row=await api('/objects/'+asset.id,{version,body},'PATCH');setVersion(row.version);setSaved(body);localStorage.removeItem(key);await t.refresh();setNotice('已保存稿件 v'+row.version)});
 const imageFile=async(file:File,caption=file.name,place='cursor')=>{const form=new FormData();form.append('file',file);const r=await api('/content/'+asset.id+'/illustrations/upload',form);insert('\n\n!['+caption.replace(/[\[\]\r\n<>]/g,'')+'](/api/illustrations/'+r.illustration_id+'/file)\n\n','',place==='start'?0:place==='end'?body.length:selection.current.start);setPictures(null)};
 const requestSuggestion=async(context:{body:string;start:number;end:number;text:string})=>{if(suggestionLock.current||activeJob(suggestionJob))return;suggestionLock.current=true;setSuggestionSubmitting(true);setError('');setSuggestedPrompt('');try{const j=await api('/studio/text/illustration-suggestion',{content_id:asset.id,body:context.body,start:context.start,end:context.end});setSuggestionJob(j);try{localStorage.setItem(suggestionKey,j.id)}catch{setError('任务已提交，但本机无法保存任务编号；请保持本页打开直到完成')}}catch(e:any){setError(e.message||'配图建议提交失败')}finally{suggestionLock.current=false;setSuggestionSubmitting(false)}};
 const openSuggestion=()=>{const {start,end}=pointerSelection.current||selection.current;pointerSelection.current=null;const text=body.slice(start,end).trim();setSuggestionOpen(true);if(suggestionLock.current||activeJob(suggestionJob))return;const context=text?{body,start,end,text}:null;setSelectedContext(context);setSuggestedPrompt('');setSuggestionJob(null);if(context?.text.length>2000){setError('请选中2000字以内的正文片段');return}if(context)void requestSuggestion(context)};
 const usePrompt=()=>{const prompt=manualPrompt.trim();if(!prompt){setError('请先填写或采用一条配图提示词');return}if(prompt.length>1200){setError('配图提示词最多1200字');return}const key='article-picture:'+t.state.user.id+':'+asset.id;try{const cached=JSON.parse(localStorage.getItem(key)||'{}');if(cached.pending){setError('已有配图生成请求待核查，请先在配图窗口处理原任务');return}localStorage.setItem(key,JSON.stringify({...cached,prompt}));setSuggestionOpen(false);setPictures('generate');setError('')}catch{setError('配图提示词暂存失败，请检查本机存储空间')}};
 return <section className={'article-editor'+(expanded?' md-expanded':'')} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();if(dirty)void save()}}}>
 <div className="md-toolbar st-text-toolbar"><div role="tablist" aria-label="文稿视图">{[['source','编辑'],['split','双栏'],['preview','预览']].map(([v,label])=><button role="tab" aria-selected={mode===v} key={v} onClick={()=>setMode(v)}>{label}</button>)}</div><small>正文约 {actualWords} 字{asset.target_words?' · 目标约 '+asset.target_words+' 字':''} · {dirty?'有未保存修改':'已保存稿件'}</small><button onClick={()=>setExpanded(!expanded)}>{expanded?'收起编辑器':'展开编辑器'}</button><button className="st-primary" disabled={busy||!dirty} onClick={()=>void save()}>保存修改</button></div>
 {mode!=='preview'&&<div className="md-format"><button disabled={busy} onClick={()=>insert('## ')}>标题</button><button disabled={busy} onClick={()=>insert('**','**')}>粗体</button><button disabled={busy} onClick={()=>insert('*','*')}>斜体</button><button disabled={busy} onClick={()=>insert('\n- ')}>列表</button><button disabled={busy} onClick={()=>insert('\n> ')}>引用</button><button disabled={busy} onClick={()=>insert('[','](https://)')}>链接</button><label className="md-upload">上传图片<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void action(()=>imageFile(file));e.target.value=''}}/></label><button disabled={busy} onClick={()=>setPictures('library')}>素材库插图</button><button disabled={busy} onPointerDown={()=>{pointerSelection.current={...selection.current}}} onKeyDown={()=>{pointerSelection.current=null}} onClick={openSuggestion}>AI 生成配图</button><small>可粘贴或拖入图片 · Ctrl+S 保存</small></div>}
 {suggestionOpen&&<section className="md-illustration-plan" aria-label="正文配图建议"><div className="md-illustration-head"><div><strong>正文配图建议</strong><p>选中文字后点击“AI 生成配图”会结合全文生成候选提示词；未选中文字时可直接手写。</p></div><button type="button" onClick={()=>setSuggestionOpen(false)}>收起</button></div>{selectedContext?<div className="md-illustration-selection"><small>本次所选正文 · {selectedContext.text.length} 字</small><p>{selectedContext.text.length>240?selectedContext.text.slice(0,240)+'…':selectedContext.text}</p>{selectedContext.text.length>2000&&<small>请重新选中 2000 字以内的片段。</small>}{suggestionSubmitting&&<small role="status">正在提交配图建议任务…</small>}{suggestionJob?.status==='failed'&&<button type="button" onClick={()=>void requestSuggestion(selectedContext)}>重试生成建议</button>}</div>:<p className="md-illustration-empty">当前没有选中文字。你可以在下方直接写画面要求，或回到正文选中一段后再次点击“AI 生成配图”。</p>}{suggestionJob&&<div className="md-illustration-job"><JobFeedback job={suggestionJob}/></div>}{suggestedPrompt&&<div className="md-illustration-candidate"><small>AI 建议 · 先核对画面是否符合正文</small><p>{suggestedPrompt}</p><button type="button" onClick={()=>setManualPrompt(suggestedPrompt)}>填入下方提示词</button></div>}<label className="md-illustration-input">配图提示词<textarea aria-label="手动配图提示词" value={manualPrompt} maxLength={1200} rows={4} placeholder="例如：物业经理与维保人员在电梯机房核对设备记录，纪实摄影，横向构图，柔和自然光，不出现虚构品牌和数字。" onChange={e=>setManualPrompt(e.target.value)}/></label><div className="md-illustration-foot"><span>这里只准备提示词；生成图片后仍需预览并手动插入，正文不会被自动改写。</span><button className="st-primary" type="button" disabled={!manualPrompt.trim()} onClick={usePrompt}>使用提示词打开配图生成</button></div></section>}
 {pictures&&<ArticleImagePicker content={asset} owner={t.state.user.id} initialTab={pictures} onClose={()=>setPictures(null)} onInsert={async(pic,caption,place)=>{const r=await fetch(pic.file_url,{headers:{Authorization:'Bearer '+getToken()}});if(!r.ok)throw new Error('素材读取失败');await imageFile(new File([await r.blob()],pic.title||'素材.png',{type:pic.mime_type||'image/png'}),caption||pic.title||'配图',place)}}/>}
 {error&&<p role="alert" className="st-alert">{error}</p>}{notice&&<p role="status" className="md-saved">{notice}</p>}
 <div className={'md-body md-'+mode}>{mode!=='preview'&&<textarea ref={textarea} data-enter="newline" aria-label="编辑生成文稿" readOnly={busy||!!pictures} value={body} onChange={e=>change(e.target.value)} onSelect={e=>{selection.current={start:e.currentTarget.selectionStart,end:e.currentTarget.selectionEnd}}} onPaste={e=>{const file=Array.from(e.clipboardData.files).find(f=>f.type.startsWith('image/'));if(file){e.preventDefault();void action(()=>imageFile(file))}}} onDragOver={e=>e.preventDefault()} onDrop={e=>{const file=e.dataTransfer.files[0];if(file?.type.startsWith('image/')){e.preventDefault();void action(()=>imageFile(file))}}}/>}{mode!=='source'&&<div className="md-rendered"><Markdown text={readerArticleText(body)}/></div>}</div>
 <footer className="md-footer"><span>{dirty?'保存后再导出或传递给下一步':'使用已保存版本导出；不会发布到外部平台'}</span><button disabled={busy||dirty} onClick={()=>void action(()=>download('/content/'+asset.id+'/export?format=html',(asset.title||'文稿')+'.html'))}>导出图文 HTML</button></footer>
 </section>
}
