import {DouyinLibrary} from './DouyinLibrary';
import {useViewState} from './useViewState';
import {useState} from 'react';
import {Plus,ArrowUpRight} from 'lucide-react';
import {PageTitle,Reader,ScopedProgress} from './WorkPages';
import {WechatLibrary} from './WechatLibrary';
import {SubscriptionStatus} from './SubscriptionStatus';
import {AcquisitionMeta,originNames,fullTime} from './AcquisitionMeta';
import {CollectionResult,jobStatus} from './CollectionResult';
import {DeleteRecord} from './DeleteRecord';
import {AccountDiscovery} from './DiscoveryPanels';
export const benchmarkFields=[{key:'title',label:'账号名称',required:true},{key:'platform',label:'平台',options:['公众号','视频号','小红书','微博','知乎','抖音','网站'].map(value=>({value,label:value}))},{key:'url',label:'主页 / 代表作品链接',type:'url'},{key:'feed_url',label:'RSS订阅地址（可选）'},{key:'reason',label:'关注理由',type:'textarea'}];
export function BenchmarkPage(t:any){
 const accounts=t.list('benchmark'),parts=(t.route||'').split('/'),account=accounts.find((x:any)=>x.id===parts[1])||accounts[0],tab=['saved','automatic','manual','history'].includes(parts[2])?parts[2]:'saved';
 const cache='benchmark-view:'+t.state.user.id+':'+account?.id;
 const [q,setQ]=useViewState(cache+':q',''),[accountQuery,setAccountQuery]=useState(''),[origin,setOrigin]=useViewState(cache+':origin',''),[reader,setReader]=useState<any>(null),[catalog,setCatalog]=useViewState(cache+':catalog',false),[discover,setDiscover]=useState(false);
 const sources=t.list('source').filter((x:any)=>x.benchmark_id===account?.id&&x.status==='ready').sort((a:any,b:any)=>(b.body_saved_at||b.created||'').localeCompare(a.body_saved_at||a.created||'')),jobs=t.list('job').filter((x:any)=>x.input?.benchmark_id===account?.id),wechat=['公众号','wechat','微信公众号'].includes(account?.platform),douyin=['抖音','douyin'].includes(account?.platform);
 const rows=sources.filter((x:any)=>x.title.includes(q)&&(!origin||(x.acquisition_origin||'unknown')===origin));
 const navigate=(id:string,next='saved')=>{location.hash='benchmark/'+id+'/'+next;if(id!==account?.id){setQ('');setOrigin('');setCatalog(false)}};
 return <div className="work-page"><PageTitle number="03" title="对标研究" description="关注账号 → 获取作品 → 保存资料 → 分析与创作" actions={<button className="primary" onClick={()=>t.newItem('benchmark','添加对标账号',benchmarkFields)}><Plus size={16}/>添加对标</button>}/><div className="benchmark-layout"><aside className="benchmark-accounts"><h2>关注账号 <small>{accounts.length}</small></h2><input aria-label="搜索对标账号" placeholder="搜索账号" value={accountQuery} onChange={e=>setAccountQuery(e.target.value)}/>{accounts.filter((x:any)=>x.title.includes(accountQuery)).map((x:any)=><button className={'benchmark-account '+(x.id===account?.id?'selected':'')} key={x.id} onClick={()=>navigate(x.id)}><span className="small-avatar">{x.title[0]}</span><span><strong>{x.title}</strong><small>{x.platform}</small></span></button>)}</aside><section className="benchmark-content">{account?(douyin?<DouyinLibrary key={account.id} account={account} t={t}/>:<><header className="benchmark-account-header"><div><span className="section-number">{account.platform}</span><h2>{account.title}</h2><p>{account.reason||'持续阅读和研究这个账号的作品。'}</p></div><div className="article-count"><b>{sources.length}</b>篇已保存正文</div></header>{wechat?<SubscriptionStatus account={account} t={t} tab={tab}/>:<a className="settings-link" href={'#settings/benchmark/'+account.id+'/'+tab}>账号与获取设置 →</a>}<nav className="work-tabs" aria-label="对标内容分类">{[['saved','已保存正文'],['automatic','订阅发现'],['manual','手动获取'],['history','获取记录']].map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>navigate(account.id,key)}>{label}{key==='saved'&&<span>{sources.length}</span>}</button>)}</nav>
 {tab==='saved'&&<><div className="section-intro"><h3>已保存正文</h3><p>这里的文章已保存在本地，可以直接阅读和分析。</p></div><div className="radar-toolbar"><input aria-label="搜索对标文章" placeholder="搜索已保存正文" value={q} onChange={e=>setQ(e.target.value)}/><select aria-label="获取方式" value={origin} onChange={e=>setOrigin(e.target.value)}><option value="">全部获取方式</option>{Object.entries(originNames).map(([key,label])=><option key={key} value={key}>{label}</option>)}<option value="unknown">历史记录 · 未细分</option></select></div><div className="benchmark-articles">{rows.map((x:any)=><article className="benchmark-article" key={x.id}><div className="article-main"><button className="article-title" onClick={()=>setReader(x)}>{x.title}</button><AcquisitionMeta item={x}/></div><DeleteRecord item={x} t={t}/><button onClick={()=>t.action(()=>t.openTask('拆解这篇文章的结构、受众和论据：'+x.title,'benchmark',[x.id]))}>分析与创作 <ArrowUpRight size={14}/></button></article>)}{!rows.length&&<div className="radar-welcome"><h3>还没有符合条件的正文</h3><p>订阅发现的文章在保存成功后会出现在这里，也可手动添加。</p><button onClick={()=>navigate(account.id,'manual')}>手动获取文章</button></div>}</div></>}
 {tab==='automatic'&&(wechat?<><div className="section-intro"><h3>订阅发现</h3><p>自动巡检和你主动点击的订阅检查会分别标记。目录不等于正文；已保存的文章也可在“已保存正文”阅读。</p></div><WechatLibrary key={account.id+'automatic'} account={account} t={t} mode="automatic"/></>:<p className="inline-empty">此平台暂未接入自动订阅，请使用手动获取。</p>)}
 {tab==='manual'&&<><div className="section-intro"><h3>手动获取文章</h3><p>已有链接可直接采集；需要查找历史文章时，先获取目录，再选择保存正文。</p></div><div className="acquisition-choices"><button onClick={()=>t.urlForm(account.id)}><b>粘贴文章链接</b><span>一篇或多篇 · 免费公开读取</span></button><button onClick={()=>t.importForm(account.id)}><b>导入已有文稿</b><span>粘贴正文 · 本地保存</span></button><button className={catalog?'selected':''} onClick={()=>wechat?setCatalog(!catalog):setDiscover(true)}><b>从目录选择文章</b><span>{wechat?'次幂目录按次收费 · 每批确认':'查看该账号可获取的作品'}</span></button></div>{!catalog&&<ScopedProgress jobs={jobs.filter((j:any)=>['batch','import','collect'].includes(j.input?.action))} label="手动获取" getSource={t.get}/>}{catalog&&wechat&&<WechatLibrary key={account.id+'catalog'} account={account} t={t} mode="catalog"/>}</>}
 {tab==='history'&&<section className="benchmark-history"><div className="section-intro"><h3>获取记录</h3><p>查看每次任务的触发方式、执行时间和结果。删除记录不删除已保存正文。</p></div>{jobs.map((j:any)=><details key={j.id}><summary><span>{j.title}<small>{originNames[j.input?.trigger]||({wechat_body:'手动目录采集',batch:'手动链接',import:'手动链接'} as any)[j.input?.action]||'历史任务 · 触发方式未记录'} · 提交 {fullTime(j.created)}</small></span><b>{jobStatus(j)}</b></summary><p className="muted">开始：{fullTime(j.started_at)} · 结束：{fullTime(j.finished_at)}</p><DeleteRecord item={j} t={t}/><CollectionResult job={j} getSource={t.get}/></details>)}{!jobs.length&&<p className="inline-empty">还没有获取记录。</p>}</section>}
 </>):<div className="radar-welcome"><h2>先添加一个关注账号</h2><p>然后选择自动订阅，或手动获取你需要的文章。</p></div>}</section></div>{discover&&account&&<AccountDiscovery account={account} t={t} onClose={()=>setDiscover(false)}/>} {reader&&<Reader item={reader} onClose={()=>setReader(null)}><AcquisitionMeta item={reader}/><button className="primary" onClick={()=>t.action(()=>t.openTask('拆解这篇文章：'+reader.title,'benchmark',[reader.id]))}>分析与创作</button><button onClick={()=>t.editItem(reader,[{key:'title',label:'标题',required:true},{key:'body',label:'正文',type:'textarea'}])}>编辑资料</button></Reader>}</div>
}
