import {useEffect,useId,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Check,ChevronDown} from 'lucide-react';
type Option={value:string;label:string;description?:string};
export function ChoiceMenu({label,value,options,onChange}:{label:string;value:string;options:Option[];onChange:(value:string)=>void}){
 const id=useId(),trigger=useRef<HTMLButtonElement>(null),popup=useRef<HTMLDivElement>(null);
 const [open,setOpen]=useState(false),[active,setActive]=useState(0),[position,setPosition]=useState<{left:number;top?:number;bottom?:number;width:number;maxHeight:number}>({left:0,top:0,width:280,maxHeight:320});
 const close=(focus=false)=>{setOpen(false);if(focus)trigger.current?.focus()};
 const show=()=>{const rect=trigger.current!.getBoundingClientRect(),width=Math.min(320,window.innerWidth-24),above=rect.top-20,below=window.innerHeight-rect.bottom-20;const upward=above>=Math.min(200,below);setPosition({left:Math.max(12,Math.min(rect.left,window.innerWidth-width-12)),...(upward?{bottom:window.innerHeight-rect.top+8}:{top:rect.bottom+8}),width,maxHeight:Math.max(60,Math.min(320,upward?above:below))});setActive(Math.max(0,options.findIndex(x=>x.value===value)));setOpen(true)};
 useEffect(()=>{if(!open)return;popup.current?.focus();const outside=(e:PointerEvent)=>{if(!popup.current?.contains(e.target as Node)&&!trigger.current?.contains(e.target as Node))close()};const reposition=()=>close();document.addEventListener('pointerdown',outside);window.addEventListener('resize',reposition);return()=>{document.removeEventListener('pointerdown',outside);window.removeEventListener('resize',reposition)}},[open]);
 useEffect(()=>{if(open)document.getElementById(id+'-'+active)?.scrollIntoView({block:'nearest'})},[active,open]);
 return <><button type="button" ref={trigger} className="choice-trigger" aria-label={label} aria-haspopup="listbox" aria-expanded={open} aria-controls={open?id:undefined} onClick={()=>open?close():show()} onKeyDown={e=>{if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();show()}}}><span>{options.find(x=>x.value===value)?.label||label}</span><ChevronDown size={14}/></button>{open&&createPortal(<div ref={popup} id={id} className="choice-menu" role="listbox" aria-label={label} aria-activedescendant={id+'-'+active} tabIndex={-1} style={position} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))close()}} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();close(true)}else if(e.key==='Tab'){close(true)}else if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();setActive(e.key==='Home'?0:e.key==='End'?options.length-1:(active+(e.key==='ArrowDown'?1:-1)+options.length)%options.length)}else if(e.key==='Enter'||e.key===' '){e.preventDefault();onChange(options[active].value);close(true)}}}><div className="choice-caption">{label}</div>{options.map((x,i)=><div key={x.value} id={id+'-'+i} role="option" aria-selected={x.value===value} className={'choice-option '+(active===i?'focused':'')} onPointerMove={()=>setActive(i)} onMouseDown={e=>e.preventDefault()} onClick={()=>{onChange(x.value);close(true)}}><span><strong>{x.label}</strong>{x.description&&<small>{x.description}</small>}</span>{x.value===value&&<Check size={15}/>}</div>)}</div>,document.body)}</>;
}
