import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,Lightbulb,BookOpen,PenLine,FolderOpen,Send,Plus} from 'lucide-react';
import {api} from './api';
import './creation-flow.css';

const stages=[['方向与身份','先确定想讲什么、为谁表达',Lightbulb],['选好主题','明确这件作品的主题与切入角度',BookOpen],['内容分支','选择产物，按依赖完成制作',PenLine],['确认作品','挑选本次流程的成品版本',FolderOpen],['平台准备','将确认作品整理成平台草稿',Send]] as const;
const tools=[['text','文案创作','text'],['image','图片创作','text_image'],['video','AI 视频','text_video'],['avatar/text','数字人口播','text_avatar'],['audio/tts','文本配音','tts'],['compose','素材成片','compose']] as const;
const platforms=[['wechat','公众号'],['channels','视频号'],['douyin','抖音']] as const;
const toolHints:Record<string,string>={text:'写标题、正文与口播文稿',image:'生成封面或画面',video:'生成视频镜头','avatar/text':'用文稿制作数字人口播','audio/tts':'制作配音',compose:'把已有画面和声音组合'};
const flowFields=['brand_id','profile_id','content_id','visual_id','cover_id','video_id','audio_id','brief','last_draft','last_draft_tool','topic_id','stage','tool_path','platform','assembled'];
const flowSignature=(value:any)=>JSON.stringify(flowFields.map(key=>value?.[key]??''));

export default function CreationFlow({t,route='flow'}:{t:any;route?:string}){
 const owner=t.state.user.id,workId=new URLSearchParams(route.split('?')[1]||'').get('work')||'';
 const storage='studio-flow:'+owner+(workId?':'+workId:'');
 const [flow,setFlow]=useState<any>(()=>{try{return JSON.parse(localStorage.getItem(storage)||'{}')}catch{return {}}});
 const flowRef=useRef(flow),version=useRef(0),dirty=useRef(false),queue=useRef(Promise.resolve()),savedSignature=useRef('');
 const saveTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 const [works,setWorks]=useState<any[]>([]),[assets,setAssets]=useState<any[]>([]),[catalog,setCatalog]=useState<any[]>([]),[topics,setTopics]=useState<any[]>([]),[deliveries,setDeliveries]=useState<any[]>([]);
 const [drafts,setDrafts]=useState<any[]>([]),[importField,setImportField]=useState('content_id'),[importId,setImportId]=useState('');
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[dataLoaded,setDataLoaded]=useState(false),[topicsLoaded,setTopicsLoaded]=useState(false);
 useEffect(()=>{let live=true;void api('/studio/flow'+(workId?'?work_id='+encodeURIComponent(workId):'')).then(r=>{
  if(!live)return;
  if(!workId&&r.id){location.hash='studio/flow?work='+encodeURIComponent(r.id);return}
  const local=flowRef.current,restored=local.id===r.id&&local.version===r.version&&local.local_updated_at&&new Date(local.local_updated_at)>new Date(r.updated||0)?{...r,...local,id:r.id||local.id}:r;
  version.current=r.version||0;savedSignature.current=flowSignature(r);dirty.current=restored!==r;flowRef.current=restored;setFlow(restored);setLoaded(true);void t.refresh?.();
 }).catch((e:Error)=>{if(live)setError(e.message)});return()=>{live=false}},[workId]);
 useEffect(()=>{if(!loaded)return;let live=true;const reads=[
  api('/studio/flows').then(r=>{if(live)setWorks(r.items||[])}),
  api('/studio/assets').then(r=>{if(live)setAssets(r.items||[])}),
  api('/studio/catalog').then(r=>{if(live)setCatalog(r.tools||[])}),
  api('/studio/topics').then(r=>{if(live){setTopics(r.items||[]);setTopicsLoaded(true)}}),
  api('/studio/deliveries'+(workId?'?flow_id='+encodeURIComponent(workId):'')).then(r=>{if(live)setDeliveries(r.items||[])}),
  ...(workId?[api('/studio/flows/'+encodeURIComponent(workId)+'/drafts').then(r=>{if(live)setDrafts(r.items||[])})]:[]),
 ];void Promise.allSettled(reads).then(results=>{if(!live)return;const failed=results.find(r=>r.status==='rejected');if(failed?.status==='rejected')setError('部分资料读取失败，请刷新后重试：'+String(failed.reason));setDataLoaded(true)});return()=>{live=false}},[workId,loaded]);
 useEffect(()=>{if(!loaded||!dirty.current)return;clearTimeout(saveTimer.current);saveTimer.current=setTimeout(()=>{
  dirty.current=false;const snapshot=flowRef.current;
  queue.current=queue.current.catch(()=>{}).then(async()=>{try{const saved=await api('/studio/flow',{...snapshot,version:version.current});version.current=saved.version;savedSignature.current=flowSignature(snapshot);if(flowRef.current.local_updated_at===snapshot.local_updated_at){flowRef.current={...flowRef.current,id:saved.id,version:saved.version,local_updated_at:saved.updated};localStorage.setItem(storage,JSON.stringify(flowRef.current));setFlow(flowRef.current)}setWorks(v=>[saved,...v.filter(x=>x.id!==saved.id)])}catch(e:any){setError('流程已暂存本机，服务端保存失败：'+e.message)}});
 },650);return()=>clearTimeout(saveTimer.current)},[flow,loaded]);
 const change=(values:any)=>{dirty.current=true;const next={...flowRef.current,...values,local_updated_at:new Date().toISOString()};flowRef.current=next;setFlow(next);try{localStorage.setItem(storage,JSON.stringify(next))}catch{setError('本机保存失败，请检查存储空间')}};
 const persistNow=async(values:any={})=>{clearTimeout(saveTimer.current);dirty.current=false;await queue.current;const next={...flowRef.current,...values};if(next.id&&savedSignature.current===flowSignature(next))return next;const saved=await api('/studio/flow',{...next,version:version.current});version.current=saved.version;savedSignature.current=flowSignature(next);flowRef.current={...next,id:saved.id,version:saved.version,local_updated_at:saved.updated};setFlow(flowRef.current);setWorks(v=>[saved,...v.filter(x=>x.id!==saved.id)]);try{localStorage.setItem(storage,JSON.stringify(flowRef.current))}catch{setError('本机保存失败，请检查存储空间')}return saved};
 const stage=Math.min(4,Math.max(0,Number(flow.stage)||0)),choice=tools.find(x=>x[0]===(flow.tool_path||'text'))||tools[0],topic=topics.find(x=>x.id===flow.topic_id);
 const contents=(t.list?.('content')||[]).filter((x:any)=>!x.archived),ownContents=contents.filter((x:any)=>x.flow_id===flow.id),ownAssets=assets.filter(x=>x.flow_id===flow.id&&x.status==='ready');
 const linked=!!(flow.content_id||flow.cover_id||flow.video_id||flow.audio_id||flow.visual_id);
 const delivery=deliveries.find(d=>d.flow_id===flow.id&&d.topic_id===flow.topic_id&&d.platform===(flow.platform||'wechat'));
 const delivered=!!delivery&&!!String(delivery.title||'').trim()&&(delivery.platform==='wechat'?!!String(delivery.body||'').trim():!!delivery.video_asset_id&&!!String(delivery.caption||delivery.script||'').trim());
 const completed=[!!flow.brief?.trim(),!!topic,!!topic&&linked,!!topic&&linked&&flow.assembled==='yes',!!topic&&delivered];
 const productFields=[['content_id','文稿','text'],['cover_id','封面','image'],['video_id','视频','video'],['audio_id','配音','audio/tts']] as const;
 const productName=(field:string)=>{const id=flow[field];return id?(contents.find((x:any)=>x.id===id)||assets.find(x=>x.id===id))?.title||'已选产物':'尚未选入'};
 const summaries=[flow.brief||'写下想法，选择表达身份',topic?.title||'等待确定主题',linked?productFields.filter(([f])=>flow[f]).map(([,label])=>label).join(' · '):flow.last_draft?'已保存草稿，等待成品':'选择文字 / 图像 / 视频 / 声音',flow.assembled==='yes'?'已确认当前产物组合':'核对成品，再确认带入平台',delivery?'已保存'+(platforms.find(x=>x[0]===delivery.platform)?.[1]||'平台')+'草稿':'选择平台，准备发布内容'];
 const dependency=choice[0]==='compose'?'需要已有画面；可加入配音':choice[0]==='avatar/text'||choice[0]==='audio/tts'?'使用本次文稿，可在工具页修改':'可直接从选题开始';
 const labels=stages.map((_,i)=>completed[i]?'已完成':i===stage?'进行中':i===2&&flow.last_draft?'有草稿':i===4&&delivery?'有交付草稿':'待开始');
 const returnRoute=(id:string,step:number)=>'studio/flow?work='+encodeURIComponent(id)+'&step='+step;
 const ensureTopic=async()=>{if(!topicsLoaded)throw new Error('选题数据尚未就绪，请刷新后重试');const current=topics.find(x=>x.id===flowRef.current.topic_id);if(current)return current.id;const brief=String(flowRef.current.brief||'').trim();if(!brief)throw new Error('请先写下主题或从选题库选择');const made=await api('/studio/topics',{title:brief.slice(0,200),angle:'从一站式创作继续完善',source_ids:[],profile_id:flowRef.current.profile_id||'',origin:'一站式创作',origin_ref:'flow:'+brief.slice(0,150),status:'selected'});setTopics(v=>[made,...v.filter(x=>x.id!==made.id)]);change({topic_id:made.id});return made.id};
 const nextTopic=async()=>{setBusy(true);setError('');try{const topicId=await ensureTopic();const saved=await persistNow({topic_id:topicId,stage:2});if(!workId)location.hash='studio/flow?work='+encodeURIComponent(saved.id)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const launch=async(selected=choice,step=2)=>{setBusy(true);setError('');try{
  if(!loaded)throw new Error('正在恢复流程，请稍候');
  const topicId=await ensureTopic(),current=flowRef.current;
  const [path,,tool]=selected,source=current.content_id?t.get?.(current.content_id):null,brief=topics.find(x=>x.id===topicId)?.title||current.brief||'';
  const input=tool==='text'?{brief,format:'通用文案'}:['text_avatar','tts'].includes(tool)?{text:source?.body||brief}:tool==='compose'?{scenes:(current.video_id||current.cover_id||current.visual_id)?[{asset_id:current.video_id||current.cover_id||current.visual_id,length:5,...(current.audio_id?{audio_id:current.audio_id}:{})}]:[]}:{prompt:brief};
  // An existing work already has a stable return address. Create the draft
  // first, then save the selected tool and draft ID together in one flow write.
  const workId=current.id||(await persistNow({topic_id:topicId,stage:step,tool_path:path})).id;
  const draft=await api('/studio/flows/'+encodeURIComponent(workId)+'/drafts',{title:String(brief).slice(0,60)||'一站式创作',tool,input,brand_id:current.brand_id||'',profile_id:current.profile_id||'',source_ids:current.content_id?[current.content_id]:[],...(tool==='text'?{}:{options:{}})});
  await persistNow({topic_id:topicId,stage:step,tool_path:path,last_draft:draft.id,last_draft_tool:path});
  location.hash='studio/'+path+'?draft='+encodeURIComponent(draft.id)+'&mode='+encodeURIComponent(tool)+'&return='+encodeURIComponent(returnRoute(workId,step));
 }catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const resumeDraft=async()=>{const path=flowRef.current.last_draft_tool,draftId=flowRef.current.last_draft,selected=tools.find(x=>x[0]===path);if(!draftId||!selected)return;setBusy(true);setError('');try{const saved=await persistNow({stage:2,tool_path:path});location.hash='studio/'+path+'?draft='+encodeURIComponent(draftId)+'&mode='+encodeURIComponent(selected[2])+'&return='+encodeURIComponent(returnRoute(saved.id,2))}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const openTopics=async()=>{setBusy(true);setError('');try{const saved=await persistNow({stage:1});location.hash='studio/topics?return='+encodeURIComponent(returnRoute(saved.id,1))}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const openDelivery=async()=>{setBusy(true);setError('');try{const topicId=await ensureTopic();const saved=await persistNow({topic_id:topicId,stage:4});location.hash='studio/topics?topic='+encodeURIComponent(topicId)+'&platform='+encodeURIComponent(flowRef.current.platform||'wechat')+'&return='+encodeURIComponent(returnRoute(saved.id,4))}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const switchWork=async(id:string)=>{setBusy(true);setLoaded(false);setError('');try{if(dirty.current)await persistNow();location.hash='studio/flow?work='+encodeURIComponent(id)}catch(e:any){setError(e.message);setLoaded(true)}finally{setBusy(false)}};
 const newWork=async()=>{setBusy(true);setLoaded(false);setError('');try{if(dirty.current)await persistNow();const made=await api('/studio/flow',{new:true,version:0,brief:'',stage:0});location.hash='studio/flow?work='+encodeURIComponent(made.id)}catch(e:any){setError(e.message);setLoaded(true)}finally{setBusy(false)}};
 const importProduct=async()=>{if(!importId)return;setBusy(true);setError('');try{const saved=await persistNow();const result=await api('/studio/flows/'+encodeURIComponent(saved.id)+'/imports',{field:importField,source_id:importId,version:saved.version});const next=result.flow||result;version.current=next.version;savedSignature.current=flowSignature(next);flowRef.current=next;setFlow(next);localStorage.setItem(storage,JSON.stringify(next));await t.refresh?.();const r=await api('/studio/assets');setAssets(r.items||[]);setImportId('')}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 if(!loaded)return <div className="cf-page"><header className="cf-head"><div className="cf-title"><h1>一站式创作</h1></div></header><p className="cf-loading" role="status">正在恢复创作步骤…</p>{error&&<p className="cf-error" role="alert">{error}</p>}</div>;
 return <div className="cf-page"><header className="cf-head"><div className="cf-title"><h1>一站式创作</h1>{!dataLoaded&&<span className="cf-data-loading" role="status">正在读取作品…</span>}</div><div className="cf-work-controls"><label>当前作品<select aria-label="切换当前作品" value={flow.id||''} disabled={busy} onChange={e=>void switchWork(e.target.value)}>{flow.id&&!works.some(x=>x.id===flow.id)&&<option value={flow.id}>{flow.brief||'当前作品'}</option>}{!flow.id&&<option value="">尚未建立作品</option>}{works.map(x=><option key={x.id} value={x.id}>{x.brief||'未命名作品'}</option>)}</select></label><button type="button" disabled={busy} onClick={()=>void newWork()}><Plus size={15}/>新建作品</button></div>
 <div className="cf-overview" aria-label="本次作品概览"><span><strong>{completed.filter(Boolean).length} / 5</strong> 步骤已完成</span><span title={t.list('profile').find((p:any)=>p.id===flow.profile_id)?.title||'身份暂不指定'}>{t.list('profile').find((p:any)=>p.id===flow.profile_id)?.title||'身份暂不指定'}</span><span>{linked?productFields.filter(([f])=>flow[f]).length+' 项产物已选入':'等待第一件产物'}</span><small>步骤与草稿自动保存</small></div></header>
 <div className="cf-workspace"><nav className="cf-timeline" aria-label="创作步骤">{stages.map(([name,desc],i)=><div key={name} className={'cf-node '+(i===stage?'current ':'')+(completed[i]?'completed':'')}><button type="button" disabled={busy} onClick={()=>change({stage:i})} aria-current={i===stage?'step':undefined} title={desc+'：'+summaries[i]}><span className="cf-step-dot"><span>{String(i+1).padStart(2,'0')}</span>{completed[i]&&<Check size={12} className="cf-step-check"/>}</span><span className="cf-node-copy"><span className="cf-node-heading"><strong>{name}</strong><small>{labels[i]}</small></span><em title={summaries[i]}>{summaries[i]}</em></span></button>{i===2&&<div className="cf-node-products" aria-label="内容产物分支">{productFields.map(([field,label,path])=><button key={field} type="button" disabled={busy} className={flow[field]?'ready':''} onClick={()=>change({stage:flow[field]?3:2,tool_path:path})}>{flow[field]?<Check size={12}/>:<span className="cf-mini-dot"/>}{label}</button>)}</div>}{i===4&&<div className="cf-node-products cf-platform-branches" aria-label="平台准备分支">{platforms.map(([key,label])=><button type="button" key={key} disabled={busy} className={(flow.platform||'wechat')===key?'ready':''} onClick={()=>change({stage:4,platform:key})}>{deliveries.some(d=>d.flow_id===flow.id&&d.platform===key&&d.topic_id===flow.topic_id)?<Check size={12}/>:<span className="cf-mini-dot"/>}{label}</button>)}</div>}{i===3&&linked&&<div className="cf-node-manifest">{productFields.filter(([f])=>flow[f]).map(([f,label])=><span key={f} title={label+'：'+productName(f)}>{label}<strong>{productName(f)}</strong></span>)}</div>}</div>)}</nav>
 <section className="cf-detail" aria-label="当前步骤编辑" tabIndex={0}><div className="cf-detail-top"><span>STEP {String(stage+1).padStart(2,'0')}</span><strong>{stages[stage][0]}</strong><span className="cf-detail-status">{labels[stage]}</span></div>{error&&<p className="cf-error" role="alert">{error}</p>}
 {stage===0&&<div className="cf-step-body"><p>先写下你想讲的事，也可以从真实行业信息和对标内容找灵感。</p><label>这次想讲什么？<textarea rows={4} value={flow.brief||''} onChange={e=>change({brief:e.target.value,topic_id:'',assembled:'no'})} placeholder="例如：物业客户如何判断旧电梯是否需要更新"/></label><label>以谁的身份表达？<select value={flow.profile_id||''} onChange={e=>change({profile_id:e.target.value})}><option value="">先不指定</option>{t.list('profile').map((p:any)=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><div className="cf-actions"><a href={'#benchmark?return='+encodeURIComponent(returnRoute(flow.id,0))}>去看灵感与对标 →</a><button className="primary" disabled={!flow.brief?.trim()} onClick={()=>change({stage:1})}>下一步：选题 <ArrowRight size={16}/></button></div></div>}
 {stage===1&&<div className="cf-step-body"><p>从选题库挑选已有主题，也可以直接使用上一步写下的想法。</p><label>从选题库选择<select value={flow.topic_id||''} onChange={e=>{const x=topics.find(v=>v.id===e.target.value);change({topic_id:e.target.value,assembled:'no',...(x?{brief:x.title}:{})})}}><option value="">{flow.brief?'使用刚才写下的想法':'请选择选题'}</option>{topics.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label>{topic&&<p className="cf-selected">已选：{topic.title} · {topic.origin||'自己添加'}</p>}<div className="cf-actions"><button disabled={busy} onClick={()=>void openTopics()}>打开选题库 <ArrowRight size={15}/></button><button className="primary" disabled={busy||!topicsLoaded||(!flow.brief?.trim()&&!flow.topic_id)} onClick={()=>void nextTopic()}>{topicsLoaded?'确定主题，下一步做内容':'正在加载选题…'} <ArrowRight size={16}/></button></div></div>}
 {stage===2&&<div className="cf-step-body"><p>选择要制作的产物。每个分支独立保存，完成后将真实结果加入这件作品。</p>{!!drafts.length&&<div className="cf-branch-drafts"><small>本流程已有 {drafts.length} 份制作草稿</small>{drafts.map(d=><button type="button" key={d.id} disabled={busy} onClick={()=>{const selected=tools.find(x=>x[2]===d.tool);if(selected){change({last_draft:d.id,last_draft_tool:selected[0]});void resumeDraft()}}}>{tools.find(x=>x[2]===d.tool)?.[1]||d.tool} · {d.title}</button>)}</div>}{flow.last_draft&&<p className="cf-selected">已有创作草稿。生成成功后，可把结果加入本次作品。{flow.last_draft_tool&&<button type="button" className="cf-resume" disabled={busy} onClick={()=>void resumeDraft()}>继续上次草稿 →</button>}</p>}<div className="cf-tool-grid" role="group" aria-label="选择本次创作工具">{tools.map(([path,label])=><button type="button" key={path} className={choice[0]===path?'selected':''} onClick={()=>change({tool_path:path})}><strong>{label}</strong><small>{toolHints[path]}</small></button>)}</div><p className="cf-dependency">{dependency}</p><p className="cf-capability">{choice[2]==='text'?t.state.bindings.writing?'文本服务已配置':'文本模型未配置，可先保存草稿':catalog.find(c=>c.id===choice[2])?.configured?'生成服务已配置':'生成服务未就绪，可先保存草稿'}</p><div className="cf-actions"><button className="primary" disabled={busy||!topicsLoaded||(!flow.brief?.trim()&&!flow.topic_id)||(choice[0]==='compose'&&!flow.video_id&&!flow.cover_id&&!flow.visual_id)} onClick={()=>void launch()}>{busy?'正在打开…':'进入'+choice[1]} <ArrowRight size={16}/></button><button onClick={()=>change({stage:3})}>{linked?'查看已完成内容，确认作品':'先确认作品'} <ArrowRight size={15}/></button></div></div>}
  {stage===3&&<div className="cf-step-body"><p>选择本次流程的成品版本，确认文稿、封面、视频与配音。需要现有成果时，在下方明确导入一份独立副本。</p><div className="cf-asset-grid"><label>发布文稿 <small>带入文章正文或视频口播稿</small><select value={flow.content_id||''} onChange={e=>change({content_id:e.target.value,assembled:'no'})}><option value="">暂不带入</option>{ownContents.map((x:any)=><option key={x.id} value={x.id}>{x.title}</option>)}</select><button type="button" onClick={()=>void launch(tools[0],3)}>去写文稿 →</button></label><label>封面图片 <small>带入平台的封面选择</small><select value={flow.cover_id||''} onChange={e=>change({cover_id:e.target.value,assembled:'no'})}><option value="">暂不带入</option>{ownAssets.filter(x=>x.asset_type==='image'&&x.status==='ready').map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select><button type="button" onClick={()=>void launch(tools[1],3)}>去做封面 →</button></label><label>成片视频 <small>用于视频号和抖音发布稿</small><select value={flow.video_id||''} onChange={e=>change({video_id:e.target.value,assembled:'no'})}><option value="">暂不带入</option>{ownAssets.filter(x=>x.asset_type==='video'&&x.status==='ready').map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select><button type="button" onClick={()=>void launch(tools[2],3)}>去做视频 →</button></label><label>配音（可选） <small>留在作品中供后续合成使用</small><select value={flow.audio_id||''} onChange={e=>change({audio_id:e.target.value,assembled:'no'})}><option value="">暂不带入</option>{ownAssets.filter(x=>x.asset_type==='audio'&&x.status==='ready').map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select><button type="button" onClick={()=>void launch(tools[4],3)}>去做配音 →</button></label></div><details className="cf-import"><summary>导入现有成果</summary><p>手动选择 AI 对话、独立创作或其他流程的成果，创建属于本流程的副本。原成果保持原样。</p><div className="cf-import-fields"><label>产物类型<select aria-label="产物类型" value={importField} onChange={e=>{setImportField(e.target.value);setImportId('')}}>{productFields.map(([field,label])=><option value={field} key={field}>{label}</option>)}</select></label><label>选择原成果<select aria-label="选择原成果" value={importId} onChange={e=>setImportId(e.target.value)}><option value="">请选择要复制的成果</option>{(importField==='content_id'?contents:assets.filter(x=>x.asset_type===(importField==='cover_id'?'image':importField==='video_id'?'video':'audio')&&x.status==='ready')).map((x:any)=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label><button type="button" disabled={busy||!importId} onClick={()=>void importProduct()}>复制到本流程</button></div></details><p className="cf-selected">{linked?'已选内容会自动出现在对应平台的发布稿中。':'目前没有选入作品；仍可先用选题准备发布稿。'}</p><div className="cf-actions"><a href={'#studio/works?return='+encodeURIComponent(returnRoute(flow.id,3))}>查看全部作品 →</a><button className="primary" onClick={()=>change({stage:4,assembled:linked?'yes':'no'})}>确认，选择发布平台 <ArrowRight size={16}/></button></div></div>}
  {stage===4&&<div className="cf-step-body"><p>先选平台，再进入该平台的发布表单。标题、描述、标签、封面和正文或视频都在同一页填写；第 4 步已选内容会自动带入。</p><div className="cf-platform-grid" role="group" aria-label="选择发布平台">{platforms.map(([key,label])=><button type="button" key={key} className={(flow.platform||'wechat')===key?'selected':''} onClick={()=>change({platform:key})}><strong>{label}</strong><small>{key==='wechat'?'文章标题、摘要、正文、封面':key==='channels'?'视频标题、描述、话题、封面和成片':'短视频标题、描述、话题、封面和成片'}</small></button>)}</div><div className="cf-actions"><button className="primary" disabled={busy||!topicsLoaded||(!flow.brief?.trim()&&!flow.topic_id)} onClick={()=>void openDelivery()}>{busy?'正在打开…':'填写'+(platforms.find(x=>x[0]===(flow.platform||'wechat'))?.[1]||'平台')+'发布稿'} <ArrowRight size={16}/></button></div><small>平台准备仅保存草稿；发布需在对应平台明确操作。</small></div>}
 </section></div><div className="cf-bottom"><button disabled={stage===0} onClick={()=>change({stage:stage-1})}><ArrowLeft size={15}/>上一步：{stage?stages[stage-1][0]:''}</button><span>所有步骤可随时返回修改，已保存的草稿和成果会保留。</span>{stage<4&&<button onClick={()=>change({stage:stage+1})}>查看下一步：{stages[stage+1][0]} <ArrowRight size={15}/></button>}</div></div>;
}
