import {useEffect,useRef,useState} from 'react';
import {ArrowRight,Check,Lightbulb,BookOpen,PenLine,FolderOpen,Send} from 'lucide-react';
import {api} from './api';
import './creation-flow.css';

const stages=[['确定方向','写下想法或从真实线索中寻找方向',Lightbulb],['选好主题','所有来源的选题统一存入选题库',BookOpen],['制作内容','进入专页完成文案、图片或视频',PenLine],['整理作品','复用文稿、形象、声音与画面',FolderOpen],['平台交付','生成并修改平台所需的完整内容',Send]] as const;
const tools=[['text','文案创作','text'],['image','图片创作','text_image'],['video','AI 视频','text_video'],['avatar/text','数字人口播','text_avatar'],['audio/tts','文本配音','tts'],['compose','素材成片','compose']] as const;
const platforms=[['wechat','公众号'],['channels','视频号'],['douyin','抖音']] as const;
export default function CreationFlow({t}:{t:any}){
 const owner=t.state.user.id,storage='studio-flow:'+owner;
 const [flow,setFlow]=useState<any>(()=>{try{return JSON.parse(localStorage.getItem(storage)||'{}')}catch{return {}}}),[assets,setAssets]=useState<any[]>([]),[catalog,setCatalog]=useState<any[]>([]),[topics,setTopics]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 const version=useRef(0),dirty=useRef(false),queue=useRef(Promise.resolve()),saveTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 useEffect(()=>{void api('/studio/flow').then(r=>{version.current=r.version;if(!dirty.current&&r.version)setFlow(r);setLoaded(true)}).catch(e=>setError(e.message))},[]);
 useEffect(()=>{if(!loaded||!dirty.current)return;const timer=setTimeout(()=>{queue.current=queue.current.catch(()=>{}).then(async()=>{try{const r=await api('/studio/flow',{...flow,version:version.current});version.current=r.version}catch(e:any){setError('流程已暂存本机，服务端保存失败：'+e.message)}})},600);saveTimer.current=timer;return()=>clearTimeout(timer)},[flow,loaded]);
 useEffect(()=>{void Promise.all([api('/studio/assets'),api('/studio/catalog'),api('/studio/topics')]).then(([a,c,b])=>{setAssets(a.items||[]);setCatalog(c.tools||[]);setTopics(b.items||[])}).catch(e=>setError(e.message))},[]);
 const change=(v:any)=>{dirty.current=true;const next={...flow,...v};setFlow(next);try{localStorage.setItem(storage,JSON.stringify(next))}catch{setError('本机保存失败，请检查存储空间')}};
 const stage=Math.min(4,Math.max(0,Number(flow.stage)||0)),choice=tools.find(x=>x[0]===(flow.tool_path||'text'))||tools[0],topic=topics.find(x=>x.id===flow.topic_id);
 const ensureTopic=async()=>{if(topic)return topic.id;if(!flow.brief?.trim())throw new Error('请先写下主题或从选题库选择');const made=await api('/studio/topics',{title:flow.brief.trim().slice(0,200),angle:'从一站式创作继续完善',source_ids:[],profile_id:flow.profile_id||'',origin:'一站式创作',origin_ref:'flow:'+flow.brief.trim().slice(0,150),status:'selected'});setTopics(v=>[made,...v.filter(x=>x.id!==made.id)]);change({topic_id:made.id});return made.id};
 const launch=async()=>{setBusy(true);setError('');try{if(!loaded)throw new Error('正在恢复流程，请稍候');clearTimeout(saveTimer.current);await queue.current;const topicId=await ensureTopic();const [path,,tool]=choice,source=flow.content_id?t.get(flow.content_id):null,brief=topic?.title||flow.brief||'';
  const input=tool==='text'?{brief,format:'通用文案'}:['text_avatar','tts'].includes(tool)?{text:source?.body||brief}:tool==='compose'?{scenes:flow.visual_id?[{asset_id:flow.visual_id,length:5,...(flow.audio_id?{audio_id:flow.audio_id}:{})}]:[]}:{prompt:brief};
  const saved=await api('/studio/flow',{...flow,topic_id:topicId,stage:2,version:version.current});version.current=saved.version;
  const draft=await api(tool==='text'?'/studio/text/drafts':'/studio/drafts',{title:brief.slice(0,60)||'一站式创作',tool,input,brand_id:flow.brand_id||'',profile_id:flow.profile_id||'',source_ids:flow.content_id?[flow.content_id]:[],...(tool==='text'?{}:{options:{}})});
  change({last_draft:draft.id,topic_id:topicId,stage:2});location.hash='studio/'+path+'?draft='+draft.id+'&mode='+tool+'&return='+encodeURIComponent('studio/flow');
 }catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const openDelivery=async()=>{setBusy(true);setError('');try{const topicId=await ensureTopic();change({stage:4});location.hash='studio/topics?topic='+encodeURIComponent(topicId)+'&platform='+encodeURIComponent(flow.platform||'wechat')+'&return=studio%2Fflow'}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 return <div className="cf-page"><header className="cf-head"><small>一站式创作 · 从想法到交付</small><h2>跟着这条线，完成一件作品</h2><p>每一步都可以单独打开。资料与草稿会保存，做完一项再回来继续。</p></header>
 <nav className="cf-stepper" aria-label="创作步骤">{stages.map(([name,desc,Icon],i)=><button key={name} className={i===stage?'current':i<stage?'visited':''} onClick={()=>change({stage:i})} aria-current={i===stage?'step':undefined}><span className="cf-step-dot">{i<stage?<Check size={15}/>:<Icon size={16}/>}</span><strong>{String(i+1).padStart(2,'0')} {name}</strong><small>{desc}</small></button>)}</nav>
 <section className="cf-detail"><div className="cf-detail-top"><span>第 {stage+1} 步 / 共 5 步</span><strong>{stages[stage][0]}</strong></div>
 {stage===0&&<div className="cf-step-body"><p>先写下你想讲的事，也可以从真实行业信息和对标内容找灵感。</p><label>这次想讲什么？<textarea rows={4} value={flow.brief||''} onChange={e=>change({brief:e.target.value,topic_id:''})} placeholder="例如：物业客户如何判断旧电梯是否需要更新"/></label><label>以谁的身份表达？<select value={flow.profile_id||''} onChange={e=>change({profile_id:e.target.value})}><option value="">先不指定</option>{t.list('profile').map((p:any)=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><div className="cf-actions"><a href="#benchmark">去看灵感与对标 →</a><button className="primary" onClick={()=>change({stage:1})}>下一步：选题 <ArrowRight size={16}/></button></div></div>}
 {stage===1&&<div className="cf-step-body"><p>选题库会记录雷达、对标、AI 建议和自己添加的主题。以后可以继续创作或二次创作。</p><label>从选题库选择<select value={flow.topic_id||''} onChange={e=>{const x=topics.find(v=>v.id===e.target.value);change({topic_id:e.target.value,...(x?{brief:x.title}:{})})}}><option value="">{flow.brief?'使用刚才写下的想法':'请选择选题'}</option>{topics.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label>{topic&&<p className="cf-selected">已选：{topic.title} · {topic.origin||'自己添加'}</p>}<div className="cf-actions"><a href="#studio/topics?return=studio%2Fflow">打开选题库 →</a><button className="primary" disabled={!flow.brief?.trim()&&!flow.topic_id} onClick={()=>change({stage:2})}>下一步：做内容 <ArrowRight size={16}/></button></div></div>}
 {stage===2&&<div className="cf-step-body"><p>选择一种本次要完成的作品，进入专门页面制作。创作完成后可返回这条流程。</p><label>这次制作什么？<select value={choice[0]} onChange={e=>change({tool_path:e.target.value})}>{tools.map(([path,label])=><option key={path} value={path}>{label}</option>)}</select></label><p className="cf-capability">{choice[2]==='text'?t.state.bindings.writing?'文本服务已配置':'文本模型未配置，可先保存草稿':catalog.find(c=>c.id===choice[2])?.configured?'生成服务已配置':'生成服务未就绪，可先保存草稿'}</p><div className="cf-actions"><button className="primary" disabled={busy||(!flow.brief?.trim()&&!flow.topic_id)} onClick={()=>void launch()}>{busy?'正在打开…':'进入'+choice[1]} <ArrowRight size={16}/></button><button onClick={()=>change({stage:3})}>已有作品，下一步</button></div></div>}
 {stage===3&&<div className="cf-step-body"><p>把已有文稿、画面和声音接到下一次创作。作品和素材保存在同一个地方。</p><div className="cf-asset-grid"><label>文稿<select value={flow.content_id||''} onChange={e=>change({content_id:e.target.value})}><option value="">暂不选择</option>{t.list('content').map((x:any)=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label><label>画面<select value={flow.visual_id||''} onChange={e=>change({visual_id:e.target.value})}><option value="">暂不选择</option>{assets.filter(x=>['image','video'].includes(x.asset_type)&&x.status==='ready').map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label><label>声音<select value={flow.audio_id||''} onChange={e=>change({audio_id:e.target.value})}><option value="">暂不选择</option>{assets.filter(x=>x.asset_type==='audio'&&x.status==='ready').map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label></div><div className="cf-actions"><a href="#studio/works">打开作品与素材 →</a><button className="primary" onClick={()=>change({stage:4})}>下一步：平台交付 <ArrowRight size={16}/></button></div></div>}
 {stage===4&&<div className="cf-step-body"><p>为目标平台准备标题、正文或口播、分镜、封面建议和素材。完成后可以修改、保存与导出。</p><label>要交付到哪里？<select value={flow.platform||'wechat'} onChange={e=>change({platform:e.target.value})}>{platforms.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><div className="cf-actions"><button className="primary" disabled={busy||(!flow.brief?.trim()&&!flow.topic_id)} onClick={()=>void openDelivery()}>{busy?'正在打开…':'打开平台交付页'} <ArrowRight size={16}/></button></div><small>导出是交付准备，不代表已发布到平台。</small></div>}
 </section>{error&&<p className="cf-error" role="alert">{error}</p>}</div>;
}
