import {useEffect,useState} from 'react';
import {LoaderCircle} from 'lucide-react';
export function DesktopUpdates(){
 const bridge=(window as any).tijianDesktop?.updates;
 const [state,setState]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[runningAction,setRunningAction]=useState(''),[installConfirmed,setInstallConfirmed]=useState(false);
 useEffect(()=>{if(!bridge)return;void bridge.getState().then(setState).catch(()=>setError('无法读取桌面版本信息'));return bridge.onState(setState)},[]);
 const run=async(action:string)=>{setError('');setBusy(true);setRunningAction(action);try{const result=await bridge[action]();if(result&&typeof result==='object')setState(result);if(action==='install'&&!result)setError('尚不能安装，请检查下载状态')}catch{setError('操作未完成，请稍后重试')}finally{setBusy(false);setRunningAction('')}};
 return <section className="surface"><h2>软件版本与更新</h2>{!bridge?<p>浏览器预览不安装桌面更新。请在桌面客户端查看版本。</p>:<><p>当前版本：{state?.currentVersion||'读取中…'}{state?.availableVersion&&' · 新版本 '+state.availableVersion}</p>{busy&&<p role="status"><LoaderCircle className="spin" size={15}/> {runningAction==='check'?'正在检查更新…':runningAction==='download'?'正在开始下载…':'正在准备安装…'}</p>}<p role="status">{state?.message}</p>{state?.status==='downloading'&&<progress max={100} value={state.progress||0} aria-label="更新下载进度"/>}<div className="button-row"><button disabled={busy||!state||['development','unconfigured','checking','downloading','downloaded'].includes(state.status)} onClick={()=>void run('check')}>{runningAction==='check'?'检查中…':'检查更新'}</button>{state?.availableVersion&&state.status!=='downloaded'&&<button disabled={busy||state.status==='downloading'} onClick={()=>void run('download')}>{runningAction==='download'?'正在开始下载…':state.status==='error'?'重试下载':'下载更新'}</button>}</div>{state?.status==='downloaded'&&<><label className="switch-row"><input type="checkbox" checked={installConfirmed} onChange={e=>setInstallConfirmed(e.target.checked)}/>我已保存当前编辑，确认退出软件并安装更新</label><button className="primary" disabled={busy||!installConfirmed} onClick={()=>void run('install')}>{runningAction==='install'?'正在准备安装…':'退出并安装更新'}</button></>}</>}{error&&<p role="alert" className="form-error">{error}</p>}</section>;
}
