import {useEffect,useRef,useState} from 'react';
import {RefreshCw,Download,ExternalLink,Bell,Check,Video,Image as ImageIcon} from 'lucide-react';
import {api,getToken,download} from './api';
import {ScopedProgress} from './WorkPages';
import {CollectionResult,jobStatus} from './CollectionResult';
import './douyin.css';
export async function douyinBridge(action:string,benchmark_id?:string){const b=(window as any).tijianDesktop;if(!b?.douyin)throw Error('请使用0.10.0或更新版本的桌面软件获取抖音作品');return b.douyin({action,benchmark_id,token:getToken()})}
export function DouyinConnection({auth}:any){
 useEffect(()=>{if(!auth)return;const token=getToken();let alive=true;const connect=()=>douyinBridge('connect').catch(()=>{});void connect();const id=setInterval(()=>{if(alive)void connect()},20000);return()=>{alive=false;clearInterval(id);void (window as any).tijianDesktop?.douyin({action:'disconnect',token}).catch(()=>{})}},[auth]);return null;
}
export function DouyinNotifications({t}:any){
 const notices=t.list('douyin_notice').filter((x:any)=>!x.read);if(!notices.length)return null;
 return <a className="douyin-inbox" href={'#benchmark/'+notices[0].benchmark_id+'/automatic'}><Bell size={16}/>抖音有 {notices.length} 条作品更新</a>
}
export function DouyinLibrary({account,t}:any){
 const [state,setState]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState((t.route||'').endsWith('/automatic')?'subscription':'works'),[selected,setSelected]=useState<string[]>([]),[query,setQuery]=useState(''),[limit,setLimit]=useState(30),[minutes,setMinutes]=useState(360),[onlyDownloads,setOnlyDownloads]=useState(false);
 const request=useRef(0);
 const refresh=async()=>{const sequence=++request.current;const d=await api('/douyin/'+account.id+'/status');if(sequence===request.current)setState(d);return d};
 useEffect(()=>{if((t.route||'').endsWith('/automatic'))setTab('subscription')},[t.route]);
 useEffect(()=>{let valid=true;setState(null);setSelected([]);setError('');refresh().then(d=>{if(valid)setMinutes(d.subscription?.interval_minutes||360)}).catch(e=>valid&&setError(e.message));const id=setInterval(()=>{if(valid)void refresh().catch(e=>valid&&setError(e.message))},3500);return()=>{valid=false;request.current++;clearInterval(id)}},[account.id]);
 const run=async(fn:()=>Promise<any>)=>{setBusy(true);setError('');try{await fn();await refresh();await t.refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const jobs=t.list('job').filter((x:any)=>x.input?.benchmark_id===account.id&&x.input?.action?.startsWith('douyin_'));const running=jobs.some((j:any)=>['queued','running'].includes(j.status));
 const rows=(state?.works||[]).filter((x:any)=>x.title.includes(query)&&(!onlyDownloads||x.files?.length)).sort((a:any,b:any)=>b.create_time-a.create_time);const sub=state?.subscription;
 const scan=()=>run(async()=>{await douyinBridge('connect');await api('/douyin/'+account.id+'/scan',{limit});t.setToast('正在获取作品，遇到验证时请打开抖音窗口')});
 return <div className="douyin-library"><header className="douyin-heading"><div><span className="section-number">抖音 · 对标作品库</span><h2>{account.title}</h2><p>作品列表、发布文案与本地媒体分别管理</p></div><strong>{state?.works?.length||0}<small>条已发现作品</small></strong></header><div className="douyin-actions"><button disabled={busy} onClick={()=>void run(()=>douyinBridge('open',account.id))}><ExternalLink size={15}/>打开抖音 / 登录验证</button><label>本次最多 <select aria-label="抖音获取数量" value={limit} onChange={e=>setLimit(Number(e.target.value))}><option value="30">30条</option><option value="60">60条</option><option value="100">100条</option></select></label><button className="primary" disabled={busy||running} onClick={()=>void scan()}><RefreshCw size={15}/>获取作品</button><a className="settings-link" href={'#settings/benchmark/'+account.id+'/saved'}>账号设置 →</a></div><nav className="work-tabs"><button className={tab==='works'?'active':''} onClick={()=>setTab('works')}>作品与下载</button><button className={tab==='subscription'?'active':''} onClick={()=>setTab('subscription')}>订阅与通知 <span>{state?.notices?.length||0}</span></button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}>获取记录</button></nav>{error&&<p className="form-error" role="alert">{error}</p>}<ScopedProgress jobs={jobs} label="抖音作品" getSource={t.get}/>
 {tab==='works'&&<><div className="douyin-filter"><input aria-label="搜索抖音作品" placeholder="搜索作品文案" value={query} onChange={e=>setQuery(e.target.value)}/><label><input type="checkbox" checked={onlyDownloads} onChange={e=>setOnlyDownloads(e.target.checked)}/>仅已下载</label><span>{rows.length} 条</span></div><div className="douyin-selection"><label><input type="checkbox" checked={!!rows.length&&rows.every((x:any)=>selected.includes(x.id))} onChange={e=>setSelected(e.target.checked?rows.map((x:any)=>x.id):[])}/>全选当前列表</label><span>已选 {selected.length}</span><button disabled={busy||running||!selected.length||selected.length>30} onClick={()=>void run(async()=>{await douyinBridge('connect');await api('/douyin/'+account.id+'/download',{ids:selected});t.setToast('开始下载所选作品；进度见获取记录')})}><Download size={14}/>下载媒体（最多30条）</button><button disabled={busy||!selected.length} onClick={()=>void run(async()=>{for(const id of selected)await api('/douyin/works/'+id+'/save',{});t.setToast('发布文案已存入原始资料，可用于分析与创作')})}>保存所选文案</button></div><p className="douyin-caption">“文案”是作品发布时的文字，未自动转写视频口播。下载保存平台可访问的视频或图文图片；可见范围与失败项会单独记录。</p><div className="douyin-work-list">{rows.map((x:any)=><article key={x.id}><input type="checkbox" aria-label={'选择'+x.title} checked={selected.includes(x.id)} onChange={e=>setSelected(e.target.checked?[...selected,x.id]:selected.filter(id=>id!==x.id))}/><div className="douyin-kind">{x.media_type==='images'?<ImageIcon size={20}/>:<Video size={20}/>}<small>{x.media_type==='images'?'图文':'视频'}</small></div><div className="douyin-work-main"><a href={x.url} target="_blank" rel="noreferrer">{x.title}</a><p>{x.published?new Date(x.published).toLocaleString('zh-CN'):'发布日期未知'} · {x.author||'发布者'} · 赞 {x.metrics?.like??'未知'} · 评论 {x.metrics?.comment??'未知'}</p><details><summary>查看文案与文件</summary><p>{x.description||'平台未提供文案'}</p>{x.files?.map((f:any,i:number)=><button key={f.name} onClick={()=>void run(()=>download('/douyin/works/'+x.id+'/file/'+i,x.aweme_id+'-'+f.name))}><Download size={14}/>{f.name} · {(f.size/1024/1024).toFixed(1)}MB</button>)}</details></div><span className={'douyin-download-state '+(x.files?.length?'done':'')}>{x.files?.length?<><Check size={14}/>已下载 {x.files.length} 个文件</>:'未下载媒体'}</span><button onClick={()=>void run(async()=>{const source=await api('/douyin/works/'+x.id+'/save',{});await t.openTask('分析这条抖音作品的发布文案、受众和表达方式；没有视频转写，不能假装看过视频：'+x.title,'benchmark',[source.id])})}>分析文案</button></article>)}</div>{!rows.length&&<div className="radar-welcome"><h3>从这个博主的作品开始</h3><p>点击上方“获取作品”。需要登录或验证时，在抖音窗口完成即可。无需填写 RSS。</p></div>}</>}
 {tab==='subscription'&&<section className="douyin-subscription"><h3>定期检查这个博主</h3><p>工作台运行且已登录时检查，关闭或休眠期间暂停。首轮建立基线，不提醒历史作品；之后发现新增作品时生成站内通知。</p><div className="button-row"><label>检查间隔 <select value={minutes} onChange={e=>setMinutes(Number(e.target.value))}><option value="30">30分钟</option><option value="60">1小时</option><option value="360">6小时</option><option value="1440">每天</option></select></label><button className="primary" disabled={busy} onClick={()=>void run(()=>api('/douyin/'+account.id+'/subscription',{enabled:true,interval_minutes:minutes},'PUT'))}>{sub?.enabled?'保存订阅设置':'开启订阅'}</button>{sub?.enabled&&<button disabled={busy} onClick={()=>void run(()=>api('/douyin/'+account.id+'/subscription',{enabled:false},'PUT'))}>暂停订阅</button>}</div><p className="muted">每轮检查最多30条平台返回的作品，密集更新或长期离线可能漏项；只通知和保存目录，不自动下载大量媒体。访问失败会退避，需验证时请主动打开抖音窗口。</p>{sub&&<div className="douyin-sub-status"><strong>{sub.enabled?'订阅已开启':'订阅已暂停'}</strong><p>上次成功：{sub.last_success?new Date(sub.last_success).toLocaleString('zh-CN'):'尚未成功'} · 下次检查：{sub.enabled?new Date(sub.next_check*1000).toLocaleString('zh-CN'):'已暂停'}</p><p>{sub.coverage}</p>{sub.error&&<p className="form-error">{sub.error}</p>}</div>}<h3>新增作品通知 · {state?.notices?.length||0}</h3>{state?.notices?.map((n:any)=><div className="douyin-notice" key={n.id}><a href={n.url} target="_blank" rel="noreferrer">{n.title}</a><button onClick={()=>void run(()=>api('/douyin/notices/'+n.id+'/read',{}))}>标为已读</button></div>)}</section>}
 {tab==='history'&&<section>{jobs.map((j:any)=><details className="douyin-history" key={j.id}><summary>{j.title} · {jobStatus(j)} · {j.input.trigger==='automatic'?'自动检查':'手动操作'}</summary><CollectionResult job={j} getSource={t.get}/>{j.error&&<p className="form-error">{j.error}</p>}</details>)}</section>}
 </div>
}
