import {useEffect,useState} from 'react';
import {api} from './api';

type Item={id?:string;title:string;body:string;source:string;scope:string;valid_from:string;valid_to:string;type:'knowledge';purpose:'qa';status:'draft'|'published'|'disabled';version?:number;updated?:string};
const empty:Item={title:'',body:'',source:'',scope:'',valid_from:'',valid_to:'',type:'knowledge',purpose:'qa',status:'draft'};

export default function KnowledgeAdmin(){
 const [items,setItems]=useState<Item[]>([]),[draft,setDraft]=useState<Item>({...empty}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const load=async()=>{const result=await api('/admin/state');setItems((result.editorial||[]).filter((x:Item)=>x.type==='knowledge'&&x.purpose==='qa'))};
 useEffect(()=>{void load().catch((e:Error)=>setError(e.message))},[]);
 const save=async(status:Item['status'])=>{setBusy(true);setError('');setNotice('');try{const result=await api('/admin/resources',{...draft,status});setDraft(result);await load();setNotice(status==='published'?'已发布；后续知识问答可引用此资料。':status==='disabled'?'已停用；后续问答不再使用。':'草稿已保存。')}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 return <section className="surface"><div className="section-heading"><div><h2>系统知识资料</h2><p>管理销售沟通口径、工具使用说明和行业资料。只有“已发布”的内容会进入后续知识问答。</p></div><button onClick={()=>{setDraft({...empty});setError('');setNotice('')}}>新增资料</button></div><div style={{display:'grid',gridTemplateColumns:'minmax(210px,300px) minmax(0,1fr)',gap:20}}><div style={{display:'grid',gap:8,alignContent:'start'}}>{items.map(x=><button key={x.id} onClick={()=>{setDraft(x);setError('');setNotice('')}} style={{textAlign:'left',padding:12,border:'1px solid #dce5df',borderRadius:9,background:draft.id===x.id?'#ebf5ef':'white'}}><strong>{x.title}</strong><small style={{display:'block',marginTop:4}}>{x.status==='published'?'已发布':x.status==='disabled'?'已停用':'草稿'} · v{x.version}</small></button>)}{!items.length&&<p>暂无系统资料</p>}</div><div><label className="field">资料名称<input value={draft.title} maxLength={120} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="例如：售后服务沟通口径"/></label><label className="field">资料来源<input value={draft.source||''} maxLength={500} onChange={e=>setDraft({...draft,source:e.target.value})} placeholder="例如：公司确认的售后流程 2026 版"/></label><label className="field">适用范围<input value={draft.scope||''} maxLength={500} onChange={e=>setDraft({...draft,scope:e.target.value})} placeholder="例如：本公司华南区代理业务"/></label><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><label className="field">生效日期<input type="date" value={draft.valid_from||''} onChange={e=>setDraft({...draft,valid_from:e.target.value})}/></label><label className="field">失效日期（可留空）<input type="date" value={draft.valid_to||''} onChange={e=>setDraft({...draft,valid_to:e.target.value})}/></label></div><label className="field">资料正文<textarea value={draft.body} rows={12} maxLength={60000} onChange={e=>setDraft({...draft,body:e.target.value})} placeholder="写明可引用事实与需核对条件。不要放 API Key。"/></label><p>来源、范围与生效日期在发布前必填。修改已发布资料会生成新版本，原版本保留在后台记录中。</p><div className="button-row"><button disabled={busy||!draft.title.trim()||!draft.body.trim()} onClick={()=>void save('draft')}>保存草稿</button><button className="primary" disabled={busy||!draft.title.trim()||!draft.body.trim()||!draft.source?.trim()||!draft.scope?.trim()||!draft.valid_from} onClick={()=>void save('published')}>保存并发布</button>{draft.id&&<button disabled={busy} onClick={()=>void save('disabled')}>停用</button>}</div>{notice&&<p role="status">{notice}</p>}{error&&<p role="alert" className="form-error">{error}</p>}</div></div></section>;
}
