import {useEffect,useRef,useState} from 'react';
import {BookOpen,FileSpreadsheet,FileText,FolderPlus,Link2,RefreshCw,Upload} from 'lucide-react';
import {api,download} from './api';
import './system-library.css';

type Row={id:string;kind:string;title:string;status:string;folder_id?:string;parent_id?:string;source_id?:string;source?:string;scope?:string;valid_from?:string;valid_to?:string;parse_status?:string;parse_error?:string;size?:number;version?:number;updated?:string;links?:string[];body?:string;filename?:string;sha256?:string};
type Data={folders:Row[];sources:Row[];wiki:Row[];counts:Record<string,number>;last_link_run:{at?:string}};
const empty:Data={folders:[],sources:[],wiki:[],counts:{},last_link_run:{}};
const mb=(n:number)=>n>=1_000_000?(n/1_000_000).toFixed(1)+' MB':Math.ceil(n/1000)+' KB';
export default function KnowledgeAdmin(){
 const [data,setData]=useState<Data>(empty),[folder,setFolder]=useState(''),[view,setView]=useState<'sources'|'wiki'>('sources'),[selected,setSelected]=useState(''),[detail,setDetail]=useState<Row|null>(null),[query,setQuery]=useState('');
 const [busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[create,setCreate]=useState<'document'|'spreadsheet'|'pdf'|null>(null);
 const file=useRef<HTMLInputElement>(null);
 const load=async()=>setData(await api<Data>('/admin/system-library'));
 useEffect(()=>{void load().catch((e:Error)=>setError(e.message))},[]);
 const act=async(label:string,run:()=>Promise<any>)=>{setBusy(label);setError('');setNotice('');try{const result=await run();await load();setNotice(label+'完成');return result}catch(e:any){setError(e.message);return null}finally{setBusy('')}};
 const open=async(row:Row)=>{setSelected(row.id);setError('');try{setDetail(await api<Row>('/admin/system-library/'+row.id))}catch(e:any){setError(e.message)}};
 const update=async(patch:any)=>{if(!detail)return;const result=await act('保存',()=>api<Row>('/admin/system-library/'+detail.id,{...patch,version:detail.version},'PATCH'));if(result)setDetail(result)};
 const upload=async(f:File)=>{const body=new FormData();body.append('file',f);body.append('folder_id',folder);const result=await act('上传',()=>api<Row>('/admin/system-library/upload',body));if(result){setView('sources');void open(result)}};
 const createFolder=()=>{const title=prompt('新分类名称');if(title?.trim())void act('新建分类',()=>api('/admin/system-library/folders',{title:title.trim(),parent_id:folder||null}))};
 const folders=new Map(data.folders.map(x=>[x.id,x]));
 const inFolder=(x:Row)=>{if(!folder)return true;let parent=x.folder_id;for(let i=0;i<8&&parent;i++){if(parent===folder)return true;parent=folders.get(parent)?.parent_id}return false};
 const visible=data[view].filter(x=>inFolder(x)&&(!query||[x.title,x.source,x.scope].join(' ').toLowerCase().includes(query.toLowerCase())));
 const tree=(parent?:string,depth=0):React.ReactNode=>data.folders.filter(x=>(x.parent_id||'')===(parent||'')).map(x=><div key={x.id}><button className={'sl-folder '+(folder===x.id?'active':'')} style={{paddingLeft:14+depth*16}} onClick={()=>{setFolder(x.id);setSelected('');setDetail(null)}}>▸ {x.title}</button>{tree(x.id,depth+1)}</div>);
 const activeSource=detail?.kind==='system_wiki'?data.sources.find(x=>x.id===detail.source_id):detail?.kind==='system_source'?detail:null;
 return <section className="system-library"><header className="sl-header"><div><p className="sl-eyebrow">SYSTEM KNOWLEDGE / ADMIN</p><h2>系统知识库</h2><p>文件是依据，Wiki 是可更新的整理层。只有发布的内容会进入用户问答。</p></div><div className="button-row"><button onClick={createFolder}><FolderPlus size={16}/> 新建分类</button><button className="primary" onClick={()=>file.current?.click()}><Upload size={16}/> 上传文件</button><input ref={file} hidden type="file" accept=".pdf,.docx,.xlsx,.md,.txt,.csv" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value=''}}/></div></header>{busy&&<p className="sl-progress" role="status"><RefreshCw className="spin" size={15}/> {busy}中，请稍候…</p>}
 <div className="sl-stats"><div><strong>{data.counts.sources||0}</strong><span>原始文件</span></div><div><strong>{data.counts.pending||0}</strong><span>待解析</span></div><div><strong>{data.counts.failed||0}</strong><span>解析失败</span></div><div><strong>{(data.counts.broken||0)+(data.counts.orphan_wiki||0)}</strong><span>异常资料</span></div><div><strong>{data.counts.published||0}</strong><span>已发布 Wiki</span></div><div><strong>{data.counts.links||0}</strong><span>知识关联</span></div></div>
 {error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p role="status" className="admin-notice">{notice}</p>}
 <div className="sl-layout"><aside className="sl-tree"><div className="sl-pane-title">资料分类 <small>最多六级</small></div><button className={'sl-folder '+(!folder?'active':'')} onClick={()=>{setFolder('');setSelected('');setDetail(null)}}>全部资料</button>{tree()}{!data.folders.length&&<p className="muted">先建立业务分类，也可直接上传到根目录。</p>}</aside>
 <div className="sl-main"><div className="sl-toolbar"><div className="sl-tabs"><button className={view==='sources'?'active':''} onClick={()=>{setView('sources');setDetail(null)}}>原始文件 <span>{data.sources.length}</span></button><button className={view==='wiki'?'active':''} onClick={()=>{setView('wiki');setDetail(null)}}>Wiki 页面 <span>{data.wiki.length}</span></button></div><input aria-label="搜索资料" placeholder="搜索名称、来源或适用范围" value={query} onChange={e=>setQuery(e.target.value)}/></div>
 <div className="sl-table"><div className="sl-table-head"><span>名称</span><span>状态</span><span>大小 / 版本</span><span>更新</span></div>{visible.map(row=><button className={'sl-row '+(selected===row.id?'active':'')} key={row.id} onClick={()=>void open(row)}><span className="sl-name">{view==='sources'?<FileText size={16}/>:<BookOpen size={16}/>}<strong>{row.title}</strong></span><span className={'sl-status '+(row.status==='published'?'live':row.parse_status==='failed'?'failed':'')}>{row.parse_status==='failed'?'解析失败':row.parse_status==='pending'?'待解析':row.status==='published'?'已发布':row.status==='disabled'?'已停用':'草稿'}</span><span>{view==='sources'?mb(row.size||0):'v'+row.version}</span><span>{row.updated?new Date(row.updated).toLocaleDateString('zh-CN'):'—'}</span></button>)}{!visible.length&&<p className="sl-empty">当前分类没有{view==='sources'?'原始文件':'Wiki 页面'}。可以上传文件或在线新建。</p>}</div>
 <div className="sl-create"><strong>在线新建</strong><button onClick={()=>setCreate('document')}><FileText size={16}/> 文档</button><button onClick={()=>setCreate('spreadsheet')}><FileSpreadsheet size={16}/> Excel</button><button onClick={()=>setCreate('pdf')}><FileText size={16}/> PDF</button><small>在线新建也会保存为不可改动的原件；更正时创建新文件。</small></div>
 <div className="sl-maintenance"><Link2 size={16}/><span>夜间 02:00 自动更新 Wiki 页面之间的关联。上次：{data.last_link_run?.at?new Date(data.last_link_run.at).toLocaleString('zh-CN'):'尚未运行'}</span><button disabled={!!busy} onClick={()=>void act('关联检查',()=>api('/admin/system-library/relink',{}))}><RefreshCw size={14}/> 立即检查</button></div></div>
 <aside className="sl-detail">{detail?<><div className="sl-pane-title">资料详情 <span>v{detail.version}</span></div><h3>{detail.title}</h3><p className="muted">{detail.kind==='system_source'?'原始文件 · 修改资料信息不会改动文件':'Wiki 页面 · 内容可审阅修改'}</p>{detail.kind==='system_source'?<><div className="sl-meta"><span>文件校验</span><code>{detail.sha256?.slice(0,16)}…</code><span>解析状态</span><strong>{detail.parse_status==='parsed'?'已解析':detail.parse_status==='failed'?'失败':'待解析'}</strong></div>{detail.parse_error&&<p className="form-error">{detail.parse_error}</p>}<div className="button-row"><button disabled={!!busy} onClick={()=>void act('解析',async()=>{const value=await api<any>('/admin/system-library/'+detail.id+'/parse',{});setDetail(value.source);return value})}>开始解析 / 重新解析</button><button onClick={()=>void download('/admin/system-library/'+detail.id+'/file',detail.filename||detail.title)}>下载原件</button></div><label className="field">资料名称<input value={detail.title} onChange={e=>setDetail({...detail,title:e.target.value})}/></label><label className="field">资料来源<input value={detail.source||''} onChange={e=>setDetail({...detail,source:e.target.value})}/></label><label className="field">适用范围<input value={detail.scope||''} onChange={e=>setDetail({...detail,scope:e.target.value})}/></label><label className="field">生效日期<input type="date" value={detail.valid_from||''} onChange={e=>setDetail({...detail,valid_from:e.target.value})}/></label><label className="field">失效日期<input type="date" value={detail.valid_to||''} onChange={e=>setDetail({...detail,valid_to:e.target.value})}/></label><button disabled={!!busy} onClick={()=>void update({title:detail.title,source:detail.source,scope:detail.scope,valid_from:detail.valid_from,valid_to:detail.valid_to})}>保存资料信息</button></>:<><p>引用原件：{activeSource?.title||detail.source_id}</p><label className="field">Wiki 标题<input value={detail.title} onChange={e=>setDetail({...detail,title:e.target.value})}/></label><label className="field">整理内容<textarea rows={13} value={detail.body||''} onChange={e=>setDetail({...detail,body:e.target.value})}/></label><button disabled={!!busy} onClick={()=>void update({title:detail.title,body:detail.body})}>保存 Wiki 修订</button>{(detail.links||[]).length>0&&<p className="muted">相关 Wiki：{detail.links?.length} 页</p>}</>}
 <div className="sl-publish"><strong>问答可见性</strong><p>发布前须核对内容；下架原件会一并停用对应 Wiki。</p><div className="button-row"><button className="primary" disabled={!!busy||detail.status==='published'} onClick={()=>void update({status:'published'})}>发布</button><button disabled={!!busy||detail.status==='disabled'} onClick={()=>void update({status:'disabled'})}>停用</button></div></div></>:<div className="sl-placeholder"><BookOpen size={32}/><h3>选择一份资料</h3><p>先上传文件，再点击解析形成 Wiki；核对后分别发布原件和 Wiki。</p></div>}</aside></div>
 {create&&<div className="modal-backdrop"><section className="modal sl-create-modal" role="dialog" aria-modal="true" aria-label="在线新建资料"><h2>在线新建{create==='document'?'文档':create==='spreadsheet'?' Excel':' PDF'}</h2><p>创建后生成原件，后续可解析并整理为 Wiki。</p><form onSubmit={e=>{e.preventDefault();const raw=Object.fromEntries(new FormData(e.currentTarget));void act('创建',()=>api('/admin/system-library/create',{...raw,format:create,folder_id:folder})).then(result=>{if(result){setCreate(null);setView('sources');void open(result)}})}}><label className="field">标题<input name="title" required maxLength={120}/></label><label className="field">内容{create==='spreadsheet'?'（每行一条，逗号分隔单元格）':''}<textarea name="body" rows={10} required/></label><div className="button-row"><button type="button" onClick={()=>setCreate(null)}>取消</button><button className="primary" disabled={!!busy}>创建原件</button></div></form></section></div>}
 </section>
}
