import {LibraryFolders} from './LibraryFolders';
import {folderDescendants} from './ReferencePicker';
import {useState,useEffect} from 'react';
import {Plus,Upload,RefreshCw,BookOpen} from 'lucide-react';
import {api,type Item} from './api';
import Markdown from './Markdown';
import {AcquisitionMeta,fullTime} from './AcquisitionMeta';
import {DeleteRecord} from './DeleteRecord';
import {ExtractKnowledge,KnowledgeJobResult,knowledgeJob,knowledgePath,linkedReferences} from './KnowledgeFlow';
import './knowledge.css';

const sections=[
 ['source','原始资料库','导入即可提问，无需确认。按文件夹管理原文，Wiki 可在后台自动整理。'],
 ['knowledge','Wiki 知识库','按主题持续积累的知识页。优先用于相关提问，数字、引用和细节按需回到原文。自动整理不代表已核实事实。'],
 ['memory','个人记忆','从你的明确发言整理偏好与决定。可随时编辑、停用或删除；身份档案在“我的 IP”维护。'],
 ['task','对话记录','保留完整交流；从对话提炼知识时，仅把用户确认的事项作为依据。'],
 ['issue','需核对','仅处理冲突、不确定信息和旧版遗留建议；普通 Wiki 整理无需逐条确认。'],
];
const missingBody=(x:Item)=>x.kind==='source'&&(!x.body?.trim()||(x.url&&[x.title,x.url].includes(x.body.trim())));
const stateLabel:Record<string,string>={auto:'自动整理',pending:'需核对',accepted:'人工整理',ready:'正文已保存',summary:'仅摘要',resolved:'已处理',rejected:'已忽略'};
export function KnowledgePage(t:any){
 const [,segment,target]=t.route.split('/');
 const tab=segment==='issues'?'issue':sections.some(x=>x[0]===segment)?segment:'source';
 const [search,setSearch]=useState(''),[folder,setFolder]=useState(''),[selected,setSelected]=useState<string[]>([]),[versions,setVersions]=useState<any[]|null>(null);
 const folderIds=folder&&folder!=='unfiled'?folderDescendants(t.list('folder'),folder):null;
 const organized=['source','knowledge','memory'].includes(tab);
 const items=t.list(tab).filter((x:Item)=>(tab!=='issue'||x.status==='pending'||x.id===target)&&(!organized||!folder||(folder==='unfiled'?!x.folder_id:folderIds?.has(x.folder_id)))&&(!search||[x.title,x.body].join(' ').toLowerCase().includes(search.toLowerCase())));
 const item=target?items.find((x:Item)=>x.id===target):items[0];
 useEffect(()=>{setVersions(null)},[item?.id]);
 const job=segment==='job'?t.get(target):null;
 const latest=item?t.list('job').find((j:Item)=>knowledgeJob(j)&&j.input?.source_ids?.includes(item.id)):null;
 const pending=t.list('issue').filter((x:Item)=>x.status==='pending').length;
 const changeTab=(kind:string)=>{setSearch('');setFolder('');setSelected([]);setVersions(null);location.hash='knowledge/'+(kind==='issue'?'issues':kind)};
 const edit=(x:Item)=>t.editItem(x,[{key:'title',label:'标题',required:true},...(x.kind==='task'?[]:[{key:'body',label:'正文内容',type:'textarea',required:true}]),...(x.kind==='source'?[{key:'url',label:'来源链接（保存链接不会自动下载正文）'}]:[]),...(['knowledge','memory'].includes(x.kind)?[{key:'region',label:'适用范围'},{key:'valid_from',label:'有效起点（有依据才填）'},{key:'valid_to',label:'有效终点'}]:[])]);
 const review=(x:Item)=>t.setForm({title:'确认并保存'+(x.candidate_kind==='memory'?'个人记忆':'知识'),description:'确认后，内容会出现在“'+(x.candidate_kind==='memory'?'个人记忆':'Wiki 知识库')+'”，并可用于相关回答。',fields:[{key:'title',label:'标题',value:x.title,required:true},{key:'body',label:'核对后的内容',type:'textarea',value:x.body,required:true},{key:'region',label:'适用范围',value:x.region},{key:'valid_from',label:'有效起点（有依据才填）',value:x.valid_from},{key:'valid_to',label:'有效终点',value:x.valid_to}],submit:'确认保存',action:async(d:any)=>{const result=await api<Item>('/issues/'+x.id+'/resolve',{...d,version:x.version,action:x.conflicts?.length?'keep_both':'accept'});await t.refresh();location.hash='knowledge/'+(x.candidate_kind==='memory'?'memory':'knowledge')+'/'+result.result_id;t.setToast('已保存，可在当前页面查看和修改')}});
 const sources=(x:Item)=><div className="knowledge-evidence"><strong>依据与来源</strong>{x.source_ids?.length?x.source_ids.map((id:string)=>{const source=t.get(id);return <div key={id}>{source&&!source.archived?<a href={knowledgePath(source)}>{source.title} →</a>:<span>来源已删除或不可用；以下保留提炼时的依据</span>}{x.evidence_excerpt?.[id]&&<details><summary>查看提炼时的原文片段</summary><Markdown text={x.evidence_excerpt[id]}/></details>}</div>}):<span>未关联来源</span>}</div>;
 return <div className="knowledge-page">
  <header className="knowledge-heading"><div><h1>知识资产</h1></div><div className="button-row"><details className="knowledge-management"><summary>管理与整理</summary><div className="knowledge-overview">{pending>0?<><span>需核对 <strong>{pending}</strong> 条</span><button className="quiet" onClick={()=>changeTab('issue')}>查看需核对事项 →</button></>:<span>原文可直接提问，无需逐条确认</span>}<a href="#settings/memory">夜间整理与记忆设置 →</a><button className="quiet" onClick={()=>t.action(async()=>{const j=await api<Item>('/synthesis/run',{});location.hash='knowledge/job/'+j.id})}>立即整理新增内容 →</button><a href="#settings/workspace/-/knowledge">存储与备份设置 →</a><button className="quiet" onClick={()=>t.action(()=>api('/knowledge/sync',{}),'已检查；变化可在需核对中查看')}><RefreshCw size={14}/>检查文件变化</button></div></details><button onClick={()=>t.urlForm()}>从链接获取正文</button><button onClick={()=>document.getElementById('file-import')?.click()}><Upload size={16}/>导入文件</button><button className="primary" onClick={()=>t.importForm()}><Plus size={16}/>添加资料</button></div></header>

  <nav className="knowledge-tabs" aria-label="知识分类">{sections.map(([key,name])=><button key={key} className={segment!=='job'&&tab===key?'active':''} onClick={()=>changeTab(key)}>{name}<span>{t.list(key).filter((x:Item)=>key!=='issue'||x.status==='pending').length}</span></button>)}</nav>
  {segment==='job'?(job&&!job.archived?<><h2>本次提炼结果</h2>{['queued','running'].includes(job.status)&&<button onClick={()=>t.action(()=>api('/jobs/'+job.id+'/cancel',{}),'已请求停止提炼')}>停止提炼</button>}<KnowledgeJobResult job={job} get={t.get}/><DeleteRecord item={job} t={t} onDeleted={()=>changeTab('issue')}/></>:<div className="surface">任务不存在或已删除。<a href="#knowledge/issues">查看需核对事项</a></div>):<>
   <div className="knowledge-section-intro"><details><summary>使用说明</summary><p>{sections.find(x=>x[0]===tab)?.[2]}</p></details>{tab==='memory'&&<button onClick={()=>t.newItem('memory','添加个人记忆',[{key:'title',label:'记忆标题',required:true},{key:'body',label:'希望 AI 记住的偏好或决定',type:'textarea',required:true}])}>添加个人记忆</button>}</div>
   <div className={organized?'knowledge-workspace':''}>{organized&&<LibraryFolders t={t} kind={tab} value={folder} onChange={(id:string)=>{setFolder(id);setSelected([])}} selected={selected} onMoved={()=>setSelected([])}/>}<div className="knowledge-layout"><aside className="knowledge-list">{organized&&<div className="library-list-actions"><button onClick={()=>setSelected(items.map((x:Item)=>x.id))}>全选结果</button><button onClick={()=>setSelected([])}>取消选择</button></div>}<input aria-label="搜索当前分类" placeholder="搜索当前分类" value={search} onChange={e=>setSearch(e.target.value)}/>{items.map((x:Item)=><div className={'knowledge-entry '+(item?.id===x.id?'selected':'')} key={x.id}><div className="entry-check">{organized&&<input type="checkbox" aria-label={'选择'+x.title} checked={selected.includes(x.id)} onChange={e=>setSelected(e.target.checked?[...selected,x.id]:selected.filter(id=>id!==x.id))}/>}<button className="knowledge-select" onClick={()=>{location.hash=knowledgePath(x)}}><small>{tab==='issue'?(x.candidate_kind==='memory'?'个人记忆建议':'待核对建议'):missingBody(x)?'待补正文':stateLabel[x.status]||'已保存'}</small><strong>{x.title}</strong><time>{fullTime(x.updated)}</time></button></div><div className="knowledge-row-actions">{tab!=='issue'?<button aria-label={'编辑'+x.title} onClick={()=>edit(x)}>编辑</button>:x.type==='knowledge_candidate'&&x.status==='pending'?<button onClick={()=>review(x)}>审阅修改</button>:null}<DeleteRecord item={x} t={t} compact onDeleted={()=>{if(item?.id===x.id)changeTab(tab)}}/></div></div>)}{!items.length&&<p className="knowledge-empty">{search?'没有匹配的内容。':tab==='issue'?'暂无需核对事项。':'这里还没有内容。'}</p>}</aside>
   <article className="knowledge-reader">{item?<>
    <div className="reader-meta"><span className="badge">{missingBody(item)?'待补正文':stateLabel[item.status]||'已保存'}</span>{item.exclude_ai&&<span>不用于 AI</span>}<small>更新 {fullTime(item.updated)}</small></div><h2>{item.title}</h2>{item.freshness_warning&&<p role="alert" className="candidate-notice">{item.freshness_warning}；当前停止用于 AI，保留内容供查阅。</p>}
    {tab==='issue'?<>
     {item.status==='pending'?<><p className="candidate-notice">{item.type==='file_conflict'?'文件与软件中的内容发生冲突，双方版本均已保留。':item.type==='maintenance'?'请核对下方变化，再标记完成。':'这是 AI 生成的建议，尚未用于长期回答。请核对原文与适用范围。'}</p><div className="button-row">{item.type==='knowledge_candidate'?<><button className="primary" onClick={()=>review(item)}>审阅并保存</button><button onClick={()=>t.action(()=>api('/issues/'+item.id+'/resolve',{action:'reject',version:item.version}),'已忽略；未加入长期知识')}>忽略建议</button></>:item.type==='file_conflict'?<><button onClick={()=>t.action(()=>api('/issues/'+item.id+'/resolve',{action:'use_external'}))}>采用外部文件</button><button onClick={()=>t.action(()=>api('/issues/'+item.id+'/resolve',{action:'use_app'}))}>采用软件版本</button></>:<button onClick={()=>t.action(()=>api('/issues/'+item.id+'/resolve',{action:'accept'}),'已标记完成')}>已查看，完成待办</button>}</div></>:item.result_id&&t.get(item.result_id)&&!t.get(item.result_id).archived?<a className="knowledge-cta" href={knowledgePath(t.get(item.result_id))}>查看已保存内容 →</a>:<p>此建议已处理；保存结果可能已移入回收站。</p>}
     {item.reason&&<p className="candidate-notice">{item.reason}</p>}<Markdown text={item.body||item.local||''}/>{sources(item)}{item.conflicts?.map((id:string)=><section className="comparison" key={id}><h3>已有不同说法</h3><Markdown text={t.get(id)?.body||'记录已不可用'}/><p>不同时间或范围可以同时成立；确认后保留双方。</p></section>)}{item.proposed&&<details><summary>软件内版本</summary><Markdown text={item.proposed}/></details>}<p className="muted">适用范围：{item.region||'未限定'} · 有效起点：{item.valid_from||'未知'} · 结束：{item.valid_to||'未知'}</p>
    </>:<>
     <div className="knowledge-reader-actions"><button className="primary" onClick={()=>t.action(()=>t.openTask('基于所选资料进行研究：'+item.title,'research',[item.id]))}>基于此内容提问 ↗</button>{['source','task'].includes(tab)&&<ExtractKnowledge item={item} t={t}/>}<button onClick={()=>edit(item)}>编辑内容</button><DeleteRecord item={item} t={t} onDeleted={()=>changeTab(tab)}/><button className="quiet" onClick={()=>t.action(()=>t.update(item,{exclude_ai:!item.exclude_ai}))}>{item.exclude_ai?'允许 AI 引用':'不用于 AI'}</button></div>
     {latest&&<a className="knowledge-latest" href={'#knowledge/job/'+latest.id}>{['queued','running'].includes(latest.status)?'正在提炼… 查看进度 →':'查看上次提炼结果 →'} <small>{latest.result?.summary||latest.error||fullTime(latest.created)}</small></a>}
     {item.kind==='source'&&<><AcquisitionMeta item={item}/>{item.url&&(!item.body?.trim()||[item.title,item.url].includes(item.body.trim()))&&<p className="candidate-notice" role="alert">这条资料只有标题或链接，没有文章正文。请点击“从链接获取正文”，或“编辑内容”粘贴原文，再提炼知识。填写来源链接不会自动下载文章。</p>}{item.url&&<a href={item.url} target="_blank" rel="noreferrer">查看来源网页 ↗</a>}</>}
     <div className="knowledge-body"><Markdown text={tab==='task'?(item.messages||[]).map((m:any)=>'### '+(m.role==='user'?'用户':'助手')+'\n'+m.text).join('\n\n')||'这段对话还没有消息。':linkedReferences(item.body||'此资料暂无正文。',t.get)}/></div>{item.source_ids?.length>0&&sources(item)}{item.related_topics?.length>0&&<div className="wiki-links"><strong>相关主题</strong>{item.related_topics.map((title:string)=>{const related=t.list('knowledge').find((x:Item)=>x.title===title);return related?<a key={title} href={knowledgePath(related)}>{title} →</a>:<span className="muted" key={title}>{title}（尚未成页）</span>})}</div>}{['knowledge','memory'].includes(tab)&&<details className="wiki-history" onToggle={e=>{if(e.currentTarget.open)api<any[]>('/objects/'+item.id+'/versions').then(setVersions).catch((e:Error)=>t.setError(e.message))}}><summary>历史版本与恢复</summary>{versions?.filter((v:any,i:number,a:any[])=>v.body&&a.findIndex(x=>x.body===v.body)===i).map((v:any)=><div key={v.version}><strong>版本 {v.version}</strong><Markdown text={v.body}/><button onClick={()=>t.action(()=>api('/knowledge/'+item.id+'/restore/'+v.version,{}),'已恢复为新版本，历史仍保留')}>恢复此版本</button></div>)}</details>}
    </>}
   </>:<div className="knowledge-empty"><BookOpen size={30}/><h3>{target?'内容不存在、已删除或不符合筛选条件':'选择左侧内容查看'}</h3><p>{tab==='issue'?'需要核对的冲突或不确定信息会显示在这里；普通结果自动保存。':'添加或导入资料后，可以查看原文、提问与提炼知识。'}</p>{target&&<button onClick={()=>changeTab(tab)}>返回当前分类</button>}</div>}</article></div></div>
  </>}
 </div>;
}
