import {useRef,useState} from 'react';
import {AudioLines,Film,Image as ImageIcon,Plus,X} from 'lucide-react';
import {api} from './api';
import './media-references.css';

const kinds=[['image','参考图片',ImageIcon,'image/*'],['video','参考视频',Film,'video/*'],['audio','参考音频',AudioLines,'audio/*']] as const;

export default function MediaReferences({draft,model,assets,update,reload,busy}:{draft:any;model:any;assets:any[];update:(v:any)=>void;reload:()=>Promise<void>;busy:boolean}){
 const [error,setError]=useState(''),[uploading,setUploading]=useState(false),[type,setType]=useState<'image'|'video'|'audio'>('image');
 const input=useRef<HTMLInputElement>(null);
 const limits=model?.reference_limits||{};
 const selected=(kind:string):string[]=>{const values=draft.inputs[kind+'_ids'];return Array.isArray(values)&&values.length?values:(kind==='image'&&draft.inputs.image_id?[draft.inputs.image_id]:[])};
 const change=(kind:string,ids:string[])=>update({[kind+'_ids']:ids,...(kind==='image'&&['image_video','image_edit'].includes(draft.tool)?{image_id:ids[0]||''}:{})});
 const add=(kind:string,id:string)=>{const ids=selected(kind);if(!id||ids.includes(id))return;if(ids.length>=(limits[kind]||0)){setError('已达到当前模型的参考素材上限');return}change(kind,[...ids,id]);setError('')};
 const upload=async(files:FileList|null)=>{if(!files?.length)return;setUploading(true);setError('');try{const old=selected(type);if(old.length+files.length>(limits[type]||0))throw Error('所选文件超过当前模型的参考数量上限');const ids:string[]=[];for(const file of Array.from(files)){if(!file.type.startsWith(type+'/'))throw Error('请选择'+type+'类型的文件');const data=new FormData();data.append('file',file);const r=await api('/studio/upload',data);const asset=r.asset||r;if(!asset.id)throw Error('素材上传未返回编号');ids.push(asset.id)}await reload();change(type,[...old,...ids])}catch(e){setError((e as Error).message)}finally{setUploading(false);if(input.current)input.current.value=''}};
 return <section className="media-refs"><div className="media-refs-title"><strong>参考素材</strong><small>{model?.family?.replace('seedance-','Seedance ')||'请先选择模型'}</small></div>{!model?.reference_limits?<p>请先选择支持参考素材的模型。</p>:<>{kinds.filter(([kind])=>(limits[kind]||0)>0).map(([kind,label,Icon,accept])=><div className="media-refs-row" key={kind}><div className="media-refs-label"><Icon size={15}/><b>{label}</b><span>{selected(kind).length} / {limits[kind]}</span></div><div className="media-refs-selected">{selected(kind).map((id,i)=>{const asset=assets.find(a=>a.id===id);return <div key={id} title={asset?.title||id}><span>{kind==='image'?'图':kind==='video'?'视频':'音频'} {i+1} · {asset?.title||'素材'}</span><button aria-label={'移除'+(asset?.title||label)} disabled={busy||uploading} onClick={()=>change(kind,selected(kind).filter(x=>x!==id))}><X size={13}/></button></div>})}</div><div className="media-refs-actions"><select aria-label={'从素材库选择'+label} disabled={busy||uploading||selected(kind).length>=limits[kind]} value="" onChange={e=>add(kind,e.target.value)}><option value="">从素材库选择</option>{assets.filter(a=>a.asset_type===kind&&a.status==='ready'&&!selected(kind).includes(a.id)).map(a=><option key={a.id} value={a.id}>{a.title||a.name}</option>)}</select><button disabled={busy||uploading||selected(kind).length>=limits[kind]} onClick={()=>{setType(kind);setTimeout(()=>input.current?.click(),0)}}><Plus size={13}/>上传</button></div></div>)}<input ref={input} hidden type="file" multiple accept={kinds.find(x=>x[0]===type)?.[3]} onChange={e=>void upload(e.target.files)}/><p>以上为模型公开的参考上限。中转平台可能设置更低上限；点击生成并确认费用后才会上传素材。</p></>}{error&&<p className="mw-error" role="alert">{error}</p>}</section>;
}
