import {useRef,useState} from 'react';
import {Sparkles,Plus,SlidersHorizontal,Expand,Image as ImageIcon,Film,LoaderCircle,ArrowDown,ChevronRight} from 'lucide-react';
import {api} from './api';
import {sendKey} from './inputKeys';
import AssetPicker,{AssetThumbnail,StudioModal} from './AssetPicker';
import MediaReferences from './MediaReferences';
import './media-workbench.css';
import './media-resize.css';
import './media-video.css';
const labels:Record<string,string>={size:'尺寸 / 比例',quality:'质量',resolution:'分辨率',ratio:'画面比例',aspect_ratio:'画面比例',duration:'时长（秒）',generate_audio:'生成声音',output_format:'文件格式',watermark:'水印'};
const optionLabel=(v:any)=>typeof v==='boolean'?(v?'开启':'关闭'):({auto:'自动',low:'标准',medium:'精细',high:'高质量','1024x1024':'1:1 · 1024×1024','1536x1024':'3:2 · 1536×1024','1024x1536':'2:3 · 1024×1536','1536x864':'16:9 · 1536×864','864x1536':'9:16 · 864×1536','2048x2048':'1:1 · 请求 2K','2560x1440':'16:9 · 请求 2K','1440x2560':'9:16 · 请求 2K'} as any)[v]||String(v).replace('*',' × ');
export default function MediaWorkbench(p:any){
 const {draft,cap,baseCap,assets,runs,update,changeModel,changeOptions,canGenerate,generate,busy,running,error,notice,saveState,context,outputUI,reuse,refreshRun,upload,owner}=p;
 const video=draft.tool.includes('video'),multiEdit=draft.tool==='image_edit'&&!!cap?.models?.find((m:any)=>m.id===(draft.model_id||baseCap?.binding))?.reference_limits?.image,refAllowed=!video&&!multiEdit&&[...(cap?.required||[]),...(cap?.optional||[])].includes('image_id'),refAsset=assets.find((a:any)=>a.id===draft.inputs.image_id);
 const selectedModel=cap?.models?.find((m:any)=>m.id===(draft.model_id||baseCap?.binding));
 const [modal,setModal]=useState(''),[direction,setDirection]=useState(''),[optimizing,setOptimizing]=useState(false),[optError,setOptError]=useState(''),[candidate,setCandidate]=useState(''),[previous,setPrevious]=useState(''),[visible,setVisible]=useState(12);
 const [panelWidth,setPanelWidth]=useState(()=>Number(localStorage.getItem('tijian-media-panel-width'))||(video?430:330));
 const panelResize=useRef<{x:number;width:number}|null>(null);
 const [rule,setRule]=useState(()=>{try{return localStorage.getItem('studio-opt-rule:'+owner+':'+(video?'video':'image'))||'保留原意与参考图约束，避免空泛形容，不添加未经确认的事实。'}catch{return ''}});
 const promptRef=useRef(draft.inputs.prompt||'');promptRef.current=draft.inputs.prompt||'';const file=useRef<HTMLInputElement>(null),shelf=useRef<HTMLDivElement>(null),guard=useRef(false);
 const pictures=assets.filter((a:any)=>a.asset_type==='image'&&a.status==='ready');
 const optimize=async(requirement='')=>{if(guard.current)return;guard.current=true;setOptimizing(true);setOptError('');const original=promptRef.current;try{const reference_counts={image:draft.inputs.image_ids?.length||(draft.inputs.image_id?1:0),video:draft.inputs.video_ids?.length||0,audio:draft.inputs.audio_ids?.length||0};let j=await api('/studio/prompt/optimize',{prompt:original,type:video?'video':'image',requirement,rule,has_reference:Object.values(reference_counts).some(Boolean),reference_counts});while(['queued','running'].includes(j.status)){await new Promise(r=>setTimeout(r,800));j=await api('/jobs/'+j.id)}if(j.status!=='done')throw Error(j.error||'优化失败');if(promptRef.current===original){setPrevious(original);update({prompt:j.result.optimized_prompt});setModal('')}else{setCandidate(j.result.optimized_prompt);setOptError('你在优化期间修改了输入，原文已保留。可查看并采用优化版本。')}}catch(e:any){setOptError(e.message)}finally{setOptimizing(false);guard.current=false}};
 const useReference=(a:any)=>{update({image_id:a.id});setModal('')};
 const takeFile=(f:File)=>{if(!/^image\/(png|jpeg|webp)$/.test(f.type)){setOptError('参考图仅支持 PNG、JPEG 或 WebP 图片');return}void upload(f,'image_id')};
 const drop=(e:React.DragEvent)=>{e.preventDefault();if(busy||running||!refAllowed)return;const id=e.dataTransfer.getData('application/x-tijian-asset');if(id){const a=pictures.find((a:any)=>a.id===id);if(a)useReference(a)}else if(e.dataTransfer.files[0]){if(e.dataTransfer.files.length>1)setOptError('当前接口一次只支持一张参考图，本次采用第一张。');takeFile(e.dataTransfer.files[0])}};
 const promptField=(expanded=false)=><textarea className={expanded?'mw-prompt-expanded':''} aria-label={expanded?'展开编辑提示词':'输入你的要求'} value={draft.inputs.prompt||''} onChange={e=>update({prompt:e.target.value})} onKeyDown={e=>sendKey(e,()=>{if(expanded)setModal('');else if(canGenerate&&!optimizing)generate()},v=>update({prompt:v}))} placeholder={video?'描述主体、动作、镜头运动与节奏…':'描述你想要的画面，或说明要怎样修改参考图…'}/>;
 return <div className="studio-v2 media-workbench" style={{'--mw-panel-width':panelWidth+'px'} as React.CSSProperties}><aside className="mw-panel"><header className="mw-heading"><span>TIJIAN / CREATE</span><h1>{video?'视频创作':'图片创作'}</h1><nav>{(video?[['text_video','文生视频'],['image_video','图生视频']]:[['text_image','图片生成'],['image_edit','图片编辑']]).map(([tool,title])=><a key={tool} aria-current={tool===draft.tool?'page':undefined} href={'#studio/'+(video?'video':'image')+'?mode='+tool}>{title}</a>)}</nav></header><div className="mw-panel-scroll"><label className="mw-model">模型<select aria-label="生成模型" value={draft.model_id||baseCap?.binding||''} onChange={e=>changeModel(e.target.value)}><option value="">后台默认模型</option>{cap?.models?.map((m:any)=><option key={m.id} value={m.id}>{m.title}{m.configured?'':' · 未配置'}</option>)}</select></label>
 {video&&p.scenario}
 {(video||multiEdit)&&<MediaReferences draft={draft} model={selectedModel} assets={assets} update={update} reload={p.reloadAssets} busy={busy||running}/>}
 {refAllowed&&<section className={'mw-reference'+(refAsset?' has-image':'')} onDragOver={e=>e.preventDefault()} onDrop={drop}><input ref={file} type="file" hidden accept="image/png,image/jpeg,image/webp" disabled={busy||running} onChange={e=>{if(e.target.files?.[0])takeFile(e.target.files[0]);e.target.value=''}}/>{refAsset?<><div className="mw-reference-image"><AssetThumbnail asset={refAsset}/></div><div className="mw-reference-caption"><span>{refAsset.title}</span><button disabled={busy||running} onClick={()=>update({image_id:''})}>移除</button></div></>:<><ImageIcon size={24}/><strong>{draft.tool==='text_image'?'添加参考图（可选）':'添加参考图'}</strong><small>拖入本地图片，或从右侧素材库拖入</small></>}<div className="mw-reference-actions"><button disabled={busy||running} onClick={()=>file.current?.click()}><Plus size={14}/>上传图片</button><button disabled={busy||running} onClick={()=>setModal('assets')}>素材库选择</button></div></section>}
 <section className="mw-prompt"><div className="mw-label"><strong>输入你的要求</strong><div><button onClick={()=>setModal('rules')}>优化规则</button><button onClick={()=>setModal('prompt')}><Expand size={13}/>放大编辑</button></div></div>{promptField()}<div className="mw-prompt-actions"><button disabled={optimizing||!draft.inputs.prompt?.trim()} onClick={()=>void optimize()}>{optimizing?<LoaderCircle className="st-spin" size={14}/>:<Sparkles size={14}/>}一键优化</button><button disabled={optimizing||!draft.inputs.prompt?.trim()} onClick={()=>setModal('direction')}>带要求优化</button>{previous&&<button disabled={optimizing} onClick={()=>{update({prompt:previous});setPrevious('')}}>撤销优化</button>}</div>{optError&&<p className="mw-error" role="alert">{optError}</p>}{candidate&&<button onClick={()=>setModal('candidate')}>查看优化版本</button>}<small className="mw-shortcut">Enter 继续 · Ctrl+Enter 换行</small></section>
 <details className="mw-context"><summary>我的 IP <ChevronRight size={14}/></summary>{context}</details></div>
 <footer className="mw-controls"><button className="mw-parameter-button" onClick={()=>setModal('parameters')}><SlidersHorizontal size={18}/><span><strong>生成参数</strong><small>{Object.entries(draft.options||{}).length?Object.entries(draft.options).map(([k,v])=>(labels[k]||k)+' '+optionLabel(v)).join(' · '):'服务默认 · 1 个结果'}</small></span><ChevronRight size={17}/></button>{error&&<p className="mw-error" role="alert">{error}</p>}{notice&&!notice.startsWith('任务已提交')&&<p className="mw-local-status">{notice}</p>}{!p.configured&&<p className="mw-error">{baseCap?.binding===''?'此功能已被管理员停用，请联系管理员。':video?'请管理员配置 WaveSpeed API Key 并绑定已上架的 Seedance 模型；草稿会继续保存。':'当前模型尚未配置可用服务，请更换模型或联系管理员。'}</p>}<button className="mw-generate" disabled={!canGenerate||optimizing} onClick={generate}>{running?<LoaderCircle className="st-spin" size={18}/>:video?<Film size={18}/>:<Sparkles size={18}/>} {running?'正在生成…':'立即生成'}</button><div className="mw-footer-meta"><span>{saveState}</span><span>按服务实际用量计费</span></div></footer></aside>
 <div className="mw-pane-resizer" role="separator" aria-label="拖动调整视频编辑栏宽度；双击还原" aria-orientation="vertical" tabIndex={0} onPointerDown={e=>{e.preventDefault();panelResize.current={x:e.clientX,width:panelWidth};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!panelResize.current)return;const width=Math.max(280,Math.min(540,panelResize.current.width+e.clientX-panelResize.current.x));const snapped=Math.abs(width-(video?430:330))<12?(video?430:330):width;setPanelWidth(snapped);localStorage.setItem('tijian-media-panel-width',String(snapped))}} onPointerUp={()=>{panelResize.current=null}} onDoubleClick={()=>{setPanelWidth(video?430:330);localStorage.setItem('tijian-media-panel-width',String(video?430:330))}} onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){const width=Math.max(280,Math.min(540,panelWidth+(e.key==='ArrowLeft'?-20:20)));setPanelWidth(width);localStorage.setItem('tijian-media-panel-width',String(width))}}}/> <main className="mw-results">{video&&<section className="mw-stage"><div className="mw-stage-inner"><div className="mw-stage-icon"><Film size={28}/></div><span>视频工作区</span><h2>从想法到镜头，都在这一页完成</h2><p>左侧选择用途、模型和参考素材；生成服务接通后，作品将在下方显示。</p></div></section>}<section className="mw-shelf"><header><div><strong>素材库</strong><small>{refAllowed?'点击放大查看 · 拖到左侧作为参考图':'从左侧参考素材中选取'}</small></div><div><span>{pictures.length} 张图片</span><button aria-label="向左浏览素材" onClick={()=>shelf.current?.scrollBy({left:-400,behavior:'smooth'})}>‹</button><button aria-label="向右浏览素材" onClick={()=>shelf.current?.scrollBy({left:400,behavior:'smooth'})}>›</button></div></header><div className="mw-shelf-items" ref={shelf}>{pictures.slice(0,60).map((a:any)=><article draggable={refAllowed} onDragStart={e=>{e.dataTransfer.setData('application/x-tijian-asset',a.id);e.dataTransfer.effectAllowed='copy'}} key={a.id}><div><AssetThumbnail asset={a}/></div><span title={a.title}>{a.title||'图片素材'}</span>{refAllowed&&<button disabled={busy||running} onClick={()=>useReference(a)}>设为参考图</button>}</article>)}{!pictures.length&&<div className="mw-shelf-empty">上传或生成的图片会保留在这里，方便下次继续创作。</div>}</div></section>
 <header className="mw-results-heading"><div><h2>{video?'视频作品':'图片作品'}</h2><span>{runs.length} 次生成</span></div><a href="#studio/works">全部作品 ↗</a></header>
 <div className="mw-history">{runs.slice(0,visible).map((r:any)=><article className="mw-result-card" key={r.id}><header><div><strong>{r.generation?.input?.prompt||r.title||'创作任务'}</strong><small>{r.generation?.model_title||r.model_id||''} · {new Date(r.created||r.updated).toLocaleString()}</small></div><span className={'st-status '+(['failed','unknown','interrupted'].includes(r.status)?'failed':'')}>{({succeeded:'已生成',queued:'排队中',preparing:'准备中',submitting:'提交中',running:'生成中',failed:'生成失败',unknown:'等待核查',archive_failed:'待保存',interrupted:'已中断'} as any)[r.status]||r.status}</span></header>{p.outputs(r).length?p.outputs(r).map((a:any)=>outputUI(a,r.generation||{})):<div className="mw-pending">{['queued','preparing','submitting','running'].includes(r.status)?<><LoaderCircle className="st-spin" size={28}/><strong>正在创作这件作品</strong><span>离开页面后仍可回来查看，无需重新提交。</span></>:<><ImageIcon size={28}/><strong>暂未取得结果文件</strong></>}{r.error&&<p className="mw-error">{r.error}</p>}</div>}<footer><button disabled={busy||running||!r.generation} onClick={()=>reuse(r)}>复用提示词与参数</button>{!['succeeded','failed'].includes(r.status)&&<button onClick={()=>refreshRun(r)}>核查原任务</button>}</footer></article>)}{runs.length>visible&&<button className="mw-more" onClick={()=>setVisible(v=>v+12)}><ArrowDown size={15}/>加载更多历史</button>}{!runs.length&&<div className="mw-empty"><div>{video?<Film size={34}/>:<ImageIcon size={34}/>}</div><h2>{video?'让想法成为动态画面':'第一幅作品，从这里开始'}</h2><p>在左侧写下要求，选择参考图与参数。<br/>生成的作品会按时间保留在这里。</p></div>}</div></main>
 {modal==='assets'&&<AssetPicker items={pictures} busy={busy} onSelect={useReference} onClose={()=>setModal('')}/>}
 {modal&&modal!=='assets'&&<StudioModal title={({parameters:'生成参数',prompt:'编辑画面要求',direction:'你希望怎样优化？',rules:'提示词优化规则',candidate:'优化版本'} as any)[modal]} onClose={()=>setModal('')}>{modal==='parameters'?<div className="mw-parameters">{Object.entries(cap?.options||{}).map(([k,vs]:any)=><fieldset key={k}><legend>{labels[k]||k}</legend><div><button aria-pressed={draft.options?.[k]===undefined} onClick={()=>changeOptions(k,undefined)}>默认</button>{vs.map((v:any)=><button key={String(v)} aria-pressed={draft.options?.[k]===v} onClick={()=>changeOptions(k,v)}>{optionLabel(v)}</button>)}</div></fieldset>)}<p>图片尺寸包含比例。仅提供所选模型支持的参数；结果会展示服务实际返回的尺寸。</p><button className="st-primary" onClick={()=>setModal('')}>完成设置</button></div>:modal==='prompt'?<div className="mw-modal-body">{promptField(true)}<button className="st-primary" onClick={()=>setModal('')}>完成编辑</button></div>:modal==='direction'?<div className="mw-modal-body"><p>例如：保留产品外观，改成更简洁的商业摄影风格。</p><textarea autoFocus aria-label="优化方向" maxLength={2000} value={direction} onChange={e=>setDirection(e.target.value)} onKeyDown={e=>sendKey(e,()=>{if(direction.trim()&&!optimizing)void optimize(direction)},setDirection)}/><button className="st-primary" disabled={optimizing||!direction.trim()} onClick={()=>void optimize(direction)}>{optimizing?'正在优化…':'按这个方向优化'}</button>{optError&&<p role="alert">{optError}</p>}</div>:modal==='rules'?<div className="mw-modal-body"><p>系统负责保留原意、遵守参考图约束。这里设置你本人的补充偏好，仅用于{video?'视频':'图片'}提示词优化，不会修改后台系统提示词。</p><textarea data-enter="newline" aria-label="优化补充规则" maxLength={3000} value={rule} onChange={e=>setRule(e.target.value)}/><button className="st-primary" onClick={()=>{try{localStorage.setItem('studio-opt-rule:'+owner+':'+(video?'video':'image'),rule);setModal('')}catch{setOptError('规则保存失败，请检查本机存储空间')}}}>保存规则</button></div>:<div className="mw-modal-body"><textarea data-enter="newline" value={candidate} onChange={e=>setCandidate(e.target.value)}/><button className="st-primary" onClick={()=>{setPrevious(draft.inputs.prompt||'');update({prompt:candidate});setCandidate('');setModal('')}}>采用优化版本</button></div>}</StudioModal>}
 </div>
}
