import {useEffect,useState} from 'react';
import {api} from './api';
import './media-registry-admin.css';

const toolLabels:Record<string,string>={text_video:'文生视频',image_video:'图生视频',text_image:'图片生成',image_edit:'图片编辑',text_avatar:'文字口播',audio_avatar:'音频口播',avatar_create:'形象克隆'};
const allowed=(family:string)=>family.startsWith('seedance')?['text_video','image_video']:family==='gpt-image-2.5-text'?['text_image']:family==='gpt-image-2.5-edit'?['image_edit']:family==='infinitetalk'?['audio_avatar']:family==='heygen-avatar-v-create'?['avatar_create']:['text_avatar','audio_avatar'];
type Provider={id:string;title:string;category:string;base_url:string;docs_url?:string;published:boolean;has_key:boolean;adapter_ready:boolean};
type Model={id:string;provider_id:string;title:string;family:string;tools:string[];published:boolean;category:string;adapter_ready:boolean;api_model_id?:string};
export default function MediaRegistryAdmin(){
 const [data,setData]=useState<{providers:Provider[];models:Model[];notice:string}|null>(null),[selected,setSelected]=useState(''),[search,setSearch]=useState(''),[category,setCategory]=useState('all'),[status,setStatus]=useState('all');
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[providerDraft,setProviderDraft]=useState<any>(null),[modelDraft,setModelDraft]=useState<Model|null>(null);
 const load=async()=>setData(await api('/admin/media-registry'));
 useEffect(()=>{void load().catch(e=>setError(e.message))},[]);
 const provider=data?.providers.find(p=>p.id===selected)||data?.providers[0];
 const models=(data?.models||[]).filter(m=>m.provider_id===provider?.id&&(!search||[m.title,m.api_model_id].join(' ').toLowerCase().includes(search.toLowerCase()))&&(category==='all'||m.category===category)&&(status==='all'||m.published===(status==='on')));
 const act=async(fn:()=>Promise<any>,message:string)=>{setBusy(true);setError('');setNotice('');try{const result=await fn();await load();setNotice(message);return result}catch(e:any){setError(e.message);return null}finally{setBusy(false)}};
 const saveProvider=async(p:any)=>{if(await act(()=>api('/admin/media-registry/providers',p),'平台已保存')){setSelected(p.id);setProviderDraft(null)}};
 const saveModel=async(m:any)=>{if(await act(()=>api('/admin/media-registry/models',m),'模型与功能已保存'))setModelDraft(null)};
 return <section className="mr-admin"><p className="mr-callout">{data?.notice||'正在读取平台目录…'} 可跳过模型生成测试直接上架，但“连接成功”只表示密钥与目录接口可用。</p>{error&&<p role="alert" className="form-error">{error}</p>}{notice&&<p role="status" className="admin-notice">{notice}</p>}
 <div className="provider-browser"><nav className="provider-directory" aria-label="媒体服务平台"><div className="section-heading"><h3>服务平台</h3><button disabled={busy} onClick={()=>setProviderDraft({id:'',title:'',category:'视频、图片与数字人',base_url:'',published:false})}>新增</button></div>{data?.providers.map(p=><button key={p.id} className={p.id===provider?.id?'active':''} onClick={()=>{setSelected(p.id);setSearch('')}}><strong>{p.title}</strong><small>{data.models.filter(m=>m.provider_id===p.id).length} 个模型 · {p.published?'已上架':'已下架'} · {p.has_key?'有密钥':'未配置'}</small></button>)}</nav>
 {provider&&<section className="surface provider-section"><div className="section-heading"><div><h2>{provider.title}</h2><p className="muted">{provider.category} · {provider.base_url}</p>{provider.docs_url&&<a href={provider.docs_url} target="_blank" rel="noreferrer">查看接口文档 ↗</a>}</div><span className={'mr-badge '+(provider.published?'on':'')}>{provider.published?'平台已上架':'平台已下架'}</span></div><div className="button-row"><button disabled={busy} onClick={()=>setProviderDraft(provider)}>{provider.has_key?'编辑连接':'配置连接'}</button><button disabled={busy} onClick={()=>void act(()=>api('/admin/media-registry/providers',{id:provider.id,published:!provider.published}),provider.published?'平台已下架，所属模型停止新任务':'平台已上架')}>{provider.published?'下架平台':'上架平台'}</button><button className="primary" disabled={busy||!provider.has_key} onClick={()=>void act(()=>api('/admin/media-registry/providers/'+provider.id+'/discover',{}),'连接成功，已获取该平台支持的模型；新模型默认下架')}>测试连接并获取模型</button></div>
 <div className="model-filters"><input aria-label="搜索当前平台模型" placeholder="搜索当前平台模型名称" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="按能力分类" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">全部能力</option><option>AI 视频</option><option>AI 生图</option><option>数字人口播</option><option>形象克隆</option></select><select aria-label="按上架状态" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">全部状态</option><option value="on">已上架</option><option value="off">已下架</option></select></div>
 <div className="mr-list">{models.map(m=><article key={m.id}><div><strong>{m.title}</strong><small>{m.category} · {m.api_model_id||m.family}</small><small>前台：{m.tools.map(t=>toolLabels[t]||t).join('、')} · {m.adapter_ready?(provider.has_key?'接口已适配':'待配置密钥'):'接口待接入'}</small></div><span className={'mr-badge '+(provider.published&&m.published?'on':'')}>{!provider.published?'随平台停用':m.published?'已上架':'已下架'}</span><button disabled={busy||!provider.published} onClick={()=>setModelDraft(m)}>功能</button><button disabled={busy||!provider.published} onClick={()=>void act(()=>api('/admin/media-registry/models',{id:m.id,published:!m.published}),m.published?'模型已下架':'模型已上架')}>{m.published?'下架':'上架'}</button></article>)}{!models.length&&<p className="muted">当前平台没有匹配模型。配置密钥后可点击“测试连接并获取模型”。</p>}</div></section>}</div>
 {providerDraft&&<div className="modal-backdrop"><section className="modal mr-modal" role="dialog" aria-modal="true" aria-label="配置媒体服务"><h2>配置服务平台</h2>{error&&<p role="alert" className="form-error">{error}</p>}<form onSubmit={e=>{e.preventDefault();const raw=Object.fromEntries(new FormData(e.currentTarget));void saveProvider({id:raw.id,title:raw.title,category:raw.category,base_url:raw.base_url,docs_url:raw.docs_url,api_key:raw.api_key||undefined,published:raw.published==='on'})}}><label className="field">平台编号<input name="id" pattern="[a-z][a-z0-9-]{1,63}" required readOnly={!!providerDraft.title} defaultValue={providerDraft.id}/></label><label className="field">平台名称<input name="title" required defaultValue={providerDraft.title}/></label><label className="field">分类<select name="category" defaultValue={providerDraft.category}><option>视频、图片与数字人</option><option>视频与图片</option><option>AI 视频</option><option>AI 生图</option><option>数字人</option></select></label><label className="field">Base URL<input name="base_url" type="url" required defaultValue={providerDraft.base_url}/></label><label className="field">接口文档网址<input name="docs_url" type="url" defaultValue={providerDraft.docs_url||''}/></label><label className="field">API Key（留空保留原值）<input name="api_key" type="password" autoComplete="new-password"/></label><label className="switch-row"><input name="published" type="checkbox" defaultChecked={providerDraft.published}/>上架平台</label><p>密钥仅在服务端加密保存。连接测试不会发起付费生成。</p><div className="button-row"><button type="button" onClick={()=>setProviderDraft(null)}>取消</button><button className="primary" disabled={busy}>保存平台</button></div></form></section></div>}
 {modelDraft&&<div className="modal-backdrop"><section className="modal mr-modal" role="dialog" aria-modal="true" aria-label="绑定前台功能"><h2>{modelDraft.title}</h2><p>选择这个模型在前台出现的位置。</p>{error&&<p role="alert" className="form-error">{error}</p>}<fieldset><legend>前台可用功能</legend>{allowed(modelDraft.family).map(t=><label key={t} className="switch-row"><input type="checkbox" checked={modelDraft.tools.includes(t)} onChange={e=>setModelDraft({...modelDraft,tools:e.target.checked?[...modelDraft.tools,t]:modelDraft.tools.filter(x=>x!==t)})}/>{toolLabels[t]}</label>)}</fieldset><div className="button-row"><button onClick={()=>setModelDraft(null)}>关闭</button><button className="primary" disabled={busy||!modelDraft.tools.length} onClick={()=>void saveModel({id:modelDraft.id,title:modelDraft.title,provider_id:modelDraft.provider_id,family:modelDraft.family,tools:modelDraft.tools,published:modelDraft.published})}>保存绑定</button></div></section></div>}
 </section>;
}
