import {useEffect,useState} from 'react';
import {api} from './api';
import './media-registry-admin.css';

const families=[['seedance-2.0','AI 视频 · Seedance 2.0'],['seedance-2.5','AI 视频 · Seedance 2.5'],['infinitetalk','数字人口播 · InfiniteTalk'],['heygen-avatar-v','数字人口播 · HeyGen Avatar V'],['heygen-avatar-v-create','形象克隆 · HeyGen Avatar V']];
const toolLabels:Record<string,string>={text_video:'文生视频',image_video:'图生视频',text_avatar:'文字口播',audio_avatar:'音频口播',avatar_create:'形象克隆'};
const allowed=(family:string)=>family.startsWith('seedance')?['text_video','image_video']:family==='infinitetalk'?['audio_avatar']:family==='heygen-avatar-v-create'?['avatar_create']:['text_avatar','audio_avatar'];
type Provider={id:string;title:string;category:string;base_url:string;docs_url?:string;published:boolean;has_key:boolean;adapter_ready:boolean};
type Model={id:string;provider_id:string;title:string;family:string;tools:string[];published:boolean;category:string;adapter_ready:boolean};
export default function MediaRegistryAdmin(){
 const [data,setData]=useState<{providers:Provider[];models:Model[];notice:string}|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [providerDraft,setProviderDraft]=useState<any>(null),[modelDraft,setModelDraft]=useState<any>(null);
 const load=async()=>setData(await api('/admin/media-registry'));
 useEffect(()=>{void load().catch(e=>setError(e.message))},[]);
 const act=async(fn:()=>Promise<any>,message:string)=>{setBusy(true);setError('');setNotice('');try{await fn();await load();setNotice(message);return true}catch(e:any){setError(e.message);return false}finally{setBusy(false)}};
 const saveProvider=async(p:any)=>{if(await act(()=>api('/admin/media-registry/providers',p),'服务已保存；新任务立即按当前上架状态检查。'))setProviderDraft(null)};
 const saveModel=async(m:any)=>{if(await act(()=>api('/admin/media-registry/models',m),'模型已保存；新任务立即按当前上架状态检查。'))setModelDraft(null)};
 return <section className="surface mr-admin"><div className="section-heading"><div><h2>中转平台与模型</h2><p>管理员管理平台、模型分类及前台功能。下架后新任务不可使用；已提交的任务仍保留记录。</p></div></div><p className="mr-callout">{data?.notice||'目录加载中…'}平台候选来自公开接口资料；当前未完成本账号联调，不展示价格或生成成功承诺。</p>{error&&<p role="alert" className="form-error">{error}</p>}{notice&&<p role="status" className="admin-notice">{notice}</p>}
 <div className="section-heading"><h3>服务平台</h3><button disabled={busy} onClick={()=>setProviderDraft({id:'',title:'',category:'视频与数字人',base_url:'',published:false})}>新增平台</button></div><div className="mr-list">{data?.providers.map(p=><article key={p.id}><div><strong>{p.title}</strong><small>{p.category} · {p.id}</small><small>{p.has_key?'已保存 API Key':'未配置 API Key'} · {p.adapter_ready?'接口已接入':'接口待接入'}</small>{p.docs_url&&<a href={p.docs_url} target="_blank" rel="noopener noreferrer">查看接口文档 ↗</a>}</div><span className={'mr-badge '+(p.published?'on':'')}>{p.published?'已上架':'已下架'}</span><button disabled={busy} onClick={()=>setProviderDraft(p)}>配置</button><button disabled={busy} onClick={()=>void act(()=>api('/admin/media-registry/providers',{id:p.id,published:!p.published}),'平台状态已更新')}>{p.published?'下架':'上架'}</button><button disabled={busy} onClick={()=>void act(()=>api('/admin/media-registry/providers',{id:p.id,archived:true,published:false}),'平台已从目录移除')}>移除</button></article>)}</div>
 <div className="section-heading"><h3>模型与功能</h3><button disabled={busy} onClick={()=>setModelDraft({id:'',title:'',provider_id:data?.providers[0]?.id||'',family:'seedance-2.0',tools:['text_video','image_video'],published:false})}>新增模型</button></div><div className="mr-list">{data?.models.map(m=><article key={m.id}><div><strong>{m.title}</strong><small>{m.category} · {data?.providers.find(p=>p.id===m.provider_id)?.title||m.provider_id}</small><small>用于：{m.tools.map(t=>toolLabels[t]||t).join('、')} · 接口待接入</small></div><span className={'mr-badge '+(m.published?'on':'')}>{m.published?'已上架':'已下架'}</span><button disabled={busy} onClick={()=>setModelDraft(m)}>编辑</button><button disabled={busy} onClick={()=>void act(()=>api('/admin/media-registry/models',{id:m.id,published:!m.published}),'模型状态已更新')}>{m.published?'下架':'上架'}</button><button disabled={busy} onClick={()=>void act(()=>api('/admin/media-registry/models',{id:m.id,archived:true,published:false}),'模型已从目录移除')}>移除</button></article>)}</div>
 {providerDraft&&<div className="modal-backdrop"><section className="modal mr-modal" role="dialog" aria-modal="true" aria-label="配置媒体服务"><h2>配置媒体服务</h2>{error&&<p role="alert" className="form-error">{error}</p>}<form onSubmit={e=>{e.preventDefault();const raw=Object.fromEntries(new FormData(e.currentTarget));void saveProvider({id:raw.id,title:raw.title,category:raw.category,base_url:raw.base_url,docs_url:raw.docs_url,api_key:raw.api_key||undefined,published:raw.published==='on'})}}><label className="field">平台编号<input name="id" pattern="[a-z][a-z0-9-]{1,63}" required readOnly={!!providerDraft.title} defaultValue={providerDraft.id}/></label><label className="field">平台名称<input name="title" required defaultValue={providerDraft.title}/></label><label className="field">分类<select name="category" defaultValue={providerDraft.category}><option>视频与数字人</option><option>AI 视频</option><option>数字人</option></select></label><label className="field">Base URL<input name="base_url" type="url" required defaultValue={providerDraft.base_url}/></label><label className="field">接口文档网址<input name="docs_url" type="url" defaultValue={providerDraft.docs_url||''}/></label><label className="field">API Key（留空保留原值）<input name="api_key" type="password" autoComplete="new-password"/></label><label className="switch-row"><input name="published" type="checkbox" defaultChecked={providerDraft.published}/>上架平台</label><p>密钥仅在服务端加密保存；当前接口待接入，保存后仍不能发起生成。</p><div className="button-row"><button type="button" onClick={()=>setProviderDraft(null)}>取消</button><button className="primary" disabled={busy}>保存平台</button></div></form></section></div>}
 {modelDraft&&<div className="modal-backdrop"><section className="modal mr-modal" role="dialog" aria-modal="true" aria-label="编辑媒体模型"><h2>编辑模型与前台功能</h2>{error&&<p role="alert" className="form-error">{error}</p>}<form onSubmit={e=>{e.preventDefault();const raw=Object.fromEntries(new FormData(e.currentTarget));void saveModel({id:raw.id,title:raw.title,provider_id:raw.provider_id,family:raw.family,tools:modelDraft.tools,published:raw.published==='on'})}}><label className="field">模型编号<input name="id" pattern="[a-z][a-z0-9-]{1,63}" required readOnly={!!modelDraft.category} defaultValue={modelDraft.id}/></label><label className="field">前台名称<input name="title" required defaultValue={modelDraft.title}/></label><label className="field">服务平台<select name="provider_id" value={modelDraft.provider_id} onChange={e=>setModelDraft({...modelDraft,provider_id:e.target.value})}>{data?.providers.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label className="field">模型类别<select name="family" value={modelDraft.family} onChange={e=>setModelDraft({...modelDraft,family:e.target.value,tools:allowed(e.target.value)})}>{families.map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></label><fieldset><legend>前台可用功能</legend>{allowed(modelDraft.family).map(t=><label className="switch-row" key={t}><input type="checkbox" checked={modelDraft.tools.includes(t)} onChange={e=>setModelDraft({...modelDraft,tools:e.target.checked?[...modelDraft.tools,t]:modelDraft.tools.filter((x:string)=>x!==t)})}/>{toolLabels[t]}</label>)}</fieldset><label className="switch-row"><input name="published" type="checkbox" defaultChecked={modelDraft.published}/>上架模型</label><p>只有平台和模型都上架时，前台才列出此模型。生成需等待接口适配及实际联调。</p><div className="button-row"><button type="button" onClick={()=>setModelDraft(null)}>取消</button><button className="primary" disabled={busy}>保存模型</button></div></form></section></div>}
 </section>;
}
