import {useEffect,useRef,useState} from 'react';
import {api,Item} from './api';
import {JobFeedback,activeJob} from './OperationFeedback';
import './outcomes.css';
export default function ModelServices({t,data,load,providerForm}:any){
 const [selected,setSelected]=useState(()=>sessionStorage.getItem('model-provider')||''),[filter,setFilter]=useState(''),[busy,setBusy]=useState(''),[notice,setNotice]=useState<Record<string,string>>({});
 const p=data.providers.find((x:any)=>x.id===selected)||data.providers[0];
 const completed=useRef(new Set<string>()),jobs=t.list('job').filter((j:Item)=>j.input?.action==='probe');
 useEffect(()=>{const ended=jobs.filter((j:Item)=>!activeJob(j)&&!completed.current.has(j.id));if(ended.length){ended.forEach((j:Item)=>completed.current.add(j.id));void load()}},[jobs.map((j:Item)=>j.id+j.status).join(',')]);
 const choose=(id:string)=>{setSelected(id);sessionStorage.setItem('model-provider',id);setFilter('')};
 const add=()=>t.setForm({title:'接入模型服务',description:'每个服务独立发现、验证和上架模型。',fields:[{key:'title',label:'服务名称',required:true},{key:'base_url',label:'Base URL',type:'url',required:true},{key:'api_key',label:'API Key',type:'password',required:true},{key:'protocol',label:'文本协议',options:[{value:'chat',label:'Chat Completions'},{value:'responses',label:'Responses API'}]}],submit:'保存连接',action:async(x:any)=>{const saved=await api('/admin/providers',x);choose(saved.id);await load()}});
 const discover=async()=>{const id=p.id;setBusy(id);setNotice(v=>({...v,[id]:'正在获取模型列表…'}));try{const all=await api('/admin/providers/'+id+'/discover',{});setNotice(v=>({...v,[id]:'已更新 · '+all.filter((m:any)=>m.provider===id).length+' 个模型'}));await load()}catch(e){setNotice(v=>({...v,[id]:(e as Error).message}))}finally{setBusy('')}};
 return <div className="model-services"><div className="section-heading"><h2>服务与模型</h2><button className="primary" onClick={add}>添加连接</button></div><div className="provider-browser"><nav className="provider-directory" aria-label="模型服务平台">{data.providers.map((x:any)=><button className={p?.id===x.id?'active':''} key={x.id} onClick={()=>choose(x.id)}><strong>{x.title}</strong><small>{data.models.filter((m:any)=>m.provider===x.id).length} 个模型 · {x.has_key?'已配置':'待配置'}</small></button>)}</nav>{p&&<section className="surface provider-section" data-provider={p.title}><div className="section-heading"><div><h2>{p.title}</h2><p className="muted">{p.base_url}</p>{p.api_key_url&&<div className="button-row"><a href={p.api_key_url} target="_blank" rel="noreferrer">获取 API Key ↗</a><a href={p.docs_url} target="_blank" rel="noreferrer">使用文档 ↗</a></div>}</div><div className="button-row"><button onClick={()=>t.setForm(providerForm(p,load))}>{p.has_key?'编辑连接':'配置连接'}</button><button disabled={!p.has_key||busy===p.id} onClick={discover}>{busy===p.id?'获取中…':'发现模型'}</button></div></div>{notice[p.id]&&<p className="inline-job" role="status">{notice[p.id]}</p>}<input className="provider-search" aria-label="搜索服务模型" placeholder="搜索当前平台的模型" value={filter} onChange={e=>setFilter(e.target.value)}/><div className="provider-table"><table><thead><tr><th>模型</th><th>能力</th><th>连接状态</th><th>上架</th><th/></tr></thead><tbody>{data.models.filter((m:any)=>m.provider===p.id&&m.title.toLowerCase().includes(filter.toLowerCase())).map((m:any)=>{const job=jobs.find((j:Item)=>j.input?.model_id===m.id);return <tr key={m.id}><td>{m.title}</td><td>{m.capability==='image'?'生图':'文本'}</td><td>{job?<JobFeedback job={job}/>:m.verified?'已验证':'未测试'}</td><td><input type="checkbox" aria-label={p.title+' 上架 '+m.title} disabled={!m.verified||activeJob(job)} checked={!!m.published} onChange={e=>t.action(async()=>{await api('/admin/models/'+m.id,{published:e.target.checked},'PATCH');await load()})}/></td><td><button disabled={activeJob(job)} onClick={()=>t.action(()=>api('/admin/models/'+m.id+'/verify',{}),'已开始测试')}>{activeJob(job)?'测试中…':m.capability==='image'?'生成测试图':'测试连接'}</button></td></tr>})}</tbody></table></div>{!data.models.some((m:any)=>m.provider===p.id)&&<p className="muted">{p.has_key?'点击发现模型，获取此平台的模型列表。':'填写 API Key 后即可发现并测试模型。'}</p>}<small className="muted">测试结果显示在对应模型行内。生图测试会实际生成一张图片，费用按服务商计费。</small></section>}</div></div>
}
