import {useState} from 'react';
import {api} from './api';
import './outcomes.css';

export default function ModelServices({t,data,load,providerForm}:any){
 const [filter,setFilter]=useState('');
 const add=()=>t.setForm({title:'接入模型服务',description:'每个服务独立发现、验证和上架模型。',fields:[{key:'title',label:'服务名称',required:true},{key:'base_url',label:'Base URL',type:'url',required:true},{key:'api_key',label:'API Key',type:'password',required:true},{key:'protocol',label:'文本协议',options:[{value:'chat',label:'Chat Completions'},{value:'responses',label:'Responses API'}]}],submit:'保存连接',action:async(x:any)=>{await api('/admin/providers',x);await load()}});
 return <div className="model-services"><div className="section-heading"><h2>服务与模型</h2><div className="button-row"><input aria-label="搜索服务模型" placeholder="搜索模型" value={filter} onChange={e=>setFilter(e.target.value)}/><button className="primary" onClick={add}>添加连接</button></div></div>{data.providers.map((p:any)=>{const models=data.models.filter((m:any)=>m.provider===p.id&&m.title.toLowerCase().includes(filter.toLowerCase()));return <section className="surface provider-section" key={p.id} data-provider={p.title}><div className="section-heading"><div><h2>{p.title}</h2><p className="muted">{p.base_url} · {p.has_key?'凭据已加密保存':'尚未配置 API Key'}</p>{p.api_key_url&&<div className="button-row"><a href={p.api_key_url} target="_blank" rel="noreferrer">获取 API Key ↗</a><a href={p.docs_url} target="_blank" rel="noreferrer">使用文档 ↗</a></div>}</div><div className="button-row"><button onClick={()=>t.setForm(providerForm(p,load))}>{p.has_key?'编辑连接':'配置连接'}</button><button disabled={!p.has_key} onClick={()=>t.action(async()=>{await api('/admin/providers/'+p.id+'/discover',{});await load()},'已更新此服务的模型')}>发现模型</button></div></div>{models.length?<div className="provider-table"><table><thead><tr><th>此服务的模型</th><th>能力</th><th>验证状态</th><th>上架</th><th/></tr></thead><tbody>{models.map((m:any)=><tr key={m.id}><td>{m.title}</td><td>{m.capability==='image'?'生图':'文本'}</td><td>{m.verified?'已验证':'待测试'}</td><td><input type="checkbox" aria-label={p.title+' 上架 '+m.title} disabled={!m.verified} checked={!!m.published} onChange={e=>t.action(async()=>{await api('/admin/models/'+m.id,{published:e.target.checked},'PATCH');await load()})}/></td><td><button onClick={()=>t.action(()=>api('/admin/models/'+m.id+'/verify',{}),'已提交实测；完成后刷新此目录')}>{m.capability==='image'?'生成测试图':'测试连接'}</button></td></tr>)}</tbody></table></div>:<p className="muted">{p.has_key?'暂无符合条件的模型，请发现模型或调整搜索。':'填写 API Key 后，发现并测试模型即可上架。'}</p>}{models.some((m:any)=>m.capability==='image')&&<small className="muted">生图实测会调用此服务生成一张图片；费用按服务商计费。上架后可在文章中选择。</small>}</section>})}</div>
}
