import {useState} from 'react';
import {RefreshCw,Plus,Globe,ExternalLink,X,Search} from 'lucide-react';
import {api,type Item} from './api';
import {DeleteRecord} from './DeleteRecord';
import {SourceWizard,openReader} from './DiscoveryPanels';
import './radar.css';

const labels:Record<string,string>={ready:'可读取',no_match:'未发现匹配',needs_browser:'需网页读取',failed:'获取失败'};
export const sourceState=(f:Item)=>f.enabled===false?'已暂停':labels[f.last_result?.status]|| (f.error?'获取异常':'尚未获取');
export async function scanRadar(channel_id=''){
 const bridge=(window as any).tijianDesktop;if(!bridge)throw Error('读取动态网页请使用桌面版');
 return bridge.discoveryBrowser({action:'radar-scan',channel_id,token:sessionStorage.getItem('tijian-session')});
}
export function RadarSources(t:any){
 const [edit,setEdit]=useState<any>(null),[browser,setBrowser]=useState<any>(null),[query,setQuery]=useState('');
 const all=t.list('feed'),feeds=all.filter((f:Item)=>(f.title+' '+f.url).toLowerCase().includes(query.toLowerCase()));
 const running=t.list('job').filter((j:Item)=>j.input?.action==='radar'&&['queued','running'].includes(j.status));
 const busy=(f:Item)=>running.some((j:Item)=>!j.input.feed_ids||j.input.feed_ids.includes(f.id));
 return <div className="radar-source-manager"><div className="source-manager-tools"><span>{all.length} 个信源 · {all.filter((f:Item)=>f.enabled!==false).length} 个已启用</span><button className="primary" onClick={()=>setEdit({})}><Plus size={16}/>添加信源</button></div><div className="filter-search"><Search size={16}/><input aria-label="搜索信源" placeholder="查找名称或网址" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="source-cards">{feeds.map((f:Item)=><article className="source-card" key={f.id}><div className="source-card-icon"><Globe size={20}/></div><div className="source-card-main"><header><h3>{f.title}</h3><span className={'source-status '+(f.error?'warning':'')}>{busy(f)?'获取中…':sourceState(f)}</span></header><a href={f.url} target="_blank" rel="noreferrer" className="source-url">{f.url}</a><div className="source-facts"><span>关键词：{f.keywords||'不限'}</span><span>{f.last_attempt?'最近检查 '+new Date(f.last_attempt).toLocaleString('zh-CN'):'尚未执行获取'}</span>{f.last_result&&<span>发现 {f.last_result.found||0} · 新增 {f.last_result.added||0}</span>}</div>{(f.error||f.last_result?.note)&&<p className={'source-note '+(f.error?'warning':'')}>{f.error||f.last_result.note}</p>}<div className="source-actions"><button disabled={busy(f)||f.enabled===false} onClick={()=>t.action(()=>api('/radar/'+f.id+'/refresh',{}),'正在获取该信源资讯')}><RefreshCw size={14}/>获取资讯</button><button onClick={()=>setBrowser(f)}><ExternalLink size={14}/>网页读取</button><button onClick={()=>setEdit(f)}>编辑</button><button onClick={()=>t.action(()=>t.update(f,{enabled:f.enabled===false}))}>{f.enabled===false?'启用':'暂停'}</button><DeleteRecord item={f} t={t}/></div></div></article>)}</div>{!feeds.length&&<p className="inline-empty">{all.length?'没有匹配的信源。':'粘贴网站栏目、RSS 或博主主页，添加第一个信源。'}</p>}{edit&&<SourceWizard t={t} item={edit.id?edit:null} onClose={()=>setEdit(null)}/>} {browser&&<RadarBrowser feed={browser} t={t} onClose={()=>setBrowser(null)}/>}</div>
}
export function RadarBrowser({feed,t,onClose}:any){
 const [channel,setChannel]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<any>(null),[selected,setSelected]=useState<string[]>([]);
 const run=async(fn:()=>Promise<any>)=>{setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const read=async()=>{const r=await scanRadar(channel);const words=String(feed.keywords||'').split(/[,，\s]+/).filter(Boolean);r.items=r.items.filter((x:any)=>!words.length||words.some(w=>x.title.toLowerCase().includes(w.toLowerCase())));setResult(r);setSelected(r.items.map((x:any)=>x.url))};
 return <div className="reader-overlay"><section className="detail-drawer discovery-panel" role="dialog" aria-label="读取信源网页"><div className="block-heading"><h2>从网页获取线索</h2><button className="icon-button" aria-label="关闭网页读取" onClick={onClose}><X/></button></div><p>{feed.title}</p><p className="muted">打开网站完成必要的登录、搜索或验证，再回到这里读取已加载的链接。抖音请打开目标博主主页；核对作品后勾选保存。</p><div className="button-row"><button disabled={busy} onClick={()=>void run(async()=>{const r=await openReader(feed.url);setChannel(r.channel_id||'')})}>1. 打开网站</button><button className="primary" disabled={busy} onClick={()=>void run(read)}>2. 读取当前页面</button></div>{error&&<p className="form-error">{error}</p>}{result&&<><p>{result.note}</p><p className="path">当前页面：{result.url}</p><div className="button-row"><button onClick={()=>setSelected(result.items.map((x:any)=>x.url))}>全选</button><button onClick={()=>setSelected([])}>清空</button><span>已选 {selected.length} / {result.items.length}</span></div><div className="browser-leads">{result.items.map((x:any)=><label key={x.url}><input type="checkbox" checked={selected.includes(x.url)} onChange={e=>setSelected(e.target.checked?[...selected,x.url]:selected.filter(u=>u!==x.url))}/><span>{x.title}</span></label>)}</div>{!result.items.length&&<p className="local-warning">没有匹配的可见链接。可在网页加载更多内容，或修改信源关键词。</p>}<button className="primary" disabled={busy||!selected.length} onClick={()=>void run(async()=>{const r=await api('/radar/'+feed.id+'/browser-import',{url:result.url,items:result.items.filter((x:any)=>selected.includes(x.url))});await t.refresh();t.setToast('已新增 '+r.added+' 条线索');onClose()})}>保存所选线索</button></>}</section></div>
}
