import {useState} from 'react';
import {Search,FolderOpen,CheckCheck,BookOpen} from 'lucide-react';
import {type Item} from './api';
import {knowledgePath} from './KnowledgeFlow';
import './library.css';

export type ReferenceScope={mode:'auto'|'selected';modules:string[];folder_ids:string[];item_ids:string[];excluded_ids:string[]};
export const defaultScope:ReferenceScope={mode:'auto',modules:['source','wiki','memory'],folder_ids:[],item_ids:[],excluded_ids:[]};
export const modules=[['source','原始资料库',['source']],['wiki','Wiki 知识库',['knowledge']],['memory','个人记忆',['memory']],['conversation','历史对话',['task']],['content','作品与选题',['content','plan']],['radar','行业雷达',['news']],['benchmark','对标资料',['benchmark','wechat_article','douyin_work']],['identity','我的 IP',['profile']],['review','发布与复盘',['publication','metric','feedback']]] as const;
export function folderDescendants(folders:Item[],id:string){const result=new Set([id]);let changed=true;while(changed){changed=false;for(const f of folders)if(result.has(f.parent_id)&&!result.has(f.id)){result.add(f.id);changed=true}}return result}
export function referenceSelected(x:Item,scope:ReferenceScope,folders:Item[]){return !scope.excluded_ids.includes(x.id)&&(scope.item_ids.includes(x.id)||modules.some(([key,,kinds])=>scope.modules.includes(key)&&(kinds as readonly string[]).includes(x.kind))||scope.folder_ids.some(id=>folderDescendants(folders,id).has(x.folder_id)))}
export function ReferencePicker({t,scope,onChange,taskId,profileId,report}: {t:any;scope:ReferenceScope;onChange:(scope:ReferenceScope)=>void;taskId?:string;profileId?:string;report?:any}){
 const [module,setModule]=useState('source'),[search,setSearch]=useState(''),[folder,setFolder]=useState('');
 const folders=t.list('folder') as Item[];
 const kinds=(modules.find(x=>x[0]===module)?.[2]||[]) as readonly string[];
 const available=(t.state.objects as Item[]).filter(x=>modules.some(v=>(v[2] as readonly string[]).includes(x.kind))&&!x.archived&&!x.exclude_ai&&!x.file_missing&&x.id!==taskId&&(!x.profile_id||x.profile_id===profileId)&&!x.freshness_warning&&(!['knowledge','memory'].includes(x.kind)||['accepted','auto'].includes(x.status)));
 const folderSet=folder?folderDescendants(folders,folder):null;
 const visible=available.filter(x=>kinds.includes(x.kind)&&(!folderSet||folderSet.has(x.folder_id))&&(!search||(x.title+' '+(x.body||'')).toLowerCase().includes(search.toLowerCase())));
 const selected=available.filter(x=>referenceSelected(x,scope,folders));
 const setItems=(ids:string[],enabled:boolean)=>onChange({...scope,mode:'selected',item_ids:enabled?[...new Set([...scope.item_ids,...ids])]:scope.item_ids.filter(id=>!ids.includes(id)),excluded_ids:enabled?scope.excluded_ids.filter(id=>!ids.includes(id)):[...new Set([...scope.excluded_ids,...ids])]});
 const visibleFolders=folders.filter(x=>kinds.includes(x.library));
 return <div className="reference-picker">
  <div className="reference-heading"><div><span className="eyebrow">本次参考范围</span><h3>把需要的资料带进对话</h3></div><span className="reference-count">{selected.length} 条可检索</span></div>
  <div className="reference-modes"><button className={scope.mode==='auto'?'active':''} onClick={()=>onChange({...defaultScope})}>自动查找</button><button className={scope.mode==='selected'?'active':''} onClick={()=>{if(scope.mode==='auto')onChange({mode:'selected',modules:[],folder_ids:[],item_ids:[],excluded_ids:[]})}}>指定范围</button><button className="quiet" onClick={()=>onChange({mode:'selected',modules:modules.map(x=>x[0]),folder_ids:[],item_ids:[],excluded_ids:[]})}><CheckCheck size={14}/>全选全部模块</button><button className="quiet" onClick={()=>onChange({mode:'selected',modules:[],folder_ids:[],item_ids:[],excluded_ids:[]})}>清空范围</button></div>
  <p className="reference-help">先查 Wiki；需要细节或依据不足时，在所选范围补查原文。全选表示可检索范围，系统只带入相关片段。当前对话历史仍会保留。</p>
  <div className="reference-modules">{modules.map(([key,label])=><div key={key} className={module===key?'current':''}><input type="checkbox" aria-label={'启用'+label} checked={scope.modules.includes(key)} onChange={e=>{const ids=available.filter(x=>(modules.find(m=>m[0]===key)![2] as readonly string[]).includes(x.kind)).map(x=>x.id);onChange({...scope,mode:'selected',modules:e.target.checked?[...scope.modules,key]:scope.modules.filter(x=>x!==key),item_ids:e.target.checked?scope.item_ids:scope.item_ids.filter(x=>!ids.includes(x)),excluded_ids:scope.excluded_ids.filter(x=>!ids.includes(x)),folder_ids:e.target.checked?scope.folder_ids:scope.folder_ids.filter(id=>!folders.some(f=>f.id===id&&(modules.find(m=>m[0]===key)![2] as readonly string[]).includes(f.library)))})}}/><button onClick={()=>{setModule(key);setFolder('');setSearch('')}}>{label}</button></div>)}</div>
  <div className="reference-filter"><Search size={16}/><input aria-label="搜索参考内容" placeholder="搜索标题或正文" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="参考文件夹" value={folder} onChange={e=>setFolder(e.target.value)}><option value="">全部文件夹</option>{visibleFolders.map(f=><option value={f.id} key={f.id}>{f.title}</option>)}</select></div>
  <div className="reference-actions"><button onClick={()=>setItems(visible.map(x=>x.id),true)}>全选当前结果</button><button onClick={()=>setItems(visible.map(x=>x.id),false)}>取消当前结果</button>{folder&&<button onClick={()=>onChange({...scope,mode:'selected',folder_ids:[...new Set([...scope.folder_ids,folder])],excluded_ids:scope.excluded_ids.filter(id=>!available.some(x=>x.id===id&&folderSet?.has(x.folder_id)))})}><FolderOpen size={14}/>使用整个文件夹（含新增）</button>}</div>
  <div className="reference-list">{visible.map(x=><label className="source-check" key={x.id}><input type="checkbox" checked={referenceSelected(x,scope,folders)} onChange={e=>setItems([x.id],e.target.checked)}/><span><strong>{x.title}</strong><small>{folders.find(f=>f.id===x.folder_id)?.title||'未分类'} · {x.source_type||modules.find(m=>(m[2] as readonly string[]).includes(x.kind))?.[1]}</small></span></label>)}{!visible.length&&<p className="knowledge-empty">当前范围暂无可用内容。停用、来源失效或属于其他身份的内容不会带入。</p>}</div>
  <details className="reference-report" open={!!report}><summary><BookOpen size={15}/>上次回答实际参考 {report?.selected_count||0} 条</summary>{report?<><p>{report.method} · {report.original_fallback?'按需补查原文':'优先使用 Wiki'} · {report.characters} 字符</p>{report.omitted_selected?.length>0&&<p>所选条目中有 {report.omitted_selected.length} 条本次未带入，可能暂无正文或超出上下文容量。可缩小范围继续提问。</p>}{report.excerpts?.map((r:any,i:number)=><details key={i}><summary>{r.title} · 字符 {r.start+1}–{r.end}</summary><p>{r.text}</p>{t.get(r.id)&&<a href={knowledgePath(t.get(r.id))}>查看来源 →</a>}</details>)}</>:<p>发送问题后，显示实际使用的内容和原文位置。</p>}</details>
 </div>
}
