import MediaWorkbench from './MediaWorkbench';
import {useEffect, useRef, useState} from 'react';
import {ArrowRight, ArrowUpRight, AudioLines, BookOpen, Check, ChevronDown, Download, FileText, Film, FolderOpen, Image, Layers3, LoaderCircle, Mic, Plus, RefreshCw, Settings2, ShieldCheck, Sparkles, Upload, UserRound, WandSparkles, X} from 'lucide-react';
import {api, getToken} from './api';
import {DesktopUpdates} from './DesktopUpdates';
import StudioHome from './StudioHome';
import KnowledgeAssistant from './KnowledgeAssistant';
import TopicDelivery from './TopicDelivery';
import './studio.css';
import ArchiveInterview from './ArchiveInterview';
import CreationFlow from './CreationFlow';
import VideoScenarios from './VideoScenarios';
import PersonalIP from './PersonalIP';
import {MemorySettings} from './MemorySettings';
import './studio-pane-resize.css';
import ArticleEditor from './ArticleEditor';
import {sendKey} from './inputKeys';

export const STUDIO_NAV = [
 ['studio/home','首页',Sparkles], ['studio/flow','一站式创作',Layers3], ['benchmark','灵感与对标',WandSparkles], ['studio/topics','选题库',BookOpen],
 ['studio/text','文案创作',FileText], ['studio/image','图片创作',Image], ['studio/video','AI 视频',Film], ['studio/avatar/text','数字人视频',UserRound],
 ['knowledge','个人知识库',BookOpen], ['studio/brand','我的 IP',ShieldCheck], ['studio/works','作品与素材',FolderOpen], ['studio/assistant','问问梯见',FileText],
] as const;
type Field = {key:string; label:string; type?:string; required?:boolean; placeholder?:string; hint?:string; options?:any[]; accept?:string; min?:number; max?:number; default?:any; resource_kind?:string};
type Capability = {id:string; title?:string; route?:string; description?:string; fields?:Field[]; configured?:boolean; available?:boolean; enabled?:boolean; status?:string; provider?:string; cost_hint?:string; reason?:string; [key:string]:any};
type Asset = {id:string; title?:string; name?:string; kind?:string; type?:string; media_type?:string; status?:string; owner_id?:string; workspace_id?:string; visibility?:string; public?:boolean; provider?:string; url?:string; download_url?:string; preview_url?:string; text?:string; [key:string]:any};
type Draft = {id:string; route:string; tool:string; title:string; inputs:Record<string,any>; version:number; updated_at:string; request_id?:string; [key:string]:any};
type Run = {id:string; status:string; draft_id?:string; version?:number; draft_version?:number; message?:string; error?:string; outputs?:Asset[]; result?:any; [key:string]:any};
const pages:Record<string,{title:string; description:string; group:string; icon:any; tools:string[]; fields:Field[]}> = {
 'text':{title:'文案创作',description:'把你的行业经验，写成值得被看见的内容。',group:'文字',icon:FileText,tools:['text'],fields:[{key:'brief',label:'创作要求',type:'textarea',required:true,placeholder:'例如：向物业经理解释老旧电梯更新的三个常见误区。保留事实依据，不编造案例。'},{key:'format',label:'内容形式',type:'select',options:['通用文案','公众号文章','小红书文案','口播脚本']}]},
 'image':{title:'图片创作',description:'从一个画面想法开始，为内容找到视觉表达。',group:'图像',icon:Image,tools:['text_image','image_edit'],fields:[{key:'prompt',label:'画面描述',type:'textarea',required:true,placeholder:'描述主体、场景、构图与光线…'}]},
 'video':{title:'AI 视频',description:'让画面构想成为新的镜头与片段。',group:'视频',icon:Film,tools:['text_video','image_video'],fields:[{key:'prompt',label:'画面与运动描述',type:'textarea',required:true}]},
 'avatar/text':{title:'文字口播',description:'写好要说的话，交给你的数字人表达。',group:'数字人',icon:UserRound,tools:['text_avatar'],fields:[{key:'text',label:'口播文稿',type:'textarea',required:true},{key:'avatar_id',label:'出镜形象',type:'asset',resource_kind:'avatar',required:true},{key:'voice_id',label:'声音',type:'asset',resource_kind:'voice',required:true}]},
 'avatar/audio':{title:'音频口播',description:'保留原录音的声音与节奏，让形象跟随音频开口。',group:'数字人',icon:Mic,tools:['audio_avatar'],fields:[{key:'audio_id',label:'驱动音频',type:'asset',resource_kind:'audio',required:true,accept:'audio/*'},{key:'avatar_id',label:'出镜形象',type:'asset',resource_kind:'avatar',required:true}]},
 'avatar/photo':{title:'照片说话',description:'一张人物照片，一段文稿，创作一次说话视频。',group:'数字人',icon:Image,tools:['photo_talk'],fields:[{key:'photo_id',label:'人物照片',type:'asset',resource_kind:'image',required:true,accept:'image/*'},{key:'text',label:'要说的话',type:'textarea',required:true},{key:'voice_id',label:'声音',type:'asset',resource_kind:'voice',required:true}]},
 'avatar/create':{title:'创建形象',description:'上传本人或已获授权的素材，建立可复用的出镜形象。',group:'数字人',icon:UserRound,tools:['avatar_create'],fields:[{key:'title',label:'形象名称',required:true},{key:'source_id',label:'形象素材',type:'asset',resource_kind:'video',accept:'video/*',required:true},{key:'consent',label:'我确认已获得该人物的形象使用与创建授权',type:'checkbox',required:true}]},
 'audio/tts':{title:'文本配音',description:'用合适的声音，把一段好内容说清楚。',group:'音频',icon:AudioLines,tools:['tts'],fields:[{key:'text',label:'配音文稿',type:'textarea',required:true},{key:'voice_id',label:'声音',type:'asset',resource_kind:'voice',required:true}]},
 'audio/create':{title:'创建声音',description:'从获授权的录音建立声音资产，供后续创作选择。',group:'音频',icon:Mic,tools:['voice_create'],fields:[{key:'title',label:'声音名称',required:true},{key:'audio_id',label:'源录音',type:'asset',resource_kind:'audio',accept:'audio/*',required:true},{key:'consent',label:'我确认已获得该声音的克隆与使用授权',type:'checkbox',required:true}]},
 'compose':{title:'素材成片',description:'把镜头、配音与字幕组织成完整的一条作品。',group:'合成',icon:Layers3,tools:['compose'],fields:[]},
};
const tabGroups:Record<string,string[][]> = {
 'avatar':[['avatar/text','文字口播'],['avatar/audio','音频口播'],['avatar/photo','照片说话']],
 'audio':[['audio/tts','文本配音'],['audio/library','声音库'],['audio/create','创建声音']],
};
const statusText:Record<string,string>={queued:'等待处理',pending:'等待处理',preparing:'准备素材',submitting:'提交中',running:'生成中',processing:'处理中',succeeded:'已完成',success:'已完成',done:'已完成',completed:'已完成',failed:'生成失败',cancelled:'已取消',ready:'可用',unavailable:'不可用',saving:'正在保存结果',save_failed:'结果保存失败',submitted:'已提交',unknown:'提交状态待核查',archive_failed:'生成完成 · 保存文件失败',interrupted:'已中断 · 可核查继续'};
const active=(r:Run)=>['queued','pending','preparing','submitting','running','processing','submitted','saving'].includes(r.status);
const completed=(r:Run)=>['succeeded','success','done','completed','ready'].includes(r.status);
const rows=(value:any,key='items'):any[]=>Array.isArray(value)?value:Array.isArray(value?.[key])?value[key]:Array.isArray(value?.items)?value.items:[];
const message=(e:unknown)=>e instanceof Error?e.message:String(e);
const go=(path:string)=>{location.hash=path.startsWith('studio/')?path:'studio/'+path};
const time=(v:string)=>v?new Date(v).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'';
const mediaKind=(a:Asset)=>a.asset_type||a.media_type?.split('/')[0]||a.type||a.kind||'';
const safeUrl=(url?:string)=>url&&(/^(https?:|blob:)/.test(url)||url.startsWith('/api/'))?url:'';
const assetUrl=(a:Asset)=>safeUrl(a.file_url||a.preview_url||a.url||a.download_url);
const readLocal=(key:string)=>{try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}};
const routeForTool=(tool:string)=>Object.keys(pages).find(p=>pages[p].tools.includes(tool))||'text';
function decodeDraft(d:any):Draft{return {...d,server_id:d.id,server_version:d.version,route:'studio/'+routeForTool(d.tool),inputs:{...d.input,brand_id:d.brand_id||'',profile_id:d.profile_id||'',source_ids:d.source_ids||[]},options:d.options||{},updated_at:d.updated,version:d.version}}
function catalogFields(cap:Capability|undefined,fallback:Field[]):Field[]{
 if(!cap)return fallback.filter(f=>!['title','consent'].includes(f.key)).map(f=>({...f,key:f.key==='photo_id'?'image_id':f.key==='source_id'?'video_id':f.key}));
 if(cap.fields)return cap.fields;
 const keys=cap.id==='avatar_create'?['image_id','video_id']:[...(cap.required||[]),...(cap.optional||[])];
 const names:Record<string,string>={text:'文稿',prompt:'画面与创作要求',avatar_id:'出镜形象',voice_id:'声音',audio_id:'音频素材',image_id:cap.id==='photo_talk'?'人物照片':'参考图片',video_id:'人物视频',scenes:'场景'};
 return keys.map((key:string)=>{const resource=key.endsWith('_id')?key.slice(0,-3):'';return {key,label:names[key]||key,required:cap.id!=='avatar_create'&&!(cap.optional||[]).includes(key),type:resource?'asset':key==='scenes'?'scenes':'textarea',resource_kind:resource,accept:['image','video','audio'].includes(resource)?resource+'/*':undefined}});
}
function transferInput(owner:string){try{const raw=JSON.parse(sessionStorage.getItem('studio-transfer:'+owner)||'null');return raw&&typeof raw.brief==='string'&&Array.isArray(raw.source_ids)&&raw.source_ids.every((x:any)=>typeof x==='string')?raw:null}catch{return null}}
function Media({asset}:{asset:Asset}){
 const [url,setUrl]=useState(''),[error,setError]=useState('');
 useEffect(()=>{let live=true,object='';setUrl('');setError('');const source=assetUrl(asset);if(!source)return;
  if(!source.startsWith('/api/')){setUrl(source);return}
  const controller=new AbortController();fetch(source,{headers:{Authorization:'Bearer '+getToken()},signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error('文件暂时无法读取');object=URL.createObjectURL(await r.blob());if(live)setUrl(object);else URL.revokeObjectURL(object)}).catch(e=>{if(live&&e.name!=='AbortError')setError(message(e))});return()=>{live=false;controller.abort();if(object)URL.revokeObjectURL(object)};
 },[asset.id,asset.file_url,asset.url,asset.preview_url,asset.download_url]);
 const kind=mediaKind(asset);if(asset.text||asset.body)return <pre className="st-text-result">{asset.text||asset.body}</pre>;
 if(error)return <p className="st-muted">{error}</p>;
 if(!url)return <div className="st-media-placeholder">{assetUrl(asset)?'预览加载中…':'该资源暂无可验证预览'}</div>;
 return kind==='image'?<img src={url} alt={asset.title||'生成图片'} onError={()=>setError('预览不可用，请尝试下载原文件')}/>:kind==='audio'||kind==='voice'?<audio controls src={url} preload="metadata"/>:kind==='video'||kind==='avatar'?<video controls src={url} preload="metadata"/>:<p className="st-muted">此文件不支持内嵌预览，可下载查看。</p>;
}
async function saveFile(asset:Asset){
 if(asset.text||asset.body){const object=URL.createObjectURL(new Blob([asset.text||asset.body],{type:'text/plain;charset=utf-8'})),link=document.createElement('a');link.href=object;link.download=(asset.title||'文稿')+'.md';link.click();setTimeout(()=>URL.revokeObjectURL(object),10000);return}
 const url=safeUrl(asset.download_url||asset.url)||assetUrl(asset);if(!url)throw new Error('暂时没有可下载文件');
 const r=await fetch(url,{headers:url.startsWith('/api/')?{Authorization:'Bearer '+getToken()}:undefined});if(!r.ok)throw new Error('下载失败，原生成任务会保留，请稍后重试');
 const object=URL.createObjectURL(await r.blob()),link=document.createElement('a');link.href=object;link.download=asset.filename||asset.name||asset.title||'作品';link.click();setTimeout(()=>URL.revokeObjectURL(object),10000);
}
/** Pass the existing App context as t; route accepts hash or plain studio/... . */
export function Studio({t,route}:{t:any;route:string}){
 const normalized=route.replace(/^#\/?/,'').replace(/^studio\/?/,'')||'home';
 return <StudioPage key={(t.state?.user?.id||'guest')+':'+normalized} t={t} page={normalized}/>;
}
function StudioPage({t,page}:{t:any;page:string}){
 const [path,query='']=page.split('?'),params=new URLSearchParams(query),spec=pages[path];
 const owner=t.state?.user?.id||'guest',workspace=t.state?.workspace||'',scope=owner+':'+workspace;
 const mode=params.get('mode')||spec?.tools[0]||path;
 const key='tijian-studio-v2:'+scope+':'+path+':'+mode+':'+(params.get('draft')||'latest');
 const fresh=():Draft=>({id:crypto.randomUUID(),route:'studio/'+path,tool:mode,title:spec?.title||'未命名创作',inputs:{},version:1,updated_at:new Date().toISOString()});
 const incoming=useRef(path==='text'?transferInput(owner):null);
 const [draft,setDraft]=useState<Draft>(()=>{const base=readLocal(key)||fresh();return incoming.current?{...base,inputs:{...base.inputs,brief:incoming.current.brief,source_ids:incoming.current.source_ids},version:base.version+1,updated_at:new Date().toISOString()}:base});
 const [catalog,setCatalog]=useState<Capability[]>([]),[assets,setAssets]=useState<Asset[]>([]),[runs,setRuns]=useState<Run[]>([]),[drafts,setDrafts]=useState<Draft[]>([]);
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[saveState,setSaveState]=useState('正在恢复草稿');
 const [busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false),[selectedRun,setSelectedRun]=useState('');
 const [filter,setFilter]=useState(''),[returnTo]=useState(()=>params.get('return')||'');
 const [editorWidth,setEditorWidth]=useState(()=>Number(localStorage.getItem('tijian-studio-editor-width'))||500);
 const editorResize=useRef<{x:number;width:number}|null>(null);
 const draftRef=useRef(draft),submitLock=useRef(false),saveQueue=useRef(Promise.resolve()),alive=useRef(true),dirty=useRef(!!incoming.current);
 const persisted=useRef<{id?:string;version?:number;payload?:string}>({id:draft.server_id,version:draft.server_version});
 const [synced,setSynced]=useState(false);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[]);
 // The authenticated assets endpoint already enforces owner scope; it intentionally omits owner IDs.
 const visibleAssets=assets;
 const baseCap=catalog.find(c=>c.id===draft.tool);
 const selectedModel=baseCap?.models?.find((m:any)=>m.id===(draft.model_id||baseCap.binding));
 const cap:Capability|undefined=baseCap?{...baseCap,...(selectedModel?{options:selectedModel.options,configured:baseCap.binding!==''&&selectedModel.configured,status:selectedModel.configured?'ready':'unconfigured',...(draft.tool==='audio_avatar'&&selectedModel.family==='infinitetalk'?{required:['audio_id','image_id']}:{} )}:{}),optional:draft.tool==='text_image'&&selectedModel&&!selectedModel.id.startsWith('service:')?['image_id']:[]}:undefined;
 const [optimized,setOptimized]=useState('');
 useEffect(()=>{if(!cap||!synced||!draft.options)return;const options=Object.fromEntries(Object.entries(draft.options).filter(([k,v])=>(cap.options?.[k]||[]).includes(v)));if(JSON.stringify(options)!==JSON.stringify(draft.options)){dirty.current=true;setDraft(d=>({...d,options,version:d.version+1}));setNotice('服务绑定已更新，不兼容的旧参数已恢复为当前服务默认值。')}},[cap,synced]);
 const configured=path==='text'?!!t.state?.models?.some((m:any)=>m.id===t.state?.bindings?.writing&&m.capability==='text'&&m.published):!!cap&&cap.configured===true&&cap.available!==false&&cap.enabled!==false&&!['planned','unconfigured','unavailable','disabled'].includes(cap.status||'');
 const fields=catalogFields(cap,spec?.fields||[]).filter(f=>path!=='avatar/audio'||!/(voice|text|script|音色|文稿)/i.test(f.key+' '+f.label));
 const liveTextJobs=(t.list?.('job')||[]).filter((j:any)=>j.input?.draft_id===draft.id||(draft.job_ids||[]).includes(j.id)).map((j:any)=>({...j,draft_id:draft.id,draft_version:j.input?.draft_version||draft.job_versions?.[j.id]}));
 const currentRuns=path==='text'?liveTextJobs:runs.filter(r=>r.draft_id===draft.id),run=currentRuns.find((r:Run)=>r.id===selectedRun)||currentRuns[0];
 const running=currentRuns.some(active),profiles=t.list?.('profile')||[];
 const update=(values:Record<string,any>)=>{dirty.current=true;const selectVideo=draft.tool==='avatar_create'&&values.video_id,selectImage=draft.tool==='avatar_create'&&values.image_id;if(selectVideo||selectImage)setNotice('形象创建只使用一种素材，已取消另一种素材选择。'+(selectVideo?'视频形象不使用照片模型选项，已恢复默认。':''));setDraft(d=>({...d,inputs:{...d.inputs,...values,...(selectVideo?{image_id:''}:selectImage?{video_id:''}:{})},...(selectVideo?{options:{}}:{}),version:d.version+1,updated_at:new Date().toISOString(),request_id:undefined}));};
 const perform=async(fn:()=>Promise<void>)=>{setError('');setBusy(true);try{await fn()}catch(e){if(alive.current)setError(message(e))}finally{if(alive.current)setBusy(false)}};
 const loadAssets=async()=>{const response=await api('/studio/assets');if(alive.current)setAssets(rows(response,'assets'))};
 useEffect(()=>{let live=true;void (async()=>{
  const result=await Promise.allSettled([api('/studio/catalog'),api('/studio/assets'),api('/studio/runs'),api('/studio/drafts'),api('/studio/text/drafts')]);
  if(!live)return;
  if(result[0].status==='fulfilled'){const raw=result[0].value;setCatalog(rows(raw,'tools').length?rows(raw,'tools'):rows(raw,'capabilities'))}else setError('服务目录暂不可用：'+message(result[0].reason));
  if(result[1].status==='fulfilled')setAssets(rows(result[1].value,'assets'));
  if(result[2].status==='fulfilled')setRuns(rows(result[2].value,'runs'));
  if(result[3].status==='fulfilled'||result[4].status==='fulfilled'){
   const list=[...(result[3].status==='fulfilled'?rows(result[3].value,'drafts'):[]),...(result[4].status==='fulfilled'?rows(result[4].value,'drafts'):[])].map(decodeDraft).sort((a,b)=>String(b.updated_at||'').localeCompare(String(a.updated_at||'')));setDrafts(list);
   const remote=params.get('draft')?list.find((d:Draft)=>d.id===params.get('draft')):list.filter((d:Draft)=>d.tool===mode).sort((a:Draft,b:Draft)=>String(b.updated_at||'').localeCompare(String(a.updated_at||'')))[0];
   const local=readLocal(key);if(remote&&!dirty.current&&(!local||String(remote.updated_at||'')>String(local.updated_at||''))){persisted.current={id:remote.id,version:remote.server_version};setDraft(remote)}
  }
  setSynced(true);setLoading(false);setSaveState(readLocal(key)?'已恢复本机草稿':'草稿自动保存');
 })();return()=>{live=false}},[]);
 useEffect(()=>{draftRef.current=draft;if(!spec||!synced||(!dirty.current&&!draft.server_id))return;try{localStorage.setItem(key,JSON.stringify(draft));if(incoming.current){sessionStorage.removeItem('studio-transfer:'+owner);incoming.current=null;setNotice('已接收对标资料；品牌、身份与其他设置保持原选择。')}setSaveState('已暂存本机')}catch{setSaveState('本机保存失败，请检查存储空间')}
  const timer=setTimeout(()=>{void persist(draft)},850);return()=>clearTimeout(timer);
 },[draft,synced]);
 const persist=async(value:Draft)=>{
  const isText=value.tool==='text',c=catalog.find(x=>x.id===value.tool),family=c?.models?.find((m:any)=>m.id===(value.model_id||c?.binding))?.family,inputKeys=isText?['brief','format']:c?.id==='avatar_create'?['image_id','video_id']:value.tool==='audio_avatar'&&family==='infinitetalk'?['audio_id','image_id']:[...(c?.required||[]),...(value.tool==='text_image'?['image_id']:[]),...(value.tool==='image_edit'&&family==='gpt-image-2.5-edit'?['image_ids']:[]),...(value.tool==='image_video'||value.tool==='text_video'?['image_ids','video_ids','audio_ids']:[])];
  const input=Object.fromEntries(inputKeys.filter((k:string)=>value.inputs[k]!==undefined&&value.inputs[k]!=='').map((k:string)=>[k,value.inputs[k]]));
  const body={tool:value.tool,title:value.title,input,...(!isText?{model_id:value.model_id||''}:{}),...(isText?{job_ids:value.job_ids||[],job_versions:value.job_versions||{}}:{options:value.options||{}}),brand_id:value.inputs.brand_id||'',profile_id:value.inputs.profile_id||'',source_ids:value.inputs.source_ids||[]};
  const payload=JSON.stringify(body);let success=true;
  const task=saveQueue.current.catch(()=>{}).then(async()=>{try{
   if(persisted.current.payload===payload){if(alive.current)setSaveState('草稿已保存');return}
   const previous=persisted.current;
   const remote=await api((isText?'/studio/text/drafts':'/studio/drafts')+(previous.id?'/'+previous.id:''),{...body,...(previous.id?{version:previous.version}:{})},previous.id?'PATCH':'POST');
   persisted.current={id:remote.id,version:remote.version,payload};
   if(alive.current){setDraft(d=>({...d,id:remote.id,server_id:remote.id,server_version:remote.version}));if(draftRef.current.version===value.version)setSaveState('草稿已保存')}
  }catch(e){success=false;if(alive.current){setSaveState('已暂存本机 · 服务端未同步');setError('草稿同步失败：'+message(e))}}});saveQueue.current=task;await task;return success;
 };
 useEffect(()=>{if(!runs.some(active))return;let cancelled=false;let timer:ReturnType<typeof setTimeout>;
  const poll=async()=>{try{await Promise.all(runs.filter(active).map(r=>api('/studio/runs/'+r.id+'/refresh',undefined,'POST')));const result=await api('/studio/runs');if(cancelled)return;const next=rows(result,'runs');setRuns(next);if(next.some(completed))void loadAssets();if(next.some(active))timer=setTimeout(poll,4500)}catch{if(!cancelled){setNotice('状态查询暂时失败，未重复提交生成。稍后继续核查原任务。');timer=setTimeout(poll,6000)}}};timer=setTimeout(poll,4000);return()=>{cancelled=true;clearTimeout(timer)};
 },[runs.map(r=>r.id+':'+r.status).join('|')]);
 const upload=async(file:File,inputKey?:string)=>perform(async()=>{const data=new FormData();data.append('file',file);const result=await api('/studio/upload',data),asset=result.asset||result;if(!asset.id)throw new Error('上传未返回有效素材编号');await loadAssets();if(inputKey)update({[inputKey]:asset.id});setNotice('文件已上传并保存，可继续创作。')});
 const assetKind=(a:Asset,kind:string)=>mediaKind(a)===kind||a.kind===kind||(kind==='image'&&a.mime_type?.startsWith('image/'));
 const compatible=(a:Asset)=>Array.isArray(a.compat)&&a.compat.includes(draft.tool);
 const draftRoute=(d:Draft)=>(d.route||'studio/'+Object.keys(pages).find(p=>pages[p].tools.includes(d.tool)))+'?draft='+d.id+'&mode='+d.tool;
 const chooseResource=(kind:string)=>{const target=kind==='avatar'?'avatar/create':'audio/create';void persist(draft).then(()=>{const next={...draft,id:persisted.current.id||draft.id,server_id:persisted.current.id,server_version:persisted.current.version};try{localStorage.setItem('tijian-studio-v2:'+scope+':'+path+':'+draft.tool+':'+next.id,JSON.stringify(next));go(target+'?return='+encodeURIComponent(draftRoute(next)))}catch{setError('原草稿保存失败，请稍后重试')}})};
 const transfer=(target:string,values:Record<string,any>,tool?:string,origin=draft.inputs)=>{
  const targetMode=tool||pages[target]?.tools[0]||target,targetKey='tijian-studio-v2:'+scope+':'+target+':'+targetMode+':latest',previous=readLocal(targetKey);
  const next:Draft={...(previous||fresh()),route:'studio/'+target,tool:targetMode,title:pages[target]?.title||'创作',inputs:{...(previous?.inputs||{}),...values,brand_id:origin.brand_id,profile_id:origin.profile_id,...(values.source_asset_id&&t.get?.(values.source_asset_id)?.kind==='content'?{source_ids:[values.source_asset_id]}:{})},version:(previous?.version||0)+1,request_id:undefined,updated_at:new Date().toISOString()};
  try{localStorage.setItem(targetKey,JSON.stringify(next));go(target+'?mode='+targetMode)}catch{setError('无法保存传递草稿，请检查本机存储空间')}
 };
 const returnResource=(asset:Asset)=>{
  if(!returnTo)return;const [returnPath,q='']=returnTo.replace(/^studio\//,'').split('?'),p=new URLSearchParams(q),id=p.get('draft'),m=p.get('mode')||pages[returnPath]?.tools[0];
  const base='tijian-studio-v2:'+scope+':'+returnPath+':'+m+':',returnKey=base+(id||'latest'),original=readLocal(returnKey)||readLocal(base+'latest');
  if(!original){setError('原草稿尚未恢复，请从原页面选择该资源。');return}
  const resourceKey=path.startsWith('avatar')?'avatar_id':'voice_id';const next={...original,inputs:{...original.inputs,[resourceKey]:asset.id},version:original.version+1,updated_at:new Date().toISOString()};
  if(!asset.compat?.includes(m)){setError('该资源不支持原草稿的创作方式，请选择兼容资源。');return}
  try{localStorage.setItem(returnKey,JSON.stringify(next));go(returnTo)}catch{setError('无法保存原草稿，请稍后重试')}
 };
 const generate=async()=>{
  if(submitLock.current)return;submitLock.current=true;setConfirm(false);
  await perform(async()=>{
   const previous=currentRuns.find((r:Run)=>r.request_id===draft.request_id||r.input?.creation_request===draft.request_id);
   const requestId=draft.request_id&&(!previous||active(previous)||previous.status==='unknown')?draft.request_id:crypto.randomUUID(),snapshot={...draft,request_id:requestId};setDraft(snapshot);
   if(!await persist(snapshot))throw new Error('草稿尚未同步到服务端，本次未提交生成。');
   try{
    if(path==='text'){
     const j=await api('/studio/text/generate',{draft_id:persisted.current.id,brief:draft.inputs.brief,format:draft.inputs.format||'通用文案',brand_id:draft.inputs.brand_id||'',profile_id:draft.inputs.profile_id||'',source_ids:draft.inputs.source_ids||[],request_id:requestId});
     setDraft(d=>({...d,job_ids:[...(d.job_ids||[]).filter((id:string)=>id!==j.id),j.id],job_versions:{...d.job_versions,[j.id]:draft.version}}));await t.refresh?.();
    }else{const response=await api('/studio/generate',{draft_id:persisted.current.id,version:persisted.current.version,request_id:requestId,confirmed:true});const next=response.run||response;if(!next.id)throw new Error('服务未返回任务编号，请到生成记录核查');setRuns(old=>[next,...old.filter(r=>r.id!==next.id)]);setSelectedRun(next.id)}
    setNotice('任务已提交。离开页面后仍可从作品与草稿继续查看。')
   }catch(e){setNotice('提交状态不确定时请先刷新生成记录，重试沿用同一请求编号。');throw e}
  });submitLock.current=false;
 };
 const outputs=(r?:Run):Asset[]=>{if(!r)return [];const content=t.get?.(r.result?.content_id);if(content)return [{...content,kind:'text',text:content.body}];return visibleAssets.filter(a=>(r.asset_ids||[]).includes(a.id))};
 const missing=fields.filter(f=>f.required&&(!draft.inputs[f.key]||(Array.isArray(draft.inputs[f.key])&&!draft.inputs[f.key].length)));
 const unusable=fields.some(f=>f.type==='asset'&&draft.inputs[f.key]&&!visibleAssets.some(a=>a.id===draft.inputs[f.key]&&compatible(a)&&(!a.status||['ready','available','completed','done'].includes(a.status))));
 const canGenerate=configured&&!running&&!currentRuns.some((r:Run)=>r.status==='unknown')&&!busy&&!loading&&!missing.length&&!unusable&&(draft.tool!=='avatar_create'||!!draft.inputs.image_id!==!!draft.inputs.video_id)&&(path!=='compose'||(draft.inputs.scenes?.length>0&&draft.inputs.scenes.every((s:any)=>s.asset_id&&s.length>0)));
 const tabs=tabGroups[path.split('/')[0]],title=spec?.title||({'flow':'一站式创作','home':'首页','assistant':'问问梯见','works':'作品与素材','assets':'作品与素材','brand':'我的 IP','about':'关于与更新','avatar/library':'数字人形象','audio/library':'声音资产'} as any)[path]||'创作工作台';
 const Icon=spec?.icon||Sparkles;
 const fieldUI=(f:Field)=>{
  const value=draft.inputs[f.key]??f.default??'';
  return <label className={'st-field '+(f.type==='textarea'?'st-wide':'')} key={f.key}><span>{f.label}{f.required&&<em>必填</em>}</span>
   {f.type==='asset'||f.type==='upload'?<><select value={value} onChange={e=>update({[f.key]:e.target.value})}><option value="">选择{f.label}</option>{visibleAssets.filter(a=>assetKind(a,f.resource_kind||'')&&compatible(a)&&(!a.status||['ready','available','completed','done'].includes(a.status))).map(a=><option value={a.id} key={a.id}>{a.title||a.name||a.id}{a.visibility==='public'?' · 公共':''}</option>)}</select><div className="st-inline">{f.accept&&<label className="st-upload-inline"><Upload size={14}/>上传文件<input type="file" accept={f.accept} disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file,f.key);e.target.value=''}}/></label>}{['avatar','voice'].includes(f.resource_kind||'')&&<button type="button" className="st-link" onClick={()=>chooseResource(f.resource_kind!)}><Plus size={14}/>创建{f.resource_kind==='avatar'?'形象':'声音'}</button>}</div>{value&&visibleAssets.find(a=>a.id===value)&&<div className="st-input-preview"><Media asset={visibleAssets.find(a=>a.id===value)!}/></div>}</>:
   f.type==='textarea'?<textarea onKeyDown={e=>sendKey(e,()=>{if(canGenerate)setConfirm(true)},v=>update({[f.key]:v}))} rows={f.key==='text'?10:6} value={value} placeholder={f.placeholder||'输入创作要求 · Enter 继续，Ctrl + Enter 换行'} onChange={e=>update({[f.key]:e.target.value})}/>:
   f.type==='checkbox'?<input type="checkbox" checked={!!value} onChange={e=>update({[f.key]:e.target.checked})}/>:
   f.options?<select value={value} onChange={e=>update({[f.key]:e.target.value})}><option value="">请选择</option>{f.options.map((o:any)=><option key={typeof o==='string'?o:o.value} value={typeof o==='string'?o:o.value}>{typeof o==='string'?o:o.label}</option>)}</select>:
   <input type={f.type==='number'?'number':'text'} value={value} min={f.min} max={f.max} placeholder={f.placeholder} onChange={e=>update({[f.key]:f.type==='number'&&e.target.value!==''?Number(e.target.value):e.target.value})}/>}
   {f.hint&&<small>{f.hint}</small>}
  </label>
 };
 const outputUI=(asset:Asset,origin=draft.inputs)=><article className="st-output" key={asset.id}>{asset.text||asset.body?<TextResult asset={asset} t={t}/>:<Media asset={asset}/>}{asset.width&&asset.height&&<div className="st-asset-dimensions"><span>实际尺寸 {asset.width} × {asset.height}{asset.duration?' · '+Number(asset.duration).toFixed(1)+' 秒':''}</span>{asset.requested_size&&asset.requested_size.replace('*','x')!==`${asset.width}x${asset.height}`&&<small>请求 {asset.requested_size.replace(/[x*]/g,' × ')}，服务返回尺寸不同，已保留原图。</small>}</div>}<div className="st-output-footer"><strong>{asset.title||asset.name||'生成结果'}</strong><button type="button" onClick={()=>void perform(()=>saveFile(asset))}><Download size={15}/>下载</button></div><div className="st-inline">{mediaKind(asset)==='audio'&&<button className="st-link" onClick={()=>transfer('avatar/audio',{audio_id:asset.id,source_asset_id:asset.id},undefined,origin)}>用于音频口播<ArrowRight size={14}/></button>}{mediaKind(asset)==='image'&&<button className="st-link" onClick={()=>transfer('video',{image_id:asset.id,source_asset_id:asset.id},'image_video',origin)}>用于视频创作<ArrowRight size={14}/></button>}{['video','audio','image'].includes(mediaKind(asset))&&<button className="st-link" onClick={()=>transfer('compose',{scenes:[{asset_id:mediaKind(asset)==='audio'?'':asset.id,...(mediaKind(asset)==='audio'?{audio_id:asset.id}:{}),length:asset.duration||5,caption:'',volume:1}]},undefined,origin)}>用于素材成片<ArrowRight size={14}/></button>}{(asset.text||asset.body)&&<><button className="st-link" onClick={()=>transfer('avatar/text',{text:asset.text||asset.body,source_asset_id:asset.id},undefined,origin)}>用于文字口播</button><button className="st-link" onClick={()=>transfer('audio/tts',{text:asset.text||asset.body,source_asset_id:asset.id},undefined,origin)}>用于配音</button></>}{returnTo&&['avatar','voice'].includes(mediaKind(asset))&&<button className="st-primary" onClick={()=>returnResource(asset)}>使用并返回原稿</button>}</div></article>;
 if(path==='topics')return <TopicDelivery t={t} page={page}/>;
 if(path==='memory-settings')return <div className="st-memory-page"><a href="#studio/home">← 返回首页</a><MemorySettings {...t}/></div>;
 if(path==='image'||path==='video')return <>{returnTo&&<a className="st-flow-return" href={'#'+returnTo}>← 返回一站式创作，继续下一步</a>}<MediaWorkbench scenario={path==='video'?<VideoScenarios compact assets={visibleAssets} initial={params.get('scenario')||''} onModeChange={(_key,name)=>update({prompt:'创作类型：'+name+'\n'+(draft.inputs.prompt||'').replace(/^创作类型：[^\n]*\n?/, '')})} onApply={async(prompt,imageId,scenario,videoId)=>{
  const target=imageId?'image_video':'text_video';
  const modelId=draft.model_id||baseCap?.binding||'';
  if(videoId&&!modelId)throw new Error('请先在视频制作区选择 Seedance 模型，再带入参考视频');
  const references={...(imageId?{image_id:imageId,...(modelId?{image_ids:[imageId]}:{})}:{}),...(videoId?{video_ids:[videoId]}:{})};
  if(target===draft.tool){update({prompt,...references});setNotice('场景要求已带入本页草稿，请核对参数。');return}
  const next=await api('/studio/drafts',{title:draft.title||'AI 视频创作',tool:target,input:{prompt,...references},model_id:modelId,brand_id:draft.inputs.brand_id||'',profile_id:draft.inputs.profile_id||'',source_ids:[],options:{}});
  go('video?draft='+next.id+'&mode='+target+'&scenario='+scenario+(returnTo?'&return='+encodeURIComponent(returnTo):''));
 }}/> :null} owner={owner} draft={draft} cap={cap} baseCap={baseCap} assets={visibleAssets} reloadAssets={loadAssets} runs={runs.filter(r=>pages[path].tools.includes(r.tool))} update={update} busy={busy} running={running} configured={configured} error={error} notice={notice} saveState={saveState} canGenerate={canGenerate} generate={()=>setConfirm(true)} upload={upload} outputs={outputs} outputUI={outputUI} context={<div className="mw-brand-fields"><label>我的 IP<select value={draft.inputs.profile_id||''} onChange={e=>update({profile_id:e.target.value})}><option value="">通用表达</option>{profiles.map((p:any)=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><a href="#studio/brand">编辑个人 IP →</a></div>}
 changeModel={(id:string)=>{const limits=baseCap?.models?.find((m:any)=>m.id===(id||baseCap.binding))?.reference_limits;if(path==='video'&&limits&&(['image','video','audio'] as const).some(kind=>(draft.inputs[kind+'_ids']?.length||0)>(limits[kind]||0))){setError('当前参考素材超过新模型上限。先在参考素材中移除多余文件，再切换模型。');return}setError('');dirty.current=true;setDraft(d=>({...d,model_id:id,inputs:d.tool==='text_image'&&(id||baseCap?.binding||'').startsWith('service:')?Object.fromEntries(Object.entries(d.inputs).filter(([k])=>k!=='image_id')):d.inputs,options:{},version:d.version+1,request_id:undefined}))}}
 changeOptions={(k:string,v:any)=>{dirty.current=true;setDraft(d=>({...d,options:v===undefined?Object.fromEntries(Object.entries(d.options||{}).filter(([key])=>key!==k)):{...d.options,[k]:v},version:d.version+1,request_id:undefined}))}}
 reuse={(r:any)=>{const g=r.generation;if(r.tool!==draft.tool){void perform(async()=>{const next=await api('/studio/drafts',{tool:r.tool,title:r.title||spec?.title,input:g.input||{},model_id:g.model_id||'',options:g.options||{},brand_id:g.brand_id||'',profile_id:g.profile_id||''});go(draftRoute(decodeDraft(next)))});return}dirty.current=true;setDraft(d=>({...d,inputs:{...g.input,brand_id:g.brand_id||'',profile_id:g.profile_id||''},model_id:g.model_id,options:g.options||{},version:d.version+1,request_id:undefined}));setNotice('已复用这次创作的提示词与参数，可继续修改。')}}
 refreshRun={(r:any)=>void perform(async()=>{await api('/studio/runs/'+r.id+'/refresh',undefined,'POST');setRuns(rows(await api('/studio/runs'),'runs'));await loadAssets()})}/>{confirm&&<CostDialog title="确认开始生成" cost={cap?.cost_hint} regenerate={!!currentRuns.length} onClose={()=>setConfirm(false)} onConfirm={()=>void generate()}/>}</>;
 return <div className="studio-v2">
  <header className="st-header"><div><div className="st-eyebrow">梯见 / CREATIVE STUDIO <span>V2</span></div><h1>{title}</h1><p>{spec?.description||({'works':'在一处查看生成作品、任务记录和上传素材。','assets':'在一处查看生成作品、任务记录和上传素材。','brand':'记录你的个人定位、服务经验和代理品牌信息。','avatar/library':'管理已授权的出镜形象及创建状态。','audio/library':'管理可复用的声音资产及创建状态。','about':'查看当前版本与更新状态。'} as Record<string,string>)[path]||'把资料与创作工具连接起来。'}</p></div><div className="st-header-tools">{spec&&<span className="st-save" role="status"><Check size={14}/>{saveState}</span>}{spec&&<a href="#studio/works" className="st-records">生成记录<ArrowUpRight size={16}/></a>}</div></header>
  {tabs&&<nav className="st-tabs" aria-label="模块功能">{tabs.map(([p,label])=><a key={p} href={'#studio/'+p+(returnTo?'?return='+encodeURIComponent(returnTo):'')} aria-current={path===p?'page':undefined}>{label}</a>)}</nav>}
  {spec&&spec.tools.length>1&&<nav className="st-tabs" aria-label="独立创作方式">{spec.tools.map(tool=><a key={tool} href={'#studio/'+path+'?mode='+tool} aria-current={draft.tool===tool?'page':undefined}>{catalog.find(c=>c.id===tool)?.title||({text_image:'AI 生图',image_edit:'图片修改',text_video:'文字生成视频',image_video:'图片生成视频'} as any)[tool]}</a>)}</nav>}
  {!spec&&error&&<div className="st-alert" role="alert"><span>{error}</span><button aria-label="关闭错误" onClick={()=>setError('')}><X size={16}/></button></div>}{!spec&&notice&&<div className="st-notice" role="status">{notice}<button aria-label="关闭提示" onClick={()=>setNotice('')}><X size={15}/></button></div>}
  {path==='home'&&<StudioHome t={t} drafts={drafts.map(d=>({...d,href:'#'+draftRoute(d)}))}/>}
  {path==='assistant'&&<KnowledgeAssistant t={t}/>}
  {(path==='works'||path==='assets')&&<nav className="st-library-tabs" aria-label="作品与素材"><a href="#studio/works" aria-current={path==='works'?'page':undefined}>作品与生成记录 <span>{runs.length}</span></a><a href="#studio/assets" aria-current={path==='assets'?'page':undefined}>素材库 <span>{visibleAssets.length}</span></a></nav>}
  {spec&&<div className="st-workspace st-resizable" style={{'--st-editor-width':editorWidth+'px'} as React.CSSProperties}><section className="st-editor"><div className="st-panel-head"><span className="st-step">01</span><div><h2>创作输入</h2><small>当前草稿 v{draft.server_version||draft.version}</small></div><Icon size={19}/></div><div className="st-editor-body"><div className="st-context"><label>我的 IP<select value={draft.inputs.profile_id||''} onChange={e=>update({profile_id:e.target.value})}><option value="">通用表达</option>{profiles.map((p:any)=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label></div>
   {path==='avatar/audio'&&<p className="st-inline-tip"><AudioLines size={17}/>使用原音频，不另选音色、不重新配音。</p>}
   {cap?.models&&['text_image','image_edit','text_video','image_video','text_avatar','audio_avatar','photo_talk'].includes(draft.tool)&&<label className="st-field st-model-select"><span>生成模型</span><select aria-label="生成模型" value={draft.model_id||baseCap?.binding||''} onChange={e=>{dirty.current=true;setOptimized('');setDraft(d=>({...d,model_id:e.target.value,inputs:d.tool==='text_image'&&(e.target.value||baseCap?.binding||'').startsWith('service:')?Object.fromEntries(Object.entries(d.inputs).filter(([k])=>k!=='image_id')):d.inputs,options:{},version:d.version+1,request_id:undefined}))}}><option value="">使用后台默认模型</option>{cap.models.map((m:any)=><option key={m.id} value={m.id}>{m.title}{m.configured?'':' · 接口待接入'}</option>)}</select><small>根据所选模型显示需要的照片、数字人形象与音频素材；接口待接入的模型可先保存草稿。</small></label>}
   <div className="st-fields">{fields.filter(f=>f.key!=='scenes').map(fieldUI)}</div>
   {['text_image','image_edit','text_video','image_video'].includes(draft.tool)&&<div className="st-prompt-tools"><button disabled={busy||!draft.inputs.prompt?.trim()} onClick={()=>void perform(async()=>{const job=await api('/studio/prompt/optimize',{prompt:draft.inputs.prompt,type:path==='video'?'video':'image'});let j=job;while(['queued','running'].includes(j.status)){await new Promise(r=>setTimeout(r,800));j=await api('/jobs/'+j.id)}if(j.status!=='done')throw new Error(j.error||'优化未完成');if(alive.current)setOptimized(j.result.optimized_prompt)})}>AI 优化提示词</button>{optimized&&<div><textarea value={optimized} data-enter="newline" onChange={e=>setOptimized(e.target.value)} aria-label="优化后的提示词"/><button onClick={()=>{update({prompt:optimized});setOptimized('')}}>采用优化结果</button><button onClick={()=>setOptimized('')}>保留原文</button></div>}</div>}
   {draft.tool==='avatar_create'&&<p className="st-inline-tip">照片与视频二选一，创建后可返回原稿使用。名称使用下方草稿名称。</p>}
   {!!Object.keys(cap?.options||{}).length&&!(draft.tool==='avatar_create'&&draft.inputs.video_id)&&<details className="st-source-detail" open><summary>生成设置<ChevronDown size={14}/></summary><div className="st-fields">{Object.entries(cap?.options||{}).map(([name,choices])=><label className="st-field" key={name}><span>{({st_show:'字幕',model:'生成方式',quality:'生成质量',size:'图片尺寸 / 比例',watermark:'水印',resolution:'清晰度',ratio:'画面比例',aspectRatio:'画面比例',duration:'时长（秒）'} as any)[name]||name}</span><select value={draft.options?.[name]===undefined?'':JSON.stringify(draft.options[name])} onChange={e=>{dirty.current=true;setDraft(d=>({...d,options:e.target.value?{...d.options,[name]:JSON.parse(e.target.value)}:Object.fromEntries(Object.entries(d.options||{}).filter(([k])=>k!==name)),version:d.version+1,request_id:undefined,updated_at:new Date().toISOString()}))}}><option value="">服务默认</option>{(choices as any[]).map(v=><option key={JSON.stringify(v)} value={JSON.stringify(v)}>{typeof v==='boolean'?(v?'开启':'关闭'):name==='st_show'?(v?'显示字幕':'不显示字幕'):({low:'低',medium:'中',high:'高',auto:'自动','1024x1024':'方形 1:1 · 1024×1024','1536x1024':'横版 3:2 · 1536×1024','1024x1536':'竖版 2:3 · 1024×1536','1536x864':'横屏 16:9 · 1536×864','864x1536':'竖屏 9:16 · 864×1536','2048x2048':'方形 2K · 2048×2048','2560x1440':'横屏 2K · 2560×1440','1440x2560':'竖屏 2K · 1440×2560'} as any)[String(v)]||String(v)}</option>)}</select></label>)}</div></details>}
   {path==='compose'&&<SceneEditor scenes={draft.inputs.scenes||[]} assets={visibleAssets.filter(a=>['video','image','audio'].includes(mediaKind(a)))} onChange={scenes=>update({scenes})} fields={fields}/>}
   {path==='text'&&<details className="st-source-detail"><summary>选择本次参考资料<ChevronDown size={14}/></summary>{[...(t.list?.('source')||[]),...(t.list?.('content')||[])].slice(0,100).map((s:any)=><label className="st-check-row" key={s.id}><input type="checkbox" checked={(draft.inputs.source_ids||[]).includes(s.id)} onChange={e=>update({source_ids:e.target.checked?[...(draft.inputs.source_ids||[]),s.id]:(draft.inputs.source_ids||[]).filter((id:string)=>id!==s.id)})}/>{s.title}</label>)}</details>}
   <details className="st-source-detail"><summary>本次资料与版本<ChevronDown size={14}/></summary><p>身份只用于辅助表达，切换身份不会覆盖已输入文稿。生成结果绑定提交时的草稿版本。</p><label className="st-field"><span>草稿名称</span><input value={draft.title} onChange={e=>{dirty.current=true;setDraft(d=>({...d,title:e.target.value,version:d.version+1,updated_at:new Date().toISOString()}))}}/></label></details>
  </div><footer className="st-generate-bar">{error&&<p className="st-alert" role="alert">{error}</p>}{notice&&!notice.startsWith('任务已提交')&&<small role="status">{notice}</small>}{!configured&&<div className="st-config-hint"><Settings2 size={17}/><span>{loading?'正在检查可用能力…':cap?.reason||'此功能尚未配置可用服务。请联系管理员，草稿可以继续编辑。'}</span></div>}<div className="st-cost"><small>{cap?.cost_hint||'调用生成服务可能产生费用，以供应商实际账单为准。'}</small><button className="st-primary" disabled={!canGenerate} onClick={()=>setConfirm(true)}>{running?<LoaderCircle size={17} className="st-spin"/>:<WandSparkles size={17}/>} {running?'任务处理中':currentRuns.length?'重新生成':'开始生成'}</button></div>{unusable&&<small className="st-warning">所选资源暂不可用或与当前服务不兼容，请重新选择。</small>}</footer></section>
  <div className="st-pane-resizer" role="separator" aria-label="拖动调整创作区宽度；双击还原" aria-orientation="vertical" tabIndex={0} onPointerDown={e=>{e.preventDefault();editorResize.current={x:e.clientX,width:editorWidth};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!editorResize.current)return;const width=Math.max(320,Math.min(720,editorResize.current.width+e.clientX-editorResize.current.x));const snapped=Math.abs(width-500)<14?500:width;setEditorWidth(snapped);localStorage.setItem('tijian-studio-editor-width',String(snapped))}} onPointerUp={()=>{editorResize.current=null}} onDoubleClick={()=>{setEditorWidth(500);localStorage.setItem('tijian-studio-editor-width','500')}} onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){const width=Math.max(320,Math.min(720,editorWidth+(e.key==='ArrowLeft'?-20:20)));setEditorWidth(width);localStorage.setItem('tijian-studio-editor-width',String(width))}}}/>  <aside className="st-preview"><div className="st-panel-head"><span className="st-step">02</span><div><h2>结果与版本</h2><small>每次生成，独立保留</small></div><span className="st-dot"/></div>{run?<><div className="st-run-head"><span className={'st-status '+(active(run)?'working':run.status==='failed'?'failed':'')}>{active(run)&&<LoaderCircle size={14} className="st-spin"/>}{statusText[run.status]||run.status}</span><select aria-label="查看生成版本" value={run.id} onChange={e=>setSelectedRun(e.target.value)}>{currentRuns.map((r:Run,i:number)=><option key={r.id} value={r.id}>生成 {currentRuns.length-i} · 草稿 v{r.draft_version||r.version||'—'} · {statusText[r.status]||r.status}</option>)}</select></div>{run.error&&<div className="st-alert">{run.error}</div>}{run.message&&<p className="st-run-message">{run.message}</p>}{(run.draft_version||run.version)!==(draft.server_version||draft.version)&&<p className="st-version-note">此结果对应提交时的文稿，之后修改的草稿不会改变已有成品。</p>}{outputs(run).length?outputs(run).map(a=>outputUI(a)):<div className="st-empty"><Icon size={40}/><h3>{active(run)?'正在创作，请稍候':completed(run)?'任务已结束，结果文件尚未就绪':'本次未获得可用成品'}</h3><p>{active(run)?'可离开本页，任务编号和草稿会保留。':'请核查原任务结果，无需重复付费生成。'}</p><button onClick={()=>void perform(async()=>{if(path!=='text')await api('/studio/runs/'+run.id+'/refresh',undefined,'POST');const r=await api('/studio/runs');setRuns(rows(r,'runs'));await loadAssets();await t.refresh?.()})}><RefreshCw size={14}/>核查原任务</button></div>}</>:<div className="st-preview-empty"><div className="st-preview-lines"><Icon size={40} strokeWidth={1}/></div><span className="st-kicker">等待你的第一个版本</span><h3>作品会在这里出现</h3><p>完成左侧输入后开始生成。<br/></p><div className="st-preview-flow"><span>输入</span><i/><span>生成</span><i/><span>保存</span></div></div>}{returnTo&&<a className="st-return" href={'#'+returnTo}>← 返回原草稿（已保留输入）</a>}</aside></div>}
  {(path==='assets'||path.endsWith('/library'))&&<><div className="st-section-head"><div><h2>{path==='assets'?'可用于本次创作的素材':'可复用的'+(path.startsWith('avatar')?'出镜形象':'声音')}</h2><p className="st-muted">只展示当前账户授权资源与公共资源，公共库为部分可用资源。</p></div><div className="st-inline">{path!=='assets'&&<button disabled={busy} onClick={()=>void perform(async()=>{const kind=path.startsWith('avatar')?'avatar':'voice';await api('/studio/assets?asset_type='+kind+'&refresh=true');await loadAssets()})}><RefreshCw size={14}/>同步公共资源</button>}{path==='assets'?<label className="st-primary st-upload-inline"><Upload size={16}/>上传素材<input type="file" disabled={busy} accept="image/png,image/jpeg,image/webp,audio/mpeg,audio/wav,audio/mp4,video/mp4,video/quicktime" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value=''}}/></label>:<a className="st-primary" href={'#studio/'+(path.startsWith('avatar')?'avatar/create':'audio/create')+(returnTo?'?return='+encodeURIComponent(returnTo):'')}><Plus size={16}/>创建{path.startsWith('avatar')?'形象':'声音'}</a>}</div></div><input className="st-search" value={filter} onChange={e=>setFilter(e.target.value)} aria-label="搜索资源" placeholder="搜索名称…"/><div className="st-asset-grid">{visibleAssets.filter(a=>(path==='assets'||mediaKind(a)===(path.startsWith('avatar')?'avatar':'voice'))&&String(a.title||a.name||'').includes(filter)).map(a=><article className="st-asset-card" key={a.id}><div className="st-asset-media">{a.file_url||a.preview_url||a.url?<Media asset={a}/>:<div className="st-empty compact"><UserRound size={30}/><span>暂无可验证预览</span></div>}</div><h3>{a.title||a.name||'未命名资源'}</h3><p><span className="st-status">{statusText[a.status||'']||a.status||'已保存'}</span><small>{a.visibility==='public'?'公共资源':'专属资源'}</small></p>{returnTo&&a.status==='ready'?<button onClick={()=>returnResource(a)}>使用并返回原稿<ArrowRight size={14}/></button>:path==='assets'&&a.file_url?<button onClick={()=>void perform(()=>saveFile(a))}><Download size={14}/>下载原文件</button>:null}</article>)}</div>{!visibleAssets.filter(a=>path==='assets'||mediaKind(a)===(path.startsWith('avatar')?'avatar':'voice')).length&&<div className="st-empty"><FolderOpen size={38}/><h3>{loading?'正在读取资源…':'还没有可用资源'}</h3><p>上传或创建后会显示实际资源及处理状态。</p></div>}</>}
  {path==='works'&&<><div className="st-section-head"><h2>生成记录 <span className="st-count">{runs.length+(t.list?.('job')||[]).filter((j:any)=>j.input?.action==='studio_text').length}</span></h2><button onClick={()=>void perform(async()=>{await Promise.all(runs.filter(r=>active(r)||['unknown','archive_failed'].includes(r.status)).map(r=>api('/studio/runs/'+r.id+'/refresh',undefined,'POST')));const r=await api('/studio/runs');setRuns(rows(r,'runs'));await loadAssets();await t.refresh?.()})}><RefreshCw size={15}/>核查原任务</button></div>{[...runs,...(t.list?.('job')||[]).filter((j:any)=>j.input?.action==='studio_text')].length?<div className="st-work-list">{[...runs,...(t.list?.('job')||[]).filter((j:any)=>j.input?.action==='studio_text')].map(r=><article key={r.id}><div className="st-section-head"><div><h3>{r.title||'创作任务'}</h3><small>{time(r.created||r.created_at||r.updated)} · 草稿 v{r.draft_version||'—'}</small></div><span className={'st-status '+(active(r)?'working':'')}>{statusText[r.status]||r.status}</span></div>{r.error&&<p className="st-warning">{r.error}</p>}{outputs(r).map(a=>outputUI(a))}{r.draft_id&&drafts.find(d=>d.id===r.draft_id)&&<a className="st-link" href={'#'+draftRoute(drafts.find(d=>d.id===r.draft_id)!)}>打开原草稿<ArrowRight size={14}/></a>}</article>)}</div>:<div className="st-empty"><Film size={40}/><h3>第一件作品，从一个想法开始</h3><p>真实生成记录、失败状态与历史版本都会保留在这里。</p><a href="#studio/text" className="st-primary">开始创作</a></div>}</>}
  {path==='brand'&&<PersonalIP t={t} assets={visibleAssets}/>}{path==='flow'&&<CreationFlow t={t}/>}
  {(path==='about'||path==='settings')&&<section className="st-about"><h2>关于与更新</h2><DesktopUpdates/></section>}
  {!spec&&!['flow','home','assistant','assets','works','brand','about','settings','avatar/library','audio/library'].includes(path)&&<div className="st-empty"><h2>此页面尚未开放</h2><a href="#studio/home">返回首页</a></div>}
  {confirm&&<CostDialog title={currentRuns.length?'确认生成新版本':'确认开始生成'} cost={cap?.cost_hint} regenerate={!!currentRuns.length} onClose={()=>setConfirm(false)} onConfirm={()=>void generate()}/>}
 </div>;
}
function TextResult({asset,t}:{asset:Asset;t:any}){return <ArticleEditor asset={asset} t={t}/>;}
function CostDialog({title,cost,regenerate,onClose,onConfirm}:{title:string;cost?:string;regenerate:boolean;onClose:()=>void;onConfirm:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{dialog.current?.showModal();return()=>dialog.current?.close()},[]);
 return <dialog ref={dialog} className="st-dialog" onCancel={e=>{e.preventDefault();onClose()}} aria-labelledby="st-cost-title"><div className="st-eyebrow">生成确认</div><h2 id="st-cost-title">{title}</h2><p>{regenerate?'这将使用当前草稿创建一个新版本，并产生新的服务消耗；已有作品会保留。':'这将把本次选择的内容与素材上传给生成服务处理。'}</p><p>请确认所选人物、声音与其他素材已获授权；本次仅提交草稿中选择的素材。</p><p className="st-dialog-cost">{cost||'服务可能按次数、字数或时长计费，实际费用以供应商账单为准。'}</p><div className="st-dialog-actions"><button onClick={onClose}>继续编辑</button><button autoFocus className="st-primary" onClick={onConfirm}>确认上传与消耗<ArrowRight size={16}/></button></div></dialog>
}
function SceneEditor({scenes,assets,onChange}:{scenes:any[];assets:Asset[];onChange:(s:any[])=>void;fields?:Field[]}){
 const change=(index:number,key:string,value:any)=>onChange(scenes.map((s,i)=>i===index?{...s,[key]:value}:s));
 return <div className="st-scenes"><div className="st-section-head"><h3>场景顺序</h3><button onClick={()=>onChange([...scenes,{asset_id:'',length:5,fit:'cover',volume:1}])}><Plus size={14}/>添加场景</button></div>{!scenes.length&&<p className="st-muted">选择已有素材，按叙事顺序组织片段。合成不会自动补足缺少的镜头。</p>}{scenes.map((s,i)=><div className="st-scene" key={i}><div className="st-section-head"><strong>场景 {String(i+1).padStart(2,'0')}</strong><div className="st-inline"><button aria-label={'上移场景'+(i+1)} disabled={!i} onClick={()=>{const next=[...scenes];[next[i-1],next[i]]=[next[i],next[i-1]];onChange(next)}}>↑</button><button aria-label={'下移场景'+(i+1)} disabled={i===scenes.length-1} onClick={()=>{const next=[...scenes];[next[i+1],next[i]]=[next[i],next[i+1]];onChange(next)}}>↓</button><button aria-label={'移除场景'+(i+1)} onClick={()=>onChange(scenes.filter((_,n)=>i!==n))}><X size={14}/></button></div></div><label className="st-field"><span>画面素材{s.audio_id&&!s.asset_id&&<em>已带入配音，请补充图片或视频</em>}</span><select value={s.asset_id} onChange={e=>change(i,'asset_id',e.target.value)}><option value="">选择图片或视频</option>{assets.filter(a=>['image','video'].includes(mediaKind(a))).map(a=><option key={a.id} value={a.id}>{a.title||a.name||a.id}</option>)}</select></label><div className="st-fields"><label className="st-field"><span>时长（秒）</span><input type="number" min="0.1" step="0.1" value={s.length} onChange={e=>change(i,'length',Number(e.target.value))}/></label><label className="st-field"><span>画面适配</span><select value={s.fit||'cover'} onChange={e=>change(i,'fit',e.target.value)}><option value="cover">填满画面</option><option value="contain">完整显示</option><option value="crop">裁切</option><option value="none">原尺寸</option></select></label></div><label className="st-field"><span>配音（可选）</span><select value={s.audio_id||''} onChange={e=>change(i,'audio_id',e.target.value||undefined)}><option value="">不添加配音</option>{assets.filter(a=>mediaKind(a)==='audio').map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label><label className="st-check-row"><input type="checkbox" checked={s.volume!==0} onChange={e=>change(i,'volume',e.target.checked?1:0)}/>保留原声</label><label className="st-field"><span>字幕</span><input value={s.caption||''} onChange={e=>change(i,'caption',e.target.value)}/></label></div>)}</div>
}
