import MediaWorkbench,{hasImageEditRequest} from './MediaWorkbench';
import type {ImageLayer} from './ImageEditWorkspace';
import {useEffect, useRef, useState} from 'react';
import {ArrowLeft, ArrowRight, ArrowUpRight, AudioLines, BookOpen, Check, ChevronDown, Download, FileText, Film, FolderOpen, Image, Layers3, LoaderCircle, Mic, Plus, RefreshCw, Settings2, ShieldCheck, Sparkles, Upload, UserRound, WandSparkles, X} from 'lucide-react';
import {api, getToken} from './api';
import {DesktopUpdates} from './DesktopUpdates';
import StudioHome from './TishijieHome';
import KnowledgeAssistant from './KnowledgeAssistant';
import TopicDelivery from './TopicDelivery';
import './studio.css';
import './studio-works.css';
import ArchiveInterview from './ArchiveInterview';
import CreationFlow from './CreationFlow';
import VideoScenarios from './VideoScenarios';
import PersonalIP from './PersonalIP';
import {MemorySettings} from './MemorySettings';
import './studio-pane-resize.css';
import ArticleEditor from './ArticleEditor';
import {sendKey} from './inputKeys';
import DigitalHumanGuide from './DigitalHumanGuide';
import {StudioModal} from './AssetPicker';
import './digital-human-layout.css';
import {digitalHumanFields,isHumanTool,type HumanSource} from './digitalHumanFields';
import {latestProfileId,profileScope,profileChoiceKey,readProfileChoice,writeProfileChoice,resolveProfileId,flowProfileInitial,taskProfileInitial,profileUnavailable,unavailableProfileOption} from './profile-defaults';

export const STUDIO_NAV = [
 ['studio/home','首页',Sparkles], ['studio/flow','一站式创作',Layers3], ['benchmark','灵感与对标',WandSparkles], ['studio/topics','选题库',BookOpen],
 ['studio/text','文案创作',FileText], ['studio/image','图片创作',Image], ['studio/video','AI 视频',Film], ['studio/avatar/text','数字人视频',UserRound],
 ['knowledge','个人知识库',BookOpen], ['studio/brand','我的 IP',ShieldCheck], ['studio/works','作品与素材',FolderOpen], ['studio/assistant','问问梯世界',FileText],
] as const;
type Field = {key:string; label:string; type?:string; required?:boolean; placeholder?:string; hint?:string; options?:any[]; accept?:string; min?:number; max?:number; default?:any; resource_kind?:string};
type Capability = {id:string; title?:string; route?:string; description?:string; fields?:Field[]; configured?:boolean; available?:boolean; enabled?:boolean; status?:string; provider?:string; cost_hint?:string; reason?:string; [key:string]:any};
type Asset = {id:string; title?:string; name?:string; kind?:string; type?:string; media_type?:string; status?:string; owner_id?:string; workspace_id?:string; visibility?:string; public?:boolean; provider?:string; url?:string; download_url?:string; preview_url?:string; text?:string; [key:string]:any};
type Draft = {id:string; route:string; tool:string; title:string; inputs:Record<string,any>; version:number; updated_at:string; request_id?:string; [key:string]:any};
type Run = {id:string; status:string; draft_id?:string; version?:number; draft_version?:number; message?:string; error?:string; outputs?:Asset[]; result?:any; [key:string]:any};
const pages:Record<string,{title:string; description:string; group:string; icon:any; tools:string[]; fields:Field[]}> = {
 'text':{title:'文案创作',description:'把你的行业经验，写成值得被看见的内容。',group:'文字',icon:FileText,tools:['text'],fields:[{key:'brief',label:'创作要求',type:'textarea',required:true,placeholder:'例如：向物业经理解释老旧电梯更新的三个常见误区。保留事实依据，不编造案例。'},{key:'format',label:'内容形式',type:'select',options:['通用文案','公众号文章','小红书文案','口播脚本']},{key:'target_words',label:'目标字数',type:'number',min:100,max:10000,placeholder:'公众号文章建议 1200 字',hint:'公众号文章建议 1200 字，可改为 100—10000 字；模型会尽量接近，不会硬截断。'}]},
 'image':{title:'图片创作',description:'从一个画面想法开始，为内容找到视觉表达。',group:'图像',icon:Image,tools:['text_image','image_edit'],fields:[{key:'prompt',label:'画面描述',type:'textarea',required:true,placeholder:'描述主体、场景、构图与光线…'}]},
 'video':{title:'AI 视频',description:'让画面构想成为新的镜头与片段。',group:'视频',icon:Film,tools:['text_video','image_video'],fields:[{key:'prompt',label:'画面与运动描述',type:'textarea',required:true}]},
 'avatar/text':{title:'文字驱动',description:'通过飞影，用文稿、数字人形象和声音生成口播视频。',group:'数字人',icon:UserRound,tools:['text_avatar'],fields:[{key:'text',label:'口播文稿',type:'textarea',required:true},{key:'avatar_id',label:'出镜形象',type:'asset',resource_kind:'avatar',required:true},{key:'voice_id',label:'声音',type:'asset',resource_kind:'voice',required:true}]},
 'avatar/audio':{title:'音频驱动',description:'通过飞影，让数字人形象或人物视频跟随原音频开口。',group:'数字人',icon:Mic,tools:['audio_avatar'],fields:[{key:'audio_id',label:'驱动音频',type:'asset',resource_kind:'audio',required:true,accept:'audio/*'},{key:'avatar_id',label:'出镜形象',type:'asset',resource_kind:'avatar',required:true}]},
 'avatar/photo':{title:'图片驱动',description:'通过飞影，用人物照片、文稿和声音生成说话视频。',group:'数字人',icon:Image,tools:['photo_talk'],fields:[{key:'photo_id',label:'人物照片',type:'asset',resource_kind:'image',required:true,accept:'image/*'},{key:'text',label:'要说的话',type:'textarea',required:true},{key:'voice_id',label:'声音',type:'asset',resource_kind:'voice',required:true}]},
 'avatar/create':{title:'创建形象',description:'上传本人或已获授权的素材，建立可复用的出镜形象。',group:'数字人',icon:UserRound,tools:['avatar_create'],fields:[{key:'title',label:'形象名称',required:true},{key:'source_id',label:'形象素材',type:'asset',resource_kind:'video',accept:'video/*',required:true},{key:'consent',label:'我确认已获得该人物的形象使用与创建授权',type:'checkbox',required:true}]},
 'audio/tts':{title:'文本配音',description:'用合适的声音，把一段好内容说清楚。',group:'音频',icon:AudioLines,tools:['tts'],fields:[{key:'text',label:'配音文稿',type:'textarea',required:true},{key:'voice_id',label:'声音',type:'asset',resource_kind:'voice',required:true}]},
 'audio/create':{title:'创建声音',description:'从获授权的录音建立声音资产，供后续创作选择。',group:'音频',icon:Mic,tools:['voice_create'],fields:[{key:'title',label:'声音名称',required:true},{key:'audio_id',label:'源录音',type:'asset',resource_kind:'audio',accept:'audio/*',required:true},{key:'consent',label:'我确认已获得该声音的克隆与使用授权',type:'checkbox',required:true}]},
 'compose':{title:'素材成片',description:'把镜头、配音与字幕组织成完整的一条作品。',group:'合成',icon:Layers3,tools:['compose'],fields:[]},
};
const tabGroups:Record<string,string[][]> = {
 'avatar':[['avatar/text','文字驱动'],['avatar/audio','音频驱动'],['avatar/photo','图片驱动']],
 'audio':[['audio/tts','文本配音'],['audio/library','声音库'],['audio/create','创建声音']],
};
const statusText:Record<string,string>={queued:'等待处理',pending:'等待处理',preparing:'准备素材',submitting:'提交中',running:'生成中',processing:'处理中',succeeded:'已完成',partial:'部分完成',success:'已完成',done:'已完成',completed:'已完成',failed:'生成失败',cancelled:'已取消',ready:'可用',unavailable:'不可用',saving:'正在保存结果',save_failed:'结果保存失败',submitted:'已提交',unknown:'提交状态待核查',archive_failed:'生成完成 · 保存文件失败',interrupted:'已中断 · 需重新确认生成'};
const active=(r:Run)=>['queued','pending','preparing','submitting','running','processing','submitted','saving'].includes(r.status);
const completed=(r:Run)=>['succeeded','partial','success','done','completed','ready'].includes(r.status);
const rows=(value:any,key='items'):any[]=>Array.isArray(value)?value:Array.isArray(value?.[key])?value[key]:Array.isArray(value?.items)?value.items:[];
const message=(e:unknown)=>e instanceof Error?e.message:String(e);
const go=(path:string)=>{location.hash=path.startsWith('studio/')||path.startsWith('task/')?path:'studio/'+path};
// Carry origin through tool/library/cover return links without changing the
// immediate return destination. Each level is still an ordinary studio route.
const creationOrigin=(route:string)=>{let current=route;for(let depth=0;depth<8;depth++){if(current.startsWith('studio/flow')||current.startsWith('task/'))return current;const next=new URLSearchParams(current.split('?')[1]||'').get('return');if(!next)return '';current=next}return ''};
const time=(v:string)=>v?new Date(v).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'';
const mediaKind=(a:Asset)=>a.asset_type||a.media_type?.split('/')[0]||a.type||a.kind||'';
const safeUrl=(url?:string)=>url&&(/^(https?:|blob:)/.test(url)||url.startsWith('/api/'))?url:'';
type WorkCategory='text'|'image'|'video'|'audio'|'other';
const workCategories:{key:WorkCategory;label:string}[]=[{key:'text',label:'文案'},{key:'image',label:'图片'},{key:'video',label:'视频'},{key:'audio',label:'音频'},{key:'other',label:'其他'}];
const workCategory=(r:Run):WorkCategory=>{
 const tool=String(r.tool||'').toLowerCase();
 if(r.input?.action==='studio_text'||tool==='text')return 'text';
 if(['text_image','image_edit'].includes(tool))return 'image';
 if(['text_video','image_video','compose','text_avatar','audio_avatar','photo_talk','avatar_create'].includes(tool))return 'video';
 if(['tts','voice_create'].includes(tool))return 'audio';
 return 'other';
};
const assetUrl=(a:Asset)=>safeUrl(a.file_url||a.preview_url||a.url||a.download_url);
const readLocal=(key:string)=>{try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}};
const routeForTool=(tool:string)=>Object.keys(pages).find(p=>pages[p].tools.includes(tool))||'text';
function decodeDraft(d:any):Draft{return {...d,server_id:d.id,server_version:d.version,route:'studio/'+routeForTool(d.tool),inputs:{...d.input,brand_id:d.brand_id||'',profile_id:d.profile_id||'',source_ids:d.source_ids||[]},options:d.options||{},updated_at:d.updated,version:d.version}}
function withSuggestedTextTarget(d:Draft,fromFlow:boolean):Draft{
 if(d.tool!=='text'||(d.inputs.format!=='公众号文章'&&!fromFlow)||d.inputs.target_words!==undefined&&d.inputs.target_words!==null&&d.inputs.target_words!=='')return d;
 return {...d,inputs:{...d.inputs,target_words:1200},version:d.version+1,updated_at:new Date().toISOString()};
}
function catalogFields(cap:Capability|undefined,fallback:Field[]):Field[]{
 if(!cap)return fallback.filter(f=>!['title','consent'].includes(f.key)).map(f=>({...f,key:f.key==='photo_id'?'image_id':f.key==='source_id'?'video_id':f.key}));
 if(cap.fields)return cap.fields;
 const keys=cap.id==='avatar_create'?['image_id','video_id']:[...(cap.required||[]),...(cap.optional||[])];
 const names:Record<string,string>={text:'文稿',prompt:'画面与创作要求',avatar_id:'出镜形象',voice_id:'声音',audio_id:'音频素材',image_id:cap.id==='photo_talk'?'人物照片':'参考图片',video_id:'人物视频',scenes:'场景'};
 return keys.map((key:string)=>{const resource=key.endsWith('_id')?key.slice(0,-3):'';return {key,label:names[key]||key,required:cap.id!=='avatar_create'&&!(cap.optional||[]).includes(key),type:resource?'asset':key==='scenes'?'scenes':'textarea',resource_kind:resource,accept:['image','video','audio'].includes(resource)?resource+'/*':undefined}});
}
function transferInput(owner:string){try{const raw=JSON.parse(sessionStorage.getItem('studio-transfer:'+owner)||'null');return raw&&typeof raw.brief==='string'&&Array.isArray(raw.source_ids)&&raw.source_ids.every((x:any)=>typeof x==='string')?raw:null}catch{return null}}
function Media({asset,noZoom=false}:{asset:Asset;noZoom?:boolean}){
 const [url,setUrl]=useState(''),[error,setError]=useState('');
 useEffect(()=>{let live=true,object='';setUrl('');setError('');const source=assetUrl(asset);if(!source)return;
  if(!source.startsWith('/api/')){setUrl(source);return}
  const controller=new AbortController();fetch(source,{headers:{Authorization:'Bearer '+getToken()},signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error('文件暂时无法读取');object=URL.createObjectURL(await r.blob());if(live)setUrl(object);else URL.revokeObjectURL(object)}).catch(e=>{if(live&&e.name!=='AbortError')setError(message(e))});return()=>{live=false;controller.abort();if(object)URL.revokeObjectURL(object)};
 },[asset.id,asset.file_url,asset.url,asset.preview_url,asset.download_url]);
 const kind=mediaKind(asset);if(asset.text||asset.body)return <pre className="st-text-result">{asset.text||asset.body}</pre>;
 if(error)return <p className="st-muted">{error}</p>;
 if(!url)return <div className="st-media-placeholder">{assetUrl(asset)?'预览加载中…':'该资源暂无可验证预览'}</div>;
 return kind==='image'?<img src={url} alt={asset.title||'生成图片'} data-no-zoom={noZoom?'true':undefined} onError={()=>setError('预览不可用，请尝试下载原文件')}/>:kind==='audio'||kind==='voice'?<audio controls src={url} preload="metadata"/>:kind==='video'||kind==='avatar'?<video controls src={url} preload="metadata"/>:<p className="st-muted">此文件不支持内嵌预览，可下载查看。</p>;
}
function HumanMediaPreview({asset}:{asset:Asset}){
 const [expanded,setExpanded]=useState(false),preview=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null),stage=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!expanded)return;const dialog=stage.current?.closest('dialog');return()=>{dialog?.close()}},[expanded]);
 const closePreview=()=>{stage.current?.closest('dialog')?.close();setExpanded(false);if(trigger.current?.isConnected)trigger.current.focus()};
 const label=asset.title||asset.name||'人物素材';
 return <div className="st-human-media-preview" ref={preview}>
  <div className="st-human-preview-head"><span title={label}>{label}</span><button ref={trigger} type="button" onClick={e=>{e.preventDefault();e.stopPropagation();preview.current?.querySelector('video')?.pause();setExpanded(true)}} aria-label={'放大预览：'+label}>放大预览 <ArrowUpRight size={14}/></button></div>
  <div className="st-human-preview-inline"><Media asset={asset} noZoom/></div>
  {expanded&&<StudioModal title={label} onClose={closePreview}><div ref={stage} className="st-human-preview-stage"><Media asset={asset} noZoom/></div><p className="st-human-preview-help">完整显示素材 · 视频可使用播放控件 · Esc 关闭</p></StudioModal>}
 </div>;
}
async function saveFile(asset:Asset){
 if(asset.text||asset.body){const object=URL.createObjectURL(new Blob([asset.text||asset.body],{type:'text/plain;charset=utf-8'})),link=document.createElement('a');link.href=object;link.download=(asset.title||'文稿')+'.md';link.click();setTimeout(()=>URL.revokeObjectURL(object),10000);return}
 const url=safeUrl(asset.download_url||asset.url)||assetUrl(asset);if(!url)throw new Error('暂时没有可下载文件');
 const r=await fetch(url,{headers:url.startsWith('/api/')?{Authorization:'Bearer '+getToken()}:undefined});if(!r.ok)throw new Error('下载失败，原生成任务会保留，请稍后重试');
 const object=URL.createObjectURL(await r.blob()),link=document.createElement('a');link.href=object;link.download=asset.filename||asset.name||asset.title||'作品';link.click();setTimeout(()=>URL.revokeObjectURL(object),10000);
}
/** Pass the existing App context as t; route accepts hash or plain studio/... . */
export function Studio({t,route}:{t:any;route:string}){
 const normalized=route.replace(/^#\/?/,'').replace(/^studio\/?/,'')||'home';
 if(normalized.split('?')[0]==='flow')return <div className="studio-v2 st-flow-page"><CreationFlow key={normalized} t={t} route={normalized}/></div>;
 return <StudioPage key={(t.state?.user?.id||'guest')+':'+normalized} t={t} page={normalized}/>;
}
function StudioPage({t,page}:{t:any;page:string}){
 const [path,query='']=page.split('?'),params=new URLSearchParams(query),spec=pages[path];
 const owner=t.state?.user?.id||'guest',workspace=t.state?.workspace||'',scope=owner+':'+workspace;
 const mode=params.get('mode')||spec?.tools[0]||path;
 const coverPrompt=params.get('cover_prompt')||'',coverReturn=params.get('cover')==='1'&&params.get('return')?.startsWith('studio/topics');
 const requestedReturn=params.get('return')||'',originReturn=creationOrigin(requestedReturn),requestedFlow=new URLSearchParams(originReturn.split('?')[1]||'').get('work')||'';
 const flowContext=originReturn.startsWith('studio/flow'),taskContext=originReturn.startsWith('task/'),requestedTask=taskContext?originReturn.split('?')[0].slice(5):'',draftScope=flowContext?'flow:'+requestedFlow:taskContext?'task:'+requestedTask:'standalone';
 const legacyKey='tijian-studio-v2:'+scope+':'+path+':'+mode+':'+(params.get('draft')||params.get('cover_session')||'latest');
 const key=legacyKey+((flowContext||taskContext)?':'+draftScope:'');
 const profiles=t.list?.('profile')||[],profilesReady=t.state?.complete!==false;
 const profileKey=profileChoiceKey(profileScope(t.state),key);
 const recordProfileKey=(id:string)=>profileChoiceKey(profileScope(t.state),'studio-draft:'+id);
 const belongsToScope=(d:any)=>flowContext?!!requestedFlow&&d.flow_id===requestedFlow:taskContext?!!requestedTask&&!d.flow_id&&(d.origin_task_id||d.task_id)===requestedTask:!d.flow_id&&!d.task_id&&!d.origin_task_id;
 const readScopedLocal=()=>{const local=readLocal(key);if(local&&belongsToScope(local))return local;const legacy=params.get('draft')?readLocal(legacyKey):null;return legacy&&belongsToScope(legacy)?legacy:null};
 const fresh=():Draft=>({id:crypto.randomUUID(),route:'studio/'+path,tool:mode,title:spec?.title||'未命名创作',...(flowContext?{flow_id:requestedFlow}:taskContext?{origin_task_id:requestedTask}:{}),inputs:{...(coverPrompt?{prompt:coverPrompt}:path==='text'?{format:'公众号文章',target_words:1200}:{}),...(params.has('profile_id')?{profile_id:params.get('profile_id')||''}:!flowContext&&!taskContext&&profilesReady&&(profiles.length||readProfileChoice(profileKey)!==undefined)?{profile_id:resolveProfileId(profiles,readProfileChoice(profileKey),profilesReady)}:{})},version:1,updated_at:new Date().toISOString()});
 const incoming=useRef(path==='text'&&!flowContext&&!taskContext&&!params.get('draft')?transferInput(owner):null);
 const suggestedOnOpen=useRef(false);
 const [draft,setDraft]=useState<Draft>(()=>{const base=(coverPrompt?null:readScopedLocal())||fresh();const transferred=incoming.current?{...base,inputs:{...base.inputs,brief:incoming.current.brief,source_ids:incoming.current.source_ids},version:base.version+1,updated_at:new Date().toISOString()}:base;const next=withSuggestedTextTarget(transferred,!!params.get('return')?.startsWith('studio/flow'));suggestedOnOpen.current=next!==transferred;return next});
 const [catalog,setCatalog]=useState<Capability[]>([]),[assets,setAssets]=useState<Asset[]>([]),[runs,setRuns]=useState<Run[]>([]),[drafts,setDrafts]=useState<Draft[]>([]);
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[saveState,setSaveState]=useState('正在恢复草稿');
 const [busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false),[selectedRun,setSelectedRun]=useState('');
 const [humanSource,setHumanSource]=useState<HumanSource>(mode==='avatar_create'?'video':'avatar');
 const [filter,setFilter]=useState(''),[returnTo]=useState(()=>params.get('return')||'');
 const [workFilter,setWorkFilter]=useState<WorkCategory|'all'>('all'),[workQuery,setWorkQuery]=useState('');
 const [expandedWorks,setExpandedWorks]=useState<string[]>([]);
 const [libraryStatus,setLibraryStatus]=useState('idle');
 const libraryEpoch=useRef(0);
 const flowReturn=returnTo.startsWith('studio/flow'),flowParams=new URLSearchParams(returnTo.split('?')[1]||''),flowStep=Number(flowParams.get('step')||2),flowWork=flowParams.get('work')||'';
 const returnPath=returnTo.split('?')[0].replace(/^studio\//,''),returnTitle=requestedReturn.startsWith('task/')?'原 AI 对话':returnPath==='video'?'AI 视频':returnPath==='image'?'图片创作':returnPath==='works'?'作品与素材':returnPath==='assets'?'素材库':returnPath==='topics'?'选题与交付':returnPath==='flow'?'一站式创作':'上一页';
 const returnLabel=flowReturn?'返回一站式创作 · 第 '+(flowStep+1)+' 步':'返回'+returnTitle;
 const currentRoute='studio/'+page,assetsHref='#studio/assets?return='+encodeURIComponent(currentRoute),worksHref='#studio/works?return='+encodeURIComponent(currentRoute);
 const [editorWidth,setEditorWidth]=useState(()=>Number(localStorage.getItem('tijian-studio-editor-width'))||500);
 const editorResize=useRef<{x:number;width:number}|null>(null);
 const draftRef=useRef(draft),submitLock=useRef(false),saveQueue=useRef(Promise.resolve()),alive=useRef(true),dirty=useRef(!!incoming.current||!!coverPrompt||suggestedOnOpen.current);
 const scopeFailure=useRef('');
 const persisted=useRef<{id?:string;version?:number;payload?:string}>({id:draft.server_id,version:draft.server_version});
 const [synced,setSynced]=useState(false);
 const [originIdentity,setOriginIdentity]=useState<{ready:boolean;value?:string}>({ready:!flowContext&&!taskContext});
 useEffect(()=>{if(!taskContext||!profilesReady)return;const task=t.get?.(requestedTask);if(task?.kind!=='task'){scopeFailure.current='原对话不存在或不可用，请从原入口重新打开';setError(scopeFailure.current);return}const choice=readProfileChoice(profileChoiceKey(profileScope(t.state),'task:'+requestedTask));setOriginIdentity({ready:true,value:choice??taskProfileInitial(task)})},[taskContext,requestedTask,profilesReady]);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[]);
 // The authenticated assets endpoint already enforces owner scope; it intentionally omits owner IDs.
 const visibleAssets=assets;
 const baseCap=catalog.find(c=>c.id===draft.tool);
 const selectedModel=baseCap?.models?.find((m:any)=>m.id===(draft.model_id||baseCap.binding));
 useEffect(()=>{if(!synced||!isHumanTool(draft.tool)||!baseCap?.models?.some((m:any)=>m.id==='service:hifly')||draft.model_id==='service:hifly')return;dirty.current=true;setDraft(d=>({...d,model_id:'service:hifly',inputs:d.tool==='audio_avatar'?Object.fromEntries(Object.entries(d.inputs).filter(([k])=>k!=='image_id')):d.inputs,options:{},version:d.version+1,request_id:undefined}));setNotice('已切换到飞影服务，旧素材与历史结果保留在素材库和生成记录中；请按当前字段检查出镜素材。')},[synced,baseCap,draft.model_id,draft.tool]);
 useEffect(()=>{if(!synced)return;if(['avatar','video','image'].includes(draft.human_source)){setHumanSource(draft.human_source);return}if(draft.tool==='avatar_create')setHumanSource(draft.inputs.image_id?'image':'video');else if(['text_avatar','audio_avatar'].includes(draft.tool))setHumanSource(draft.inputs.video_id?'video':'avatar')},[synced,draft.id,draft.tool]);
 useEffect(()=>{if(path!=='video'||!baseCap?.models?.length||!draft.model_id||baseCap.models.some((m:any)=>m.id===draft.model_id))return;dirty.current=true;setDraft(d=>({...d,model_id:baseCap.binding||'media:ark-seedance-25',options:{},version:d.version+1,request_id:undefined}));setNotice('原视频平台已切换为官方Seedance；提示词和素材已保留，请检查参数。')},[baseCap,draft.model_id]);
 const supportsImageReferences=(model:any)=>Number(model?.reference_limits?.image||0)>0;
 const referenceModels=catalog.find(c=>c.id==='text_image')?.models||[];
 const imageReferenceModel=referenceModels.find((m:any)=>supportsImageReferences(m)&&m.configured)||referenceModels.find(supportsImageReferences);
 useEffect(()=>{
  if(draft.tool!=='text_image'||!draft.inputs.image_ids?.length||!imageReferenceModel)return;
  const current=baseCap?.models?.find((m:any)=>m.id===(draft.model_id||baseCap.binding));
  if(supportsImageReferences(current))return;
  dirty.current=true;
  setDraft(d=>({...d,model_id:imageReferenceModel.id,options:{},version:d.version+1,request_id:undefined}));
 },[draft.tool,draft.inputs.image_ids,draft.model_id,baseCap,imageReferenceModel]);
 const cap:Capability|undefined=baseCap?{...baseCap,...(selectedModel?{options:selectedModel.options,configured:baseCap.binding!==''&&selectedModel.configured,status:selectedModel.configured?'ready':'unconfigured',...(draft.tool==='audio_avatar'&&selectedModel.family==='infinitetalk'?{required:['audio_id','image_id']}:{} )}:{}),optional:draft.tool==='text_image'&&supportsImageReferences(selectedModel)?['image_id','image_ids']:baseCap.optional||[]}:undefined;
 const [optimized,setOptimized]=useState('');
 useEffect(()=>{if(!cap||!synced||!draft.options)return;const options=Object.fromEntries(Object.entries(draft.options).filter(([k,v])=>(cap.options?.[k]||[]).includes(v)||(selectedModel?.provider==='ark'&&(k==='execution_expires_after'||k==='callback_url'))));if(JSON.stringify(options)!==JSON.stringify(draft.options)){dirty.current=true;setDraft(d=>({...d,options,version:d.version+1}));setNotice('服务绑定已更新，不兼容的旧参数已恢复为当前服务默认值。')}},[cap,synced]);
 const configured=path==='text'?!!t.state?.models?.some((m:any)=>m.id===t.state?.bindings?.writing&&m.capability==='text'&&m.published):!!cap&&cap.configured===true&&cap.available!==false&&cap.enabled!==false&&!['planned','unconfigured','unavailable','disabled'].includes(cap.status||'');
 const fields:Field[]=digitalHumanFields(draft.tool,humanSource)||catalogFields(cap,spec?.fields||[]).filter(f=>path!=='avatar/audio'||!/(voice|text|script|音色|文稿)/i.test(f.key+' '+f.label));
 const liveTextJobs=(t.list?.('job')||[]).filter((j:any)=>j.input?.draft_id===draft.id||(draft.job_ids||[]).includes(j.id)).map((j:any)=>({...j,draft_id:draft.id,draft_version:j.input?.draft_version||draft.job_versions?.[j.id]}));
 const currentRuns=path==='text'?liveTextJobs:runs.filter(r=>r.draft_id===draft.id),run=currentRuns.find((r:Run)=>r.id===selectedRun)||currentRuns[0];
 const mediaVersionPendingSave=draft.server_version!==undefined&&draft.version>draft.server_version;
 const sameMediaVersion=(r:Run)=>r.draft_version==null||(!mediaVersionPendingSave&&r.draft_version===(draft.server_version??draft.version));
 const running=currentRuns.some((r:Run)=>active(r)&&(path==='text'||sameMediaVersion(r)));
 const unknownCurrentVersion=path!=='text'&&currentRuns.some((r:Run)=>sameMediaVersion(r)&&r.status==='unknown');
 const unknownPreviousVersion=path!=='text'&&currentRuns.some((r:Run)=>!sameMediaVersion(r)&&r.status==='unknown');
 const update=(values:Record<string,any>)=>{dirty.current=true;const selectVideo=draft.tool==='avatar_create'&&values.video_id,selectImage=draft.tool==='avatar_create'&&values.image_id;if(selectVideo||selectImage)setNotice('形象创建只使用一种素材，已取消另一种素材选择。'+(selectVideo?'视频形象不使用照片模型选项，已恢复默认。':''));setDraft(d=>{const inputs:Record<string,any>={...d.inputs,...values,...(selectVideo?{image_id:''}:selectImage?{video_id:''}:{})};if(d.tool==='text'&&values.format==='公众号文章'&&(inputs.target_words===''||inputs.target_words===undefined))inputs.target_words=1200;return {...d,inputs,...(selectVideo?{options:{}}:{}),version:d.version+1,updated_at:new Date().toISOString(),request_id:undefined}});};
 const chooseProfile=(value:string)=>{try{writeProfileChoice(profileKey,value);writeProfileChoice(recordProfileKey(draft.id),value);update({profile_id:value})}catch{setError('身份选择暂存失败，请在离开前保存草稿')}};
 useEffect(()=>{if(!spec||!synced||loading||scopeFailure.current||!profilesReady||!originIdentity.ready||draft.inputs.profile_id)return;const choice=readProfileChoice(recordProfileKey(draft.id))??readProfileChoice(profileKey);if(choice===''||params.has('profile_id'))return;const next=resolveProfileId(profiles,choice??originIdentity.value,profilesReady);if(next&&next!==draft.inputs.profile_id)update({profile_id:next})},[synced,loading,profilesReady,profileKey,latestProfileId(profiles),draft.id,draft.inputs.profile_id,originIdentity.ready,originIdentity.value]);
 const chooseHumanSource=(source:HumanSource)=>{setHumanSource(source);dirty.current=true;setDraft(d=>({...d,human_source:source,inputs:{...d.inputs,...(d.tool==='avatar_create'?(source==='image'?{video_id:''}:{image_id:''}):source==='video'?{avatar_id:'',voice_id:''}:{video_id:''})},options:d.tool==='avatar_create'?{}:d.options,version:d.version+1,request_id:undefined,updated_at:new Date().toISOString()}))};
 const perform=async(fn:()=>Promise<void>)=>{setError('');setBusy(true);try{await fn()}catch(e){if(alive.current)setError(message(e))}finally{if(alive.current)setBusy(false)}};
 const libraryKind=path.startsWith('avatar')?'avatar':'voice';
 const loadAssets=async(added:Asset[]=[])=>{const epoch=libraryEpoch.current;if(added.length&&alive.current)setAssets(current=>[...added,...current.filter(asset=>!added.some(item=>item.id===asset.id))]);const response=await api('/studio/assets'+(path.endsWith('/library')?'?asset_type='+libraryKind:''));if(alive.current&&(!path.endsWith('/library')||epoch===libraryEpoch.current))setAssets(rows(response,'assets'))};
 const syncLibrary=()=>perform(async()=>{libraryEpoch.current++;const response=await api('/studio/assets?asset_type='+libraryKind+'&refresh=true');setAssets(rows(response,'assets'));setLibraryStatus(response.public_library_status||'queued');setNotice('飞影公共资源已加入后台同步，请稍候。')});
 useEffect(()=>{if(!path.endsWith('/library')||!['queued','running'].includes(libraryStatus))return;let cancelled=false,timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const response=await api('/studio/assets?asset_type='+libraryKind);if(cancelled)return;libraryEpoch.current++;setAssets(rows(response,'assets'));const status=response.public_library_status||'idle';setLibraryStatus(status);if(['queued','running'].includes(status))timer=setTimeout(poll,1500);else if(status==='ready')setNotice('飞影公共资源同步完成。');else if(['failed','interrupted'].includes(status))setError(response.public_library_error||'飞影公共资源同步未完成，可以稍后重试。')}catch{if(!cancelled)timer=setTimeout(poll,3000)}};timer=setTimeout(poll,1200);return()=>{cancelled=true;clearTimeout(timer)}},[path,libraryKind,libraryStatus]);
 useEffect(()=>{let live=true;void (async()=>{
  if(spec){
   // Open the editor after its own draft and model catalog arrive. History and
   // asset shelves can finish in the background without holding the page blank.
   const catalogRead=api('/studio/catalog').then(raw=>{if(live)setCatalog(rows(raw,'tools').length?rows(raw,'tools'):rows(raw,'capabilities'))}).catch(e=>{if(live)setError('服务目录暂不可用：'+message(e))});
   const originRead=flowContext?api('/studio/flow?work_id='+encodeURIComponent(requestedFlow)).then(flow=>{if(!live)return;if(flow.id!==requestedFlow)throw Error('原作品不存在或不可用');const choice=readProfileChoice(profileChoiceKey(profileScope(t.state),'flow:'+requestedFlow));setOriginIdentity({ready:true,value:flowProfileInitial(flow,choice)})}).catch(e=>{if(live){scopeFailure.current='原作品读取失败：'+message(e);setError(scopeFailure.current)}}):Promise.resolve();
   const draftRead=api(flowContext?'/studio/flows/'+encodeURIComponent(requestedFlow)+'/drafts':taskContext?'/studio/tasks/'+encodeURIComponent(requestedTask)+'/drafts':path==='text'?'/studio/text/drafts':'/studio/drafts').then(raw=>{if(!live)return;const list=rows(raw,'drafts').filter(belongsToScope).map(decodeDraft).sort((a,b)=>String(b.updated_at||'').localeCompare(String(a.updated_at||'')));setDrafts(list);const remote=params.get('draft')?list.find((d:Draft)=>d.id===params.get('draft')):list.find((d:Draft)=>d.tool===mode);const local=readScopedLocal();if(local?.server_id&&!list.some(d=>d.id===local.server_id)){persisted.current={};dirty.current=false;setDraft(fresh());if(params.get('draft')){scopeFailure.current='指定草稿不属于当前创作范围，请从原入口重新打开';setError(scopeFailure.current)}return}if(params.get('draft')&&!remote){scopeFailure.current='指定草稿不属于当前创作范围，请从原入口重新打开';setError(scopeFailure.current);return}if(remote&&!dirty.current&&(!local||String(remote.updated_at||'')>String(local.updated_at||''))){const opened=withSuggestedTextTarget(remote,flowReturn);persisted.current={id:remote.id,version:remote.server_version};if(opened!==remote)dirty.current=true;setDraft(opened);if(opened!==remote)void persist(opened)}else if(local&&(!remote||String(local.updated_at||'')>=String(remote.updated_at||''))){if(remote)persisted.current={id:remote.id,version:remote.server_version};dirty.current=true}}).catch(e=>{if(live){const failure='草稿读取失败：'+message(e);if(params.get('draft')||flowContext||taskContext)scopeFailure.current=failure;setError(failure)}});
   void api('/studio/assets').then(raw=>{if(live)setAssets(rows(raw,'assets'))}).catch(()=>{});
   void api('/studio/runs').then(raw=>{if(live)setRuns(rows(raw,'runs'))}).catch(()=>{});
   await Promise.allSettled([catalogRead,draftRead,originRead]);
   if(live){setSynced(true);setLoading(false);setSaveState(readLocal(key)?'已恢复本机草稿':'草稿自动保存')}
   return;
  }
  const result=await Promise.allSettled([api('/studio/catalog'),api('/studio/assets'+(path.endsWith('/library')?'?asset_type='+libraryKind:'')),api('/studio/runs'),api('/studio/drafts'),api('/studio/text/drafts')]);
  if(!live)return;
  if(result[0].status==='fulfilled'){const raw=result[0].value;setCatalog(rows(raw,'tools').length?rows(raw,'tools'):rows(raw,'capabilities'))}else setError('服务目录暂不可用：'+message(result[0].reason));
  if(result[1].status==='fulfilled'){setAssets(rows(result[1].value,'assets'));if(path.endsWith('/library'))setLibraryStatus(result[1].value.public_library_status||'idle')}
  if(result[2].status==='fulfilled')setRuns(rows(result[2].value,'runs'));
  if(result[3].status==='fulfilled'||result[4].status==='fulfilled'){
   const list=[...(result[3].status==='fulfilled'?rows(result[3].value,'drafts'):[]),...(result[4].status==='fulfilled'?rows(result[4].value,'drafts'):[])].filter(belongsToScope).map(decodeDraft).sort((a,b)=>String(b.updated_at||'').localeCompare(String(a.updated_at||'')));setDrafts(list);
   const remote=params.get('draft')?list.find((d:Draft)=>d.id===params.get('draft')):list.filter((d:Draft)=>d.tool===mode).sort((a:Draft,b:Draft)=>String(b.updated_at||'').localeCompare(String(a.updated_at||'')))[0];
   const local=readScopedLocal();if(local?.server_id&&!list.some(d=>d.id===local.server_id)){persisted.current={};dirty.current=false;setDraft(fresh());if(params.get('draft')){scopeFailure.current='指定草稿不属于当前创作范围，请从原入口重新打开';setError(scopeFailure.current)}return}if(params.get('draft')&&!remote){scopeFailure.current='指定草稿不属于当前创作范围，请从原入口重新打开';setError(scopeFailure.current);return}if(remote&&!dirty.current&&(!local||String(remote.updated_at||'')>String(local.updated_at||''))){const opened=withSuggestedTextTarget(remote,flowReturn);persisted.current={id:remote.id,version:remote.server_version};if(opened!==remote)dirty.current=true;setDraft(opened);if(opened!==remote)void persist(opened)}else if(local&&(!remote||String(local.updated_at||'')>=String(remote.updated_at||''))){if(remote)persisted.current={id:remote.id,version:remote.server_version};dirty.current=true}
  }
  setSynced(true);setLoading(false);setSaveState(readLocal(key)?'已恢复本机草稿':'草稿自动保存');
 })();return()=>{live=false}},[]);
 useEffect(()=>{draftRef.current=draft;if(!spec||!synced||!dirty.current)return;try{localStorage.setItem(key,JSON.stringify(draft));if(incoming.current){sessionStorage.removeItem('studio-transfer:'+owner);incoming.current=null;setNotice('已接收对标资料；品牌、身份与其他设置保持原选择。')}setSaveState('已暂存本机')}catch{setSaveState('本机保存失败，请检查存储空间')}
  const timer=setTimeout(()=>{void persist(draft)},850);return()=>clearTimeout(timer);
 },[draft,synced,profilesReady,originIdentity.ready]);
 const persist=async(value:Draft)=>{
  if(!originIdentity.ready||!profilesReady)return false;
  if(scopeFailure.current||!belongsToScope(value)){setError(scopeFailure.current||'草稿归属不一致，请重新打开');return false}
   const isText=value.tool==='text',c=catalog.find(x=>x.id===value.tool),chosenModel=c?.models?.find((m:any)=>m.id===(value.model_id||c?.binding)),family=chosenModel?.family,inputKeys=isText?['brief','format','target_words']:c?.id==='avatar_create'?['image_id','video_id']:value.tool==='audio_avatar'&&family==='infinitetalk'?['audio_id','image_id']:[...(c?.required||[]),...(c?.optional||[]),...(value.tool==='text_image'&&supportsImageReferences(chosenModel)?['image_id','image_ids']:[]),...(value.tool==='image_edit'?['image_ids','edit_marks','image_layers']:[]),...(value.tool==='image_video'||value.tool==='text_video'?['prompt','image_id','image_ids','video_ids','audio_ids','reference_mode','remote_references','draft_run']:[])];
  const input=Object.fromEntries(inputKeys.filter((k:string)=>value.inputs[k]!==undefined&&value.inputs[k]!=='').map((k:string)=>[k,value.inputs[k]]));
  const body={tool:value.tool,title:value.title,input,...(!isText?{model_id:value.model_id||''}:{}),...(isText?{job_ids:value.job_ids||[],job_versions:value.job_versions||{}}:{options:value.options||{}}),brand_id:value.inputs.brand_id||'',profile_id:value.inputs.profile_id||'',source_ids:value.inputs.source_ids||[]};
  const payload=JSON.stringify(body);let success=true;
  const task=saveQueue.current.catch(()=>{}).then(async()=>{try{
   if(persisted.current.payload===payload){if(alive.current){if(draftRef.current.version===value.version)dirty.current=false;setSaveState('草稿已保存')}return}
   const previous=persisted.current;
   const remote=await api((flowContext?'/studio/flows/'+encodeURIComponent(requestedFlow)+'/drafts':taskContext?'/studio/tasks/'+encodeURIComponent(requestedTask)+'/drafts':isText?'/studio/text/drafts':'/studio/drafts')+(previous.id?'/'+previous.id:''),{...body,...(previous.id?{version:previous.version}:{})},previous.id?'PATCH':'POST');
   persisted.current={id:remote.id,version:remote.version,payload};if(readProfileChoice(profileKey)!==undefined||readProfileChoice(recordProfileKey(value.id))!==undefined)writeProfileChoice(recordProfileKey(remote.id),value.inputs.profile_id||'');
   if(alive.current){setDraft(d=>({...d,id:remote.id,server_id:remote.id,server_version:remote.version}));if(draftRef.current.version===value.version){dirty.current=false;setSaveState('草稿已保存')}}
  }catch(e){success=false;if(alive.current){setSaveState('已暂存本机 · 服务端未同步');setError('草稿同步失败：'+message(e))}}});saveQueue.current=task;await task;return success;
 };
 useEffect(()=>{if(!runs.some(active))return;let cancelled=false;let timer:ReturnType<typeof setTimeout>;
  const poll=async()=>{try{await Promise.all(runs.filter(active).map(r=>api('/studio/runs/'+r.id+'/refresh',undefined,'POST')));const result=await api('/studio/runs');if(cancelled)return;const next=rows(result,'runs');setRuns(next);if(next.some(completed))void loadAssets();if(next.some(active))timer=setTimeout(poll,4500)}catch{if(!cancelled){setNotice('状态查询暂时失败，未重复提交生成。稍后继续核查原任务。');timer=setTimeout(poll,6000)}}};timer=setTimeout(poll,4000);return()=>{cancelled=true;clearTimeout(timer)};
 },[runs.map(r=>r.id+':'+r.status).join('|')]);
 const upload=async(file:File,inputKey?:string)=>perform(async()=>{const data=new FormData();data.append('file',file);const result=await api('/studio/upload',data),asset=result.asset||result;if(!asset.id)throw new Error('上传未返回有效素材编号');await loadAssets();if(inputKey)update({[inputKey]:asset.id});setNotice('文件已上传并保存，可继续创作。')});
 const assetKind=(a:Asset,kind:string)=>mediaKind(a)===kind||a.kind===kind||(kind==='image'&&a.mime_type?.startsWith('image/'));
 const compatible=(a:Asset)=>Array.isArray(a.compat)&&a.compat.includes(draft.tool);
 const draftRoute=(d:Draft)=>(d.route||'studio/'+Object.keys(pages).find(p=>pages[p].tools.includes(d.tool)))+'?draft='+d.id+'&mode='+d.tool;
 const chooseResource=(kind:string)=>{const target=kind==='avatar'?'avatar/create':'audio/create';void persist(draft).then(ok=>{if(!ok)return;const next={...draft,id:persisted.current.id||draft.id,server_id:persisted.current.id,server_version:persisted.current.version};try{localStorage.setItem('tijian-studio-v2:'+scope+':'+path+':'+draft.tool+':'+next.id+((flowContext||taskContext)?':'+draftScope:''),JSON.stringify(next));go(target+'?return='+encodeURIComponent(draftRoute(next)+(returnTo?'&return='+encodeURIComponent(returnTo):'')))}catch{setError('原草稿保存失败，请稍后重试')}})};
 const transfer=(target:string,values:Record<string,any>,tool?:string,origin=draft.inputs)=>void perform(async()=>{
  const targetMode=tool||pages[target]?.tools[0]||target;
  const input={...values};delete input.source_asset_id;
  const next=await api(flowContext?'/studio/flows/'+encodeURIComponent(requestedFlow)+'/drafts':taskContext?'/studio/tasks/'+encodeURIComponent(requestedTask)+'/drafts':targetMode==='text'?'/studio/text/drafts':'/studio/drafts',{tool:targetMode,title:pages[target]?.title||'创作',input,brand_id:origin.brand_id||'',profile_id:origin.profile_id||'',source_ids:values.source_asset_id&&t.get?.(values.source_asset_id)?.kind==='content'?[values.source_asset_id]:[],...(targetMode==='text'?{}:{options:{}})});
  const deliberate=readProfileChoice(recordProfileKey(draft.id))??readProfileChoice(profileKey)??originIdentity.value;
  if(!origin.profile_id&&deliberate==='')writeProfileChoice(recordProfileKey(next.id),'');
  go(draftRoute(decodeDraft(next))+(returnTo?'&return='+encodeURIComponent(returnTo):''));
 });
 const returnResource=(asset:Asset)=>{
  if(!returnTo)return;const [returnPath,q='']=returnTo.replace(/^studio\//,'').split('?'),p=new URLSearchParams(q),id=p.get('draft'),m=p.get('mode')||pages[returnPath]?.tools[0];
  const parentReturn=creationOrigin(p.get('return')||''),parentFlow=new URLSearchParams(parentReturn.split('?')[1]||'').get('work')||'',parentSuffix=parentReturn.startsWith('studio/flow')?':flow:'+parentFlow:parentReturn.startsWith('task/')?':task:'+parentReturn.split('?')[0].slice(5):'';
  const base='tijian-studio-v2:'+scope+':'+returnPath+':'+m+':',returnKey=base+(id||'latest')+parentSuffix,original=readLocal(returnKey)||(!id&&!parentSuffix?readLocal(base+'latest'):null);
  if(!original){setError('原草稿尚未恢复，请从原页面选择该资源。');return}
  const resourceKey=path.startsWith('avatar')?'avatar_id':'voice_id';const next={...original,inputs:{...original.inputs,[resourceKey]:asset.id},version:original.version+1,updated_at:new Date().toISOString()};
  if(!asset.compat?.includes(m)){setError('该资源不支持原草稿的创作方式，请选择兼容资源。');return}
  try{localStorage.setItem(returnKey,JSON.stringify(next));go(returnTo)}catch{setError('无法保存原草稿，请稍后重试')}
 };
 const generate=async()=>{
  if(draft.tool==='image_edit'&&!hasImageEditRequest(draft.inputs.prompt||'')&&!draft.inputs.edit_marks?.some((mark:any)=>mark.instruction?.trim())&&!draft.inputs.image_layers?.length){setConfirm(false);setError('请至少填写一条整图或区域修改要求，本次未提交生成。');return}
  if(referenceOverflow){setConfirm(false);setError('已选参考素材超过当前模型上限，请先移除多余素材，本次未提交生成。');return}
  if(submitLock.current)return;submitLock.current=true;setConfirm(false);
  await perform(async()=>{
   const previous=currentRuns.find((r:Run)=>r.request_id===draft.request_id||r.input?.creation_request===draft.request_id);
   const requestId=draft.request_id&&(!previous||active(previous)||previous.status==='unknown')?draft.request_id:crypto.randomUUID(),snapshot={...draft,request_id:requestId};setDraft(snapshot);
   if(!await persist(snapshot))throw new Error('草稿尚未同步到服务端，本次未提交生成。');
   try{
    if(path==='text'){
     const targetWords=draft.inputs.target_words||((draft.inputs.format==='公众号文章'||flowReturn)?1200:undefined);
     const j=await api('/studio/text/generate',{...(flowContext?{flow_id:requestedFlow}:taskContext?{task_id:requestedTask}:{}),draft_id:persisted.current.id,brief:draft.inputs.brief,format:draft.inputs.format||'通用文案',...(targetWords?{target_words:targetWords}:{}),brand_id:draft.inputs.brand_id||'',profile_id:draft.inputs.profile_id||'',source_ids:draft.inputs.source_ids||[],request_id:requestId});
     setDraft(d=>({...d,job_ids:[...(d.job_ids||[]).filter((id:string)=>id!==j.id),j.id],job_versions:{...d.job_versions,[j.id]:draft.version}}));await t.refresh?.();
    }else{const response=await api('/studio/generate',{...(flowContext?{flow_id:requestedFlow}:taskContext?{task_id:requestedTask}:{}),draft_id:persisted.current.id,version:persisted.current.version,request_id:requestId,confirmed:true});const next=response.run||response;if(!next.id)throw new Error('服务未返回任务编号，请到生成记录核查');setRuns(old=>[next,...old.filter(r=>r.id!==next.id)]);setSelectedRun(next.id)}
    setNotice('任务已提交。离开页面后仍可从作品与草稿继续查看。')
   }catch(e){setNotice('提交状态不确定时请先刷新生成记录，重试沿用同一请求编号。');throw e}
  });submitLock.current=false;
 };
 const outputs=(r?:Run):Asset[]=>{if(!r)return [];const content=t.get?.(r.result?.content_id);if(content)return [{...content,kind:'text',text:content.body}];return visibleAssets.filter(a=>(r.asset_ids||[]).includes(a.id))};
 const saveAndReturn=()=>void perform(async()=>{if(spec&&dirty.current&&await persist(draftRef.current)===false)throw new Error('草稿尚未保存到服务端，请重试后返回');go(returnTo)});
 const attachToFlow=(asset:Asset)=>void perform(async()=>{
  const field=(asset.text||asset.body||asset.kind==='text')?'content_id':mediaKind(asset)==='image'?'cover_id':mediaKind(asset)==='video'?'video_id':mediaKind(asset)==='audio'?'audio_id':'';
  if(!field||!flowReturn||!flowWork)throw new Error('这个结果暂不能加入本次作品');
  const current=await api('/studio/flow'+(flowWork?'?work_id='+encodeURIComponent(flowWork):''));
  if(flowWork&&current.id!==flowWork)throw new Error('当前作品已切换，请返回主线重新选择');
  if(asset.flow_id===flowWork)await api('/studio/flow',{...current,[field]:asset.id,assembled:'no',stage:flowStep,version:current.version});
  else await api('/studio/flows/'+encodeURIComponent(flowWork)+'/imports',{field,source_id:asset.id,version:current.version});
  go(returnTo);
 });
 const missing=fields.filter(f=>f.required&&path!=='video'&&!(draft.tool==='image_edit'&&f.key==='prompt'&&(draft.inputs.edit_marks?.some((mark:any)=>mark.instruction?.trim())||draft.inputs.image_layers?.length))&&(!draft.inputs[f.key]||(Array.isArray(draft.inputs[f.key])&&!draft.inputs[f.key].length)));
 const unusable=fields.some(f=>f.type==='asset'&&draft.inputs[f.key]&&!visibleAssets.some(a=>a.id===draft.inputs[f.key]&&compatible(a)&&(!isHumanTool(draft.tool)||!['avatar','voice'].includes(f.resource_kind||'')||a.provider==='hifly')&&(!a.status||['ready','available','completed','done'].includes(a.status))));
 const referenceOverflow=['text_video','image_video','image_edit','text_image'].includes(draft.tool)&&(['image','video','audio'] as const).some(kind=>{const ids=draft.inputs[kind+'_ids'];const count=(Array.isArray(ids)&&ids.length?ids.length:kind==='image'&&draft.inputs.image_id?1:0)+(draft.inputs.remote_references||[]).filter((r:any)=>r.kind===kind).length;const legacyImage=kind==='image'&&draft.tool==='text_image'&&selectedModel&&!selectedModel.id.startsWith('media:')&&!selectedModel.id.startsWith('service:');const guideSlot=kind==='image'&&draft.tool==='image_edit'&&draft.inputs.edit_marks?.length?1:0;return count+guideSlot>(selectedModel?.reference_limits?.[kind]??(kind==='image'&&(draft.tool==='image_edit'||legacyImage)?1:0))});
 const imageReferencesReady=draft.tool!=='text_image'||selectedModel?.family!=='gpt-image-2.5-edit'||(draft.inputs.image_ids||[]).length>0;
  const targetWords=draft.inputs.target_words,targetWordsInvalid=draft.tool==='text'&&targetWords!==''&&targetWords!==undefined&&(!Number.isInteger(targetWords)||targetWords<100||targetWords>10000);
  const videoHasInput=path!=='video'||!!(draft.inputs.draft_run||draft.inputs.prompt?.trim()||draft.inputs.image_id||draft.inputs.image_ids?.length||draft.inputs.video_ids?.length||draft.inputs.audio_ids?.length||draft.inputs.remote_references?.length);
  const canGenerate=profilesReady&&originIdentity.ready&&videoHasInput&&configured&&!profileUnavailable(profiles,draft.inputs.profile_id||'',profilesReady)&&!running&&!unknownCurrentVersion&&!busy&&!loading&&!missing.length&&!targetWordsInvalid&&!unusable&&!referenceOverflow&&imageReferencesReady&&(draft.tool!=='image_edit'||hasImageEditRequest(draft.inputs.prompt||'')||draft.inputs.edit_marks?.some((mark:any)=>mark.instruction?.trim())||draft.inputs.image_layers?.length)&&(draft.tool!=='avatar_create'||!!draft.inputs.image_id!==!!draft.inputs.video_id)&&(path!=='compose'||(draft.inputs.scenes?.length>0&&draft.inputs.scenes.every((s:any)=>s.asset_id&&s.length>0)));
 const tabs=tabGroups[path.split('/')[0]],title=spec?.title||({'flow':'一站式创作','home':'首页','assistant':'问问梯世界','works':'作品与素材','assets':'作品与素材','brand':'我的 IP','about':'关于与更新','avatar/library':'数字人形象','audio/library':'声音资产'} as any)[path]||'创作工作台';
 const Icon=spec?.icon||Sparkles;
 const fieldUI=(f:Field)=>{
  const value=draft.inputs[f.key]??f.default??'';
  return <label className={'st-field '+(f.type==='textarea'?'st-wide':'')} key={f.key}><span>{f.label}{f.required&&<em>必填</em>}</span>
   {f.type==='asset'||f.type==='upload'?<><select value={value} onChange={e=>update({[f.key]:e.target.value})}><option value="">选择{f.label}</option>{visibleAssets.filter(a=>assetKind(a,f.resource_kind||'')&&compatible(a)&&(!isHumanTool(draft.tool)||!['avatar','voice'].includes(f.resource_kind||'')||a.provider==='hifly')&&(!a.status||['ready','available','completed','done'].includes(a.status))).map(a=><option value={a.id} key={a.id}>{a.title||a.name||a.id}{a.visibility==='public'?' · 公共':''}</option>)}</select><div className="st-inline">{f.accept&&<label className="st-upload-inline"><Upload size={14}/>上传文件<input type="file" accept={f.accept} disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file,f.key);e.target.value=''}}/></label>}{['avatar','voice'].includes(f.resource_kind||'')&&<button type="button" className="st-link" onClick={()=>chooseResource(f.resource_kind!)}><Plus size={14}/>创建{f.resource_kind==='avatar'?'形象':'声音'}</button>}</div>{value&&visibleAssets.find(a=>a.id===value)&&(isHumanTool(draft.tool)&&['image','video'].includes(f.resource_kind||'')?<HumanMediaPreview key={value} asset={visibleAssets.find(a=>a.id===value)!}/>:<div className="st-input-preview"><Media asset={visibleAssets.find(a=>a.id===value)!}/></div>)}</>:
   f.type==='textarea'?<textarea onKeyDown={e=>sendKey(e,()=>{if(canGenerate)setConfirm(true)},v=>update({[f.key]:v}))} rows={f.key==='text'?10:6} value={value} placeholder={f.placeholder||'输入创作要求 · Enter 继续，Ctrl + Enter 换行'} onChange={e=>update({[f.key]:e.target.value})}/>:
   f.type==='checkbox'?<input type="checkbox" checked={!!value} onChange={e=>update({[f.key]:e.target.checked})}/>:
   f.options?<select value={value} onChange={e=>update({[f.key]:e.target.value})}><option value="">请选择</option>{f.options.map((o:any)=><option key={typeof o==='string'?o:o.value} value={typeof o==='string'?o:o.value}>{typeof o==='string'?o:o.label}</option>)}</select>:
   <input type={f.type==='number'?'number':'text'} value={value} min={f.min} max={f.max} placeholder={f.placeholder} onChange={e=>update({[f.key]:f.type==='number'&&e.target.value!==''?Number(e.target.value):e.target.value})} onBlur={()=>{if(f.key==='target_words'&&value===''&&(draft.inputs.format==='公众号文章'||flowReturn))update({target_words:1200})}}/>}
    {f.type==='asset'&&['avatar','voice'].includes(f.resource_kind||'')&&!visibleAssets.some(a=>assetKind(a,f.resource_kind||'')&&compatible(a)&&a.provider==='hifly')&&<small className="st-resource-empty">暂无可选飞影{f.resource_kind==='avatar'?'形象':'声音'}；先创建，或在资源库同步公共资源。</small>}{f.hint&&<small>{f.hint}</small>}{f.key==='target_words'&&targetWordsInvalid&&<small role="alert" className="st-warning">请输入 100—10000 之间的整数。</small>}
  </label>
 };
 const outputUI=(asset:Asset,origin=draft.inputs)=><article className="st-output" key={asset.id}>{asset.text||asset.body?<TextResult asset={asset} t={t}/>:<Media asset={asset}/>}{asset.width&&asset.height&&<div className="st-asset-dimensions"><span>实际尺寸 {asset.width} × {asset.height}{asset.duration?' · '+Number(asset.duration).toFixed(1)+' 秒':''}</span>{asset.requested_size&&asset.requested_size.replace('*','x')!==`${asset.width}x${asset.height}`&&<small>请求 {asset.requested_size.replace(/[x*]/g,' × ')}，服务返回尺寸不同，已保留原图。</small>}</div>}<div className="st-output-footer"><strong>{asset.title||asset.name||'生成结果'}</strong><span className="st-output-actions"><button type="button" onClick={()=>void perform(()=>saveFile(asset))}><Download size={15}/>下载</button>{path==='image'&&draft.tool==='text_image'&&<button type="button" disabled={!(origin?.input?.prompt||origin?.prompt)} onClick={()=>void navigator.clipboard.writeText(origin?.input?.prompt||origin?.prompt).then(()=>setNotice('提示词已复制')).catch(()=>setError('复制提示词失败，请重试'))}>复制提示词</button>}</span></div>{(!(path==='image'&&draft.tool==='text_image')||coverReturn||flowReturn)&&<div className="st-inline">{coverReturn&&mediaKind(asset)==='image'&&<button className="st-primary" disabled={busy} onClick={()=>go(returnTo+(returnTo.includes('?')?'&':'?')+'cover_asset='+encodeURIComponent(asset.id))}>用作发布封面并返回<ArrowRight size={14}/></button>}{flowReturn&&(asset.text||asset.body||asset.kind==='text'||['image','video','audio'].includes(mediaKind(asset)))&&<button className="st-primary" disabled={busy} onClick={()=>attachToFlow(asset)}>加入本次作品并返回第 {flowStep+1} 步<ArrowRight size={14}/></button>}{mediaKind(asset)==='audio'&&<button className="st-link" onClick={()=>transfer('avatar/audio',{audio_id:asset.id,source_asset_id:asset.id},undefined,origin)}>用于音频口播<ArrowRight size={14}/></button>}{mediaKind(asset)==='image'&&<button className="st-link" onClick={()=>transfer('video',{image_id:asset.id,source_asset_id:asset.id},'image_video',origin)}>用于视频创作<ArrowRight size={14}/></button>}{['video','audio','image'].includes(mediaKind(asset))&&<button className="st-link" onClick={()=>transfer('compose',{scenes:[{asset_id:mediaKind(asset)==='audio'?'':asset.id,...(mediaKind(asset)==='audio'?{audio_id:asset.id}:{}),length:asset.duration||5,caption:'',volume:1}]},undefined,origin)}>用于素材成片<ArrowRight size={14}/></button>}{(asset.text||asset.body)&&<><button className="st-link" onClick={()=>transfer('avatar/text',{text:asset.text||asset.body,source_asset_id:asset.id},undefined,origin)}>用于文字口播</button><button className="st-link" onClick={()=>transfer('audio/tts',{text:asset.text||asset.body,source_asset_id:asset.id},undefined,origin)}>用于配音</button></>}{returnTo&&['avatar','voice'].includes(mediaKind(asset))&&<button className="st-primary" onClick={()=>returnResource(asset)}>使用并返回原稿</button>}</div>}</article>;
 const workRecords=(path==='works'||path==='assets'?[...runs,...(t.list?.('job')||[]).filter((j:any)=>j.input?.action==='studio_text')]:[]).map((run:Run)=>{
  const content=t.get?.(run.result?.content_id);
  const category=workCategory(run);
  const title=content?.title||run.title||'创作任务';
  const searchText=String(content?.body||run.input?.brief||run.input?.prompt||'');
  const snippet=searchText.replace(/\s+/g,' ').slice(0,180);
  return {run,category,title,snippet,searchText};
 }).sort((a,b)=>Date.parse(b.run.created||b.run.created_at||b.run.updated||'')-Date.parse(a.run.created||a.run.created_at||a.run.updated||''));
 const searchedWorkRecords=workRecords.filter(item=>!workQuery.trim()||(`${item.title} ${item.searchText}`).toLocaleLowerCase().includes(workQuery.trim().toLocaleLowerCase()));
 if(path==='topics')return <TopicDelivery t={t} page={page}/>;
 if(path==='memory-settings')return <div className="st-memory-page"><a href="#studio/home">← 返回首页</a><MemorySettings {...t}/></div>;
 if(spec&&(params.get('draft')||flowContext||taskContext)&&(loading||!profilesReady||!originIdentity.ready||scopeFailure.current))return <div className="studio-v2"><section className="surface" role={scopeFailure.current?'alert':'status'}>{scopeFailure.current?<><h2>本次草稿尚未恢复</h2><p>{scopeFailure.current}</p><button onClick={()=>location.reload()}>重新读取</button></>:<><LoaderCircle className="spin" size={18}/><strong>正在恢复本次草稿…</strong><p>先读取当前作品的已保存内容，再开放编辑；其他素材会在后台补齐。</p></>}</section></div>;
 if(path==='image'||path==='video')return <>{returnTo&&<div className="st-flow-context"><span>{flowReturn?<>一站式创作 <b>›</b> {draft.title} <b>›</b> 第 {flowStep+1} 步 · {flowStep===3?'确认作品':'制作内容'} <b>›</b> {title}</>:'从 '+returnTitle+' 进入 · '+title}</span><button disabled={busy||loading} onClick={saveAndReturn}><ArrowLeft size={15}/>{returnLabel}</button></div>}{unknownCurrentVersion&&<p className="st-alert" role="status">本版本有提交状态未知的任务，可能已计费。核查不会重新提交；请修改草稿并保存为新版本，再确认是否生成。</p>}{unknownPreviousVersion&&<p className="st-alert" role="status">旧版本仍有提交状态未知的任务，可能已计费。当前新版本可以生成，但会产生新的服务调用；请核对旧任务与供应商账单。</p>}<MediaWorkbench scenario={path==='video'?<VideoScenarios compact assets={visibleAssets} manageHref={assetsHref} initial={params.get('scenario')||''} onApply={async(prompt,imageId,scenario,videoId)=>{
  const target=imageId?'image_video':'text_video';
  const modelId=draft.model_id||baseCap?.binding||'';
  if(videoId&&!modelId)throw new Error('请先在视频制作区选择 Seedance 模型，再带入参考视频');
  const references={...(imageId?{image_id:imageId,...(modelId?{image_ids:[imageId]}:{})}:{}),...(videoId?{video_ids:[videoId]}:{})};
  if(target===draft.tool){update({prompt,...references});setNotice('场景要求已带入本页草稿，请核对参数。');return}
  const next=await api(flowContext?'/studio/flows/'+encodeURIComponent(requestedFlow)+'/drafts':taskContext?'/studio/tasks/'+encodeURIComponent(requestedTask)+'/drafts':'/studio/drafts',{title:draft.title||'AI 视频创作',tool:target,input:{prompt,...references},model_id:modelId,brand_id:draft.inputs.brand_id||'',profile_id:draft.inputs.profile_id||'',source_ids:[],options:{}});
  go('video?draft='+next.id+'&mode='+target+'&scenario='+scenario+(returnTo?'&return='+encodeURIComponent(returnTo):''));
 }}/> :null} worksHref={worksHref} returnTo={returnTo} imageReferenceModel={imageReferenceModel} coverReturn={!!coverReturn} onImageReferences={(ids:string[])=>{setError(ids.length&&catalog.length&&!imageReferenceModel?'当前没有可用于参考图生成的模型，请在管理后台启用支持参考图的图片模型。':'');dirty.current=true;setDraft(d=>{const currentId=d.model_id||baseCap?.binding||'',current=baseCap?.models?.find((m:any)=>m.id===currentId),nextId=ids.length&&!supportsImageReferences(current)&&imageReferenceModel?imageReferenceModel.id:currentId;return {...d,model_id:nextId,inputs:{...d.inputs,image_ids:ids,image_id:ids[0]||''},options:nextId!==currentId?{}:d.options,version:d.version+1,request_id:undefined}});setNotice(ids.length?'已选参考图，仍在图片生成页；将使用当前支持参考图的模型。':'参考图已移除。')}} useComposite={(assetId:string,sourceId:string,placedLayers:ImageLayer[])=>{const current=draftRef.current;if(current.inputs.image_id!==sourceId||JSON.stringify(current.inputs.image_layers||[])!==JSON.stringify(placedLayers)){setNotice('合成图已保存到素材库；画布期间发生变化，当前编辑已保留。');return false}update({image_id:assetId,image_ids:[assetId,...(current.inputs.image_ids||[]).filter((id:string)=>id!==sourceId&&id!==assetId)],image_layers:[]});return true}} owner={owner} draft={draft} cap={cap} baseCap={baseCap} assets={visibleAssets} reloadAssets={loadAssets} runs={runs.filter(r=>pages[path].tools.includes(r.tool))} update={update} busy={busy} running={running} configured={configured} error={error} notice={notice} saveState={saveState} canGenerate={canGenerate} generate={()=>setConfirm(true)} upload={upload} outputs={outputs} outputUI={outputUI} context={<div className="mw-brand-fields"><label>我的 IP<select value={draft.inputs.profile_id||''} onChange={e=>chooseProfile(e.target.value)}><option value="">不使用 IP · 通用表达</option>{unavailableProfileOption(profiles,draft.inputs.profile_id||'',profilesReady).map(p=><option key={p.value} value={p.value}>{p.label}</option>)}{profiles.map((p:any)=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><a href={'#studio/brand?return='+encodeURIComponent(currentRoute)}>编辑个人 IP →</a></div>}
 changeModel={(id:string)=>{const target=baseCap?.models?.find((m:any)=>m.id===(id||baseCap.binding)),limits=target?.reference_limits;if(path==='video'&&limits&&(['image','video','audio'] as const).some(kind=>((draft.inputs[kind+'_ids']?.length||0)+(draft.inputs.remote_references||[]).filter((r:any)=>r.kind===kind).length)>(limits[kind]||0))){setError('当前参考素材超过新模型上限。先在参考素材中移除多余文件，再切换模型。');return}setError('');dirty.current=true;setDraft(d=>({...d,model_id:id,inputs:d.tool==='text_image'&&!supportsImageReferences(target)?Object.fromEntries(Object.entries(d.inputs).filter(([k])=>k!=='image_ids'&&k!=='image_id')):path==='video'?(target?.provider==='ark'?{...d.inputs,...(target?.modes&&!target.modes.includes(d.inputs.reference_mode||'reference')?{reference_mode:'reference'}:{}),...(target?.family!=='seedance-2.5'?{draft_run:''}:{})}:Object.fromEntries(Object.entries(d.inputs).filter(([k])=>!['reference_mode','remote_references','draft_run'].includes(k)))):d.inputs,options:{},version:d.version+1,request_id:undefined}));if(draft.tool==='text_image'&&!supportsImageReferences(target)&&draft.inputs.image_ids?.length)setNotice('已切换到不支持参考图的模型，原参考图仍保存在素材库。')}} changeOptions={(k:string,v:any)=>{dirty.current=true;setDraft(d=>({...d,options:v===undefined?Object.fromEntries(Object.entries(d.options||{}).filter(([key])=>key!==k)):{...d.options,[k]:v},version:d.version+1,request_id:undefined}))}}
 useVideoSample={(r:any)=>{dirty.current=true;setDraft(d=>({...d,model_id:r.model_id,inputs:{draft_run:r.id,reference_mode:'reference'},options:{resolution:'1080p'},version:d.version+1,request_id:undefined}));setNotice('已选样片，确认清晰度后点击生成正式视频；将独立计费。')}} useVideoLastFrame={(r:any)=>{dirty.current=true;setDraft(d=>({...d,model_id:r.model_id,inputs:{image_id:r.last_frame_id,image_ids:[r.last_frame_id],video_ids:[],audio_ids:[],remote_references:[],reference_mode:'first_frame',prompt:''},options:{ratio:'adaptive'},version:d.version+1,request_id:undefined}))}} cancelRun={(r:any)=>void perform(async()=>{await api('/studio/runs/'+r.id+'/cancel',{},'POST');setRuns(rows(await api('/studio/runs'),'runs'))})} reuse={(r:any)=>{const g=r.generation;const reusedInput=r.tool==='image_edit'&&g.input?.edit_marks?.length?{...g.input,prompt:g.prompt_original??String(g.input.prompt||'').split('\n区域 1 [')[0]}:g.input||{};if(r.tool!==draft.tool){void perform(async()=>{const next=await api(flowContext?'/studio/flows/'+encodeURIComponent(requestedFlow)+'/drafts':taskContext?'/studio/tasks/'+encodeURIComponent(requestedTask)+'/drafts':'/studio/drafts',{tool:r.tool,title:r.title||spec?.title,input:reusedInput,model_id:g.model_id||'',options:g.options||{},brand_id:g.brand_id||'',profile_id:g.profile_id||''});go(draftRoute(decodeDraft(next))+(returnTo?'&return='+encodeURIComponent(returnTo):''))});return}dirty.current=true;setDraft(d=>({...d,inputs:{...reusedInput,brand_id:g.brand_id||'',profile_id:g.profile_id||''},model_id:g.model_id,options:g.options||{},version:d.version+1,request_id:undefined}));setNotice('已复用这次创作的提示词与参数，可继续修改。')}}
 refreshRun={(r:any)=>void perform(async()=>{await api('/studio/runs/'+r.id+'/refresh',undefined,'POST');setRuns(rows(await api('/studio/runs'),'runs'));await loadAssets()})}/>{confirm&&<CostDialog title="确认开始生成" cost={cap?.cost_hint} regenerate={!!currentRuns.length} onClose={()=>setConfirm(false)} onConfirm={()=>void generate()}/>}</>;
 return <div className={'studio-v2'+(path==='flow'?' st-flow-page':'')}>
  <header className="st-header"><div><div className="st-eyebrow">梯世界 / CREATIVE STUDIO <span>V2</span></div><h1>{title}</h1><p>{spec?.description||({'works':'在一处查看生成作品、任务记录和上传素材。','assets':'在一处查看生成作品、任务记录和上传素材。','brand':'记录你的个人定位、服务经验和代理品牌信息。','avatar/library':'管理已授权的出镜形象及创建状态。','audio/library':'管理可复用的声音资产及创建状态。','about':'查看当前版本与更新状态。'} as Record<string,string>)[path]||'把资料与创作工具连接起来。'}</p></div><div className="st-header-tools">{busy&&<span className="st-operating" role="status"><LoaderCircle className="spin" size={15}/> 正在处理当前操作…</span>}{spec&&<span className="st-save" role="status"><Check size={14}/>{saveState}</span>}{spec&&<a href={worksHref} className="st-records">生成记录<ArrowUpRight size={16}/></a>}</div></header>
  {returnTo&&<div className="st-flow-context"><span>{flowReturn?<>一站式创作 <b>›</b> {draft.title} <b>›</b> 第 {flowStep+1} 步 · {flowStep===3?'确认作品':'制作内容'} <b>›</b> {title}</>:'从 '+returnTitle+' 进入 · '+title}</span><button disabled={busy||(!!spec&&loading)} onClick={saveAndReturn}><ArrowLeft size={15}/>{returnLabel}</button></div>}
  {tabs&&<nav className="st-tabs" aria-label="模块功能">{tabs.map(([p,label])=><a key={p} href={'#studio/'+p+(returnTo?'?return='+encodeURIComponent(returnTo):'')} aria-current={path===p?'page':undefined}>{label}</a>)}</nav>}
  {spec&&spec.tools.length>1&&<nav className="st-tabs" aria-label="独立创作方式">{spec.tools.map(tool=><a key={tool} href={'#studio/'+path+'?mode='+tool+(returnTo?'&return='+encodeURIComponent(returnTo):'')} aria-current={draft.tool===tool?'page':undefined}>{catalog.find(c=>c.id===tool)?.title||({text_image:'AI 生图',image_edit:'图片修改',text_video:'文字生成视频',image_video:'图片生成视频'} as any)[tool]}</a>)}</nav>}
  {!spec&&error&&<div className="st-alert" role="alert"><span>{error}</span><button aria-label="关闭错误" onClick={()=>setError('')}><X size={16}/></button></div>}{!spec&&notice&&<div className="st-notice" role="status">{notice}<button aria-label="关闭提示" onClick={()=>setNotice('')}><X size={15}/></button></div>}
  {path==='home'&&<StudioHome t={t} drafts={drafts.map(d=>({...d,href:'#'+draftRoute(d)}))}/>}
  {path==='assistant'&&<KnowledgeAssistant t={t}/>}
  {(path==='works'||path==='assets')&&<nav className="st-library-tabs" aria-label="作品与素材"><a href={'#studio/works'+(returnTo?'?return='+encodeURIComponent(returnTo):'')} aria-current={path==='works'?'page':undefined}>作品与生成记录 <span>{workRecords.length}</span></a><a href={'#studio/assets'+(returnTo?'?return='+encodeURIComponent(returnTo):'')} aria-current={path==='assets'?'page':undefined}>素材库 <span>{visibleAssets.length}</span></a></nav>}
  {spec&&<div className={"st-workspace st-resizable"+(isHumanTool(draft.tool)?" st-human-workspace":"")+(draft.tool==='avatar_create'?" st-avatar-create":"")} style={{'--st-editor-width':editorWidth+'px'} as React.CSSProperties}><section className="st-editor"><div className="st-panel-head"><span className="st-step">01</span><div><h2>创作输入</h2><small>当前草稿 v{draft.server_version||draft.version}</small></div><Icon size={19}/></div><div className="st-editor-body"><div className="st-context"><label>我的 IP<select value={draft.inputs.profile_id||''} onChange={e=>chooseProfile(e.target.value)}><option value="">不使用 IP · 通用表达</option>{unavailableProfileOption(profiles,draft.inputs.profile_id||'',profilesReady).map(p=><option key={p.value} value={p.value}>{p.label}</option>)}{profiles.map((p:any)=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label></div>
   {isHumanTool(draft.tool)&&<DigitalHumanGuide tool={draft.tool} source={humanSource} onSource={chooseHumanSource} configured={configured} busy={busy||running} returnRoute={currentRoute}/>}
   {profileUnavailable(profiles,draft.inputs.profile_id||'',profilesReady)&&<p className="st-warning" role="alert">原 IP 已删除或不可用，请重新选择。</p>}
   {cap?.models&&!isHumanTool(draft.tool)&&['text_image','image_edit','text_video','image_video','text_avatar','audio_avatar','photo_talk'].includes(draft.tool)&&<label className="st-field st-model-select"><span>生成模型</span><select aria-label="生成模型" value={draft.model_id||baseCap?.binding||''} onChange={e=>{dirty.current=true;setOptimized('');setDraft(d=>({...d,model_id:e.target.value,inputs:d.tool==='text_image'&&(e.target.value||baseCap?.binding||'').startsWith('service:')?Object.fromEntries(Object.entries(d.inputs).filter(([k])=>k!=='image_id')):d.inputs,options:{},version:d.version+1,request_id:undefined}))}}><option value="">使用后台默认模型</option>{cap.models.map((m:any)=><option key={m.id} value={m.id}>{m.title}{m.configured?'':' · 接口待接入'}</option>)}</select><small>根据所选模型显示需要的照片、数字人形象与音频素材；服务未配置时仍可保存草稿。</small></label>}
   {draft.tool==='avatar_create'&&<section className="st-human-name" aria-label="形象信息"><h3>形象信息</h3><label className="st-field"><span>形象名称</span><input aria-label="形象名称" aria-describedby="st-human-name-help" value={draft.title} placeholder="为这个形象起一个便于查找的名字" onChange={e=>{dirty.current=true;setDraft(d=>({...d,title:e.target.value,version:d.version+1,updated_at:new Date().toISOString()}))}}/><small id="st-human-name-help">创建完成后，形象与本次草稿使用同一个名称。</small></label></section>}
   {draft.tool==='avatar_create'&&<h3 className="st-human-material-heading">创建素材</h3>}
   <div className="st-fields">{fields.filter(f=>f.key!=='scenes').map(fieldUI)}</div>
   {['text_image','image_edit','text_video','image_video'].includes(draft.tool)&&<div className="st-prompt-tools"><button disabled={busy||!draft.inputs.prompt?.trim()} onClick={()=>void perform(async()=>{const job=await api('/studio/prompt/optimize',{prompt:draft.inputs.prompt,type:path==='video'?'video':'image'});let j=job;while(['queued','running'].includes(j.status)){await new Promise(r=>setTimeout(r,800));j=await api('/jobs/'+j.id)}if(j.status!=='done')throw new Error(j.error||'优化未完成');if(alive.current)setOptimized(j.result.optimized_prompt)})}>AI 优化提示词</button>{optimized&&<div><textarea value={optimized} data-enter="newline" onChange={e=>setOptimized(e.target.value)} aria-label="优化后的提示词"/><button onClick={()=>{update({prompt:optimized});setOptimized('')}}>采用优化结果</button><button onClick={()=>setOptimized('')}>保留原文</button></div>}</div>}
   {draft.tool==='avatar_create'&&<p className="st-inline-tip">形象创建完成后，可在数字人形象库中复用，也可返回原稿继续创作。</p>}
   {!!Object.keys(cap?.options||{}).length&&!(draft.tool==='avatar_create'&&humanSource==='video')&&<details className="st-source-detail" open><summary>生成设置<ChevronDown size={14}/></summary><div className="st-fields">{Object.entries(cap?.options||{}).map(([name,choices])=><label className="st-field" key={name}><span>{({st_show:'字幕',model:'生成方式',quality:'生成质量',size:'图片尺寸 / 比例',watermark:'水印',resolution:'清晰度',ratio:'画面比例',aspectRatio:'画面比例',duration:'时长（秒）'} as any)[name]||name}</span><select value={draft.options?.[name]===undefined?'':JSON.stringify(draft.options[name])} onChange={e=>{dirty.current=true;setDraft(d=>({...d,options:e.target.value?{...d.options,[name]:JSON.parse(e.target.value)}:Object.fromEntries(Object.entries(d.options||{}).filter(([k])=>k!==name)),version:d.version+1,request_id:undefined,updated_at:new Date().toISOString()}))}}><option value="">服务默认</option>{(choices as any[]).map(v=><option key={JSON.stringify(v)} value={JSON.stringify(v)}>{typeof v==='boolean'?(v?'开启':'关闭'):name==='st_show'?(v?'显示字幕':'不显示字幕'):name==='model'&&draft.tool==='photo_talk'?({5:'4.0 · 写实人物',6:'4.0 · 卡通人物'} as any)[v]||String(v):name==='model'&&draft.tool==='avatar_create'?({1:'图片形象 · 视频 2.0',2:'图片形象 · 视频 2.1'} as any)[v]||String(v):({low:'低',medium:'中',high:'高',auto:'自动','1024x1024':'方形 1:1 · 1024×1024','1536x1024':'横版 3:2 · 1536×1024','1024x1536':'竖版 2:3 · 1024×1536','1536x864':'横屏 16:9 · 1536×864','864x1536':'竖屏 9:16 · 864×1536','2048x2048':'方形 2K · 2048×2048','2560x1440':'横屏 2K · 2560×1440','1440x2560':'竖屏 2K · 1440×2560'} as any)[String(v)]||String(v)}</option>)}</select></label>)}</div></details>}
   {path==='compose'&&<SceneEditor scenes={draft.inputs.scenes||[]} assets={visibleAssets.filter(a=>['video','image','audio'].includes(mediaKind(a)))} onChange={scenes=>update({scenes})} fields={fields}/>}
   {path==='text'&&<details className="st-source-detail"><summary>选择本次参考资料<ChevronDown size={14}/></summary>{[...(t.list?.('source')||[]),...(t.list?.('content')||[])].slice(0,100).map((s:any)=><label className="st-check-row" key={s.id}><input type="checkbox" checked={(draft.inputs.source_ids||[]).includes(s.id)} onChange={e=>update({source_ids:e.target.checked?[...(draft.inputs.source_ids||[]),s.id]:(draft.inputs.source_ids||[]).filter((id:string)=>id!==s.id)})}/>{s.title}</label>)}</details>}
   <details className="st-source-detail"><summary>本次资料与版本<ChevronDown size={14}/></summary><p>身份只用于辅助表达，切换身份不会覆盖已输入文稿。生成结果绑定提交时的草稿版本。</p>{draft.tool!=='avatar_create'&&<label className="st-field"><span>草稿名称</span><input value={draft.title} onChange={e=>{dirty.current=true;setDraft(d=>({...d,title:e.target.value,version:d.version+1,updated_at:new Date().toISOString()}))}}/></label>}</details>
  </div><footer className="st-generate-bar">{error&&<p className="st-alert" role="alert">{error}</p>}{notice&&!notice.startsWith('任务已提交')&&<small role="status">{notice}</small>}{!configured&&<div className="st-config-hint"><Settings2 size={17}/><span>{loading?'正在检查可用能力…':cap?.reason||'此功能尚未配置可用服务。请联系管理员，草稿可以继续编辑。'}</span></div>}<div className="st-cost"><small>{cap?.cost_hint||'调用生成服务可能产生费用，以供应商实际账单为准。'}</small><button className="st-primary" disabled={!canGenerate} onClick={()=>setConfirm(true)}>{running?<LoaderCircle size={17} className="st-spin"/>:<WandSparkles size={17}/>} {running?'任务处理中':currentRuns.length?'重新生成':'开始生成'}</button></div>{unusable&&<small className="st-warning">所选资源暂不可用或与当前服务不兼容，请重新选择。</small>}</footer></section>
  <div className="st-pane-resizer" role="separator" aria-label="拖动调整创作区宽度；双击还原" aria-orientation="vertical" tabIndex={0} onPointerDown={e=>{e.preventDefault();editorResize.current={x:e.clientX,width:editorWidth};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!editorResize.current)return;const width=Math.max(320,Math.min(720,editorResize.current.width+e.clientX-editorResize.current.x));const snapped=Math.abs(width-500)<14?500:width;setEditorWidth(snapped);localStorage.setItem('tijian-studio-editor-width',String(snapped))}} onPointerUp={()=>{editorResize.current=null}} onDoubleClick={()=>{setEditorWidth(500);localStorage.setItem('tijian-studio-editor-width','500')}} onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){const width=Math.max(320,Math.min(720,editorWidth+(e.key==='ArrowLeft'?-20:20)));setEditorWidth(width);localStorage.setItem('tijian-studio-editor-width',String(width))}}}/>  <aside className="st-preview"><div className="st-panel-head"><span className="st-step">02</span><div><h2>结果与版本</h2><small>每次生成，独立保留</small></div><span className="st-dot"/></div>{run?<><div className="st-run-head"><span className={'st-status '+(active(run)?'working':run.status==='failed'?'failed':'')}>{active(run)&&<LoaderCircle size={14} className="st-spin"/>}{statusText[run.status]||run.status}</span><select aria-label="查看生成版本" value={run.id} onChange={e=>setSelectedRun(e.target.value)}>{currentRuns.map((r:Run,i:number)=><option key={r.id} value={r.id}>生成 {currentRuns.length-i} · 草稿 v{r.draft_version||r.version||'—'} · {statusText[r.status]||r.status}</option>)}</select></div>{run.error&&<div className="st-alert">{run.error}</div>}{run.message&&<p className="st-run-message">{run.message}</p>}{(run.draft_version||run.version)!==(draft.server_version||draft.version)&&<p className="st-version-note">此结果对应提交时的文稿，之后修改的草稿不会改变已有成品。</p>}{outputs(run).length?outputs(run).map(a=>outputUI(a)):<div className="st-empty"><Icon size={40}/><h3>{active(run)?'正在创作，请稍候':completed(run)?'任务已结束，结果文件尚未就绪':'本次未获得可用成品'}</h3><p>{active(run)?'可离开本页，任务编号和草稿会保留。':'请核查原任务结果，无需重复付费生成。'}</p><button onClick={()=>void perform(async()=>{if(path!=='text')await api('/studio/runs/'+run.id+'/refresh',undefined,'POST');const r=await api('/studio/runs');setRuns(rows(r,'runs'));await loadAssets();await t.refresh?.()})}><RefreshCw size={14}/>核查原任务</button></div>}</>:<div className="st-preview-empty"><div className="st-preview-lines"><Icon size={40}/></div><span className="st-kicker">等待你的第一个版本</span><h3>作品会在这里出现</h3><p>完成左侧输入后开始生成。<br/></p><div className="st-preview-flow"><span>输入</span><i/><span>生成</span><i/><span>保存</span></div></div>}{returnTo&&<button className="st-return" disabled={busy||loading} onClick={saveAndReturn}>{returnLabel}</button>}</aside></div>}
  {(path==='assets'||path.endsWith('/library'))&&<><div className="st-section-head"><div><h2>{path==='assets'?'可用于本次创作的素材':'可复用的'+(path.startsWith('avatar')?'出镜形象':'声音')}</h2><p className="st-muted">展示当前账户的飞影资源及同步的飞影公共资源，创建完成后才可用于驱动。</p></div><div className="st-inline">{path!=='assets'&&<button disabled={loading||busy||['queued','running'].includes(libraryStatus)} onClick={()=>void syncLibrary()}><RefreshCw size={14}/>{['queued','running'].includes(libraryStatus)?'后台同步中…':'同步飞影公共资源'}</button>}{path==='assets'?<label className="st-primary st-upload-inline"><Upload size={16}/>上传素材<input type="file" disabled={busy} accept="image/png,image/jpeg,image/webp,audio/mpeg,audio/wav,audio/mp4,video/mp4,video/quicktime" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value=''}}/></label>:<a className="st-primary" href={'#studio/'+(path.startsWith('avatar')?'avatar/create':'audio/create')+(returnTo?'?return='+encodeURIComponent(returnTo):'')}><Plus size={16}/>创建{path.startsWith('avatar')?'形象':'声音'}</a>}</div></div><input className="st-search" value={filter} onChange={e=>setFilter(e.target.value)} aria-label="搜索资源" placeholder="搜索名称…"/><div className="st-asset-grid">{visibleAssets.filter(a=>(path==='assets'||a.provider==='hifly'&&mediaKind(a)===(path.startsWith('avatar')?'avatar':'voice'))&&String(a.title||a.name||'').includes(filter)).map(a=><article className="st-asset-card" key={a.id}><div className="st-asset-media">{a.file_url||a.preview_url||a.url?<Media asset={a}/>:<div className="st-empty compact"><UserRound size={30}/><span>暂无可验证预览</span></div>}</div><h3>{a.title||a.name||'未命名资源'}</h3><p><span className="st-status">{statusText[a.status||'']||a.status||'已保存'}</span><small>{a.visibility==='public'?'公共资源':'专属资源'}</small></p>{path.endsWith('/library')&&returnTo&&a.status==='ready'?<button onClick={()=>returnResource(a)}>使用并返回原稿<ArrowRight size={14}/></button>:path==='assets'&&a.file_url?<button onClick={()=>void perform(()=>saveFile(a))}><Download size={14}/>下载原文件</button>:null}</article>)}</div>{!visibleAssets.filter(a=>path==='assets'||a.provider==='hifly'&&mediaKind(a)===(path.startsWith('avatar')?'avatar':'voice')).length&&<div className="st-empty"><FolderOpen size={38}/><h3>{loading?'正在读取资源…':'还没有可用资源'}</h3><p>上传或创建后会显示实际资源及处理状态。</p></div>}</>}
  {path==='works'&&<>
   <div className="st-section-head"><div><h2>作品与生成记录 <span className="st-count">{workRecords.length}</span></h2><p className="st-muted">按内容类型查找，展开记录后查看完整作品和原任务。</p></div><button onClick={()=>void perform(async()=>{await Promise.all(runs.filter(r=>active(r)||['unknown','archive_failed'].includes(r.status)).map(r=>api('/studio/runs/'+r.id+'/refresh',undefined,'POST')));const result=await api('/studio/runs');setRuns(rows(result,'runs'));await loadAssets();await t.refresh?.()})}><RefreshCw size={15}/>核查原任务</button></div>
   {workRecords.length?<><div className="st-work-toolbar"><div className="st-work-filters" role="group" aria-label="按作品类型筛选"><button type="button" aria-pressed={workFilter==='all'} onClick={()=>setWorkFilter('all')}>全部 <span>{workRecords.length}</span></button>{workCategories.map(group=><button type="button" key={group.key} aria-pressed={workFilter===group.key} onClick={()=>setWorkFilter(group.key)}>{group.label} <span>{workRecords.filter(item=>item.category===group.key).length}</span></button>)}</div><label className="st-work-search"><span>搜索作品</span><input type="search" value={workQuery} onChange={e=>setWorkQuery(e.target.value)} placeholder="搜索标题或内容" /></label></div>
    {workCategories.filter(group=>workFilter==='all'||workFilter===group.key).map(group=>{
     const items=searchedWorkRecords.filter(item=>item.category===group.key);
     return items.length?<section className="st-work-group" key={group.key}>
      <div className="st-work-group-head"><h3>{group.label}作品</h3><span>{items.length} 条</span></div>
      <div className="st-work-records">{items.map(({run,title,snippet})=><details className="st-work-record" key={run.id} onToggle={event=>{const open=event.currentTarget.open;setExpandedWorks(previous=>open?(previous.includes(run.id)?previous:[...previous,run.id]):previous.filter(id=>id!==run.id))}}>
       <summary><span className="st-work-record-main"><strong>{title}</strong><small>{time(run.created||run.created_at||run.updated)} · {snippet||'展开查看作品和任务详情'}</small></span><span className={'st-status '+(active(run)?'working':'')}>{statusText[run.status]||run.status}</span><ChevronDown size={17} className="st-work-chevron"/></summary>
       {expandedWorks.includes(run.id)&&<div className="st-work-record-body">{run.error&&<p className="st-warning">{run.error}</p>}{outputs(run).map(asset=>outputUI(asset))}{run.draft_id&&drafts.find(d=>d.id===run.draft_id)&&<a className="st-link" href={'#'+draftRoute(drafts.find(d=>d.id===run.draft_id)!)+(returnTo?'&return='+encodeURIComponent(returnTo):'')}>打开原草稿<ArrowRight size={14}/></a>}{!run.error&&!outputs(run).length&&<p className="st-muted">当前任务暂无可查看的作品，请核查任务状态。</p>}</div>}
      </details>)}</div>
     </section>:null;
    })}
    {!searchedWorkRecords.some(item=>workFilter==='all'||item.category===workFilter)&&<div className="st-empty-row">没有找到匹配的作品。可以换个关键词或类型。</div>}
   </>:<div className="st-empty"><Film size={40}/><h3>第一件作品，从一个想法开始</h3><p>真实生成记录、失败状态与历史版本都会保留在这里。</p><a href="#studio/text" className="st-primary">开始创作</a></div>}
  </>}
  {path==='brand'&&<PersonalIP t={t} assets={visibleAssets}/>}{path==='flow'&&<CreationFlow key={page} t={t} route={page}/>}
  {(path==='about'||path==='settings')&&<section className="st-about"><h2>关于与更新</h2><DesktopUpdates/></section>}
  {!spec&&!['flow','home','assistant','assets','works','brand','about','settings','avatar/library','audio/library'].includes(path)&&<div className="st-empty"><h2>此页面尚未开放</h2><a href="#studio/home">返回首页</a></div>}
  {confirm&&<CostDialog title={currentRuns.length?'确认生成新版本':'确认开始生成'} cost={cap?.cost_hint} regenerate={!!currentRuns.length} onClose={()=>setConfirm(false)} onConfirm={()=>void generate()}/>}
 </div>;
}
function TextResult({asset,t}:{asset:Asset;t:any}){return <ArticleEditor asset={asset} t={t}/>;}
function CostDialog({title,cost,regenerate,onClose,onConfirm}:{title:string;cost?:string;regenerate:boolean;onClose:()=>void;onConfirm:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{dialog.current?.showModal();return()=>dialog.current?.close()},[]);
 return <dialog ref={dialog} className="st-dialog" onCancel={e=>{e.preventDefault();onClose()}} aria-labelledby="st-cost-title"><div className="st-eyebrow">生成确认</div><h2 id="st-cost-title">{title}</h2><p>{regenerate?'这将使用当前草稿创建一个新版本，并产生新的服务消耗；已有作品会保留。':'这将把本次选择的内容与素材上传给生成服务处理。'}</p><p>请确认所选人物、声音与其他素材已获授权；本次仅提交草稿中选择的素材。</p><p className="st-dialog-cost">{cost||'服务可能按次数、字数或时长计费，实际费用以供应商账单为准。'}</p><div className="st-dialog-actions"><button onClick={onClose}>继续编辑</button><button autoFocus className="st-primary" onClick={onConfirm}>确认上传与消耗<ArrowRight size={16}/></button></div></dialog>
}
function SceneEditor({scenes,assets,onChange}:{scenes:any[];assets:Asset[];onChange:(s:any[])=>void;fields?:Field[]}){
 const change=(index:number,key:string,value:any)=>onChange(scenes.map((s,i)=>i===index?{...s,[key]:value}:s));
 return <div className="st-scenes"><div className="st-section-head"><h3>场景顺序</h3><button onClick={()=>onChange([...scenes,{asset_id:'',length:5,fit:'cover',volume:1}])}><Plus size={14}/>添加场景</button></div>{!scenes.length&&<p className="st-muted">选择已有素材，按叙事顺序组织片段。合成不会自动补足缺少的镜头。</p>}{scenes.map((s,i)=><div className="st-scene" key={i}><div className="st-section-head"><strong>场景 {String(i+1).padStart(2,'0')}</strong><div className="st-inline"><button aria-label={'上移场景'+(i+1)} disabled={!i} onClick={()=>{const next=[...scenes];[next[i-1],next[i]]=[next[i],next[i-1]];onChange(next)}}>↑</button><button aria-label={'下移场景'+(i+1)} disabled={i===scenes.length-1} onClick={()=>{const next=[...scenes];[next[i+1],next[i]]=[next[i],next[i+1]];onChange(next)}}>↓</button><button aria-label={'移除场景'+(i+1)} onClick={()=>onChange(scenes.filter((_,n)=>i!==n))}><X size={14}/></button></div></div><label className="st-field"><span>画面素材{s.audio_id&&!s.asset_id&&<em>已带入配音，请补充图片或视频</em>}</span><select value={s.asset_id} onChange={e=>change(i,'asset_id',e.target.value)}><option value="">选择图片或视频</option>{assets.filter(a=>['image','video'].includes(mediaKind(a))).map(a=><option key={a.id} value={a.id}>{a.title||a.name||a.id}</option>)}</select></label><div className="st-fields"><label className="st-field"><span>时长（秒）</span><input type="number" min="0.1" step="0.1" value={s.length} onChange={e=>change(i,'length',Number(e.target.value))}/></label><label className="st-field"><span>画面适配</span><select value={s.fit||'cover'} onChange={e=>change(i,'fit',e.target.value)}><option value="cover">填满画面</option><option value="contain">完整显示</option><option value="crop">裁切</option><option value="none">原尺寸</option></select></label></div><label className="st-field"><span>配音（可选）</span><select value={s.audio_id||''} onChange={e=>change(i,'audio_id',e.target.value||undefined)}><option value="">不添加配音</option>{assets.filter(a=>mediaKind(a)==='audio').map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label><label className="st-check-row"><input type="checkbox" checked={s.volume!==0} onChange={e=>change(i,'volume',e.target.checked?1:0)}/>保留原声</label><label className="st-field"><span>字幕</span><input value={s.caption||''} onChange={e=>change(i,'caption',e.target.value)}/></label></div>)}</div>
}
