import {useEffect,useState} from 'react';
import {api} from './api';

const statusNames:any={published:'已启用',draft:'草稿',disabled:'已停用',deleted:'已删除'};
export function SystemCapabilities(){
 const [data,setData]=useState<any>(null),[tab,setTab]=useState('agent'),[selected,setSelected]=useState(''),[draft,setDraft]=useState<any>(null);
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState(''),[previewPurpose,setPreviewPurpose]=useState('writing');
 const load=async()=>{const result=await api('/admin/capabilities');setData(result);return result};
 useEffect(()=>{load().then(result=>{const base=result.items.find((x:any)=>x.id==='role:agent');setSelected(base.id);setDraft({...base})}).catch(e=>setError(e.message))},[]);
 const dirty=()=>draft&&JSON.stringify(draft)!==JSON.stringify(data?.items.find((x:any)=>x.id===selected));
 const discard=()=>!dirty()||confirm('当前有未保存的修改，是否放弃？');
 const choose=(item:any)=>{if(!discard())return;setSelected(item.id||'new');setDraft({...item});setError('');setNotice('');setPreview('');if(item.purpose!=='all'&&item.purpose!=='agent')setPreviewPurpose(item.purpose)};
 const switchTab=(key:string)=>{if(!discard())return;setTab(key);setPreview('');setError('');setNotice('');const base=key==='agent'?data?.items.find((x:any)=>x.id==='role:agent'):null;setDraft(base?{...base}:null);setSelected(base?.id||'')};
 const run=async(fn:()=>Promise<any>,message:string)=>{if(busy)return;setBusy(true);setError('');setNotice('');try{const result=await fn();await load();if(result?.id){setDraft(result);setSelected(result.id)}setNotice(message)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const save=(status:string)=>run(()=>api('/admin/capabilities',{...draft,status}),status==='published'?'已生效：后续请求使用新版本；已提交任务保持原版本。':'已保存，未启用的方法不会参与 AI 请求。');
 const group=data?.items.filter((x:any)=>tab==='deleted'?x.status==='deleted':x.status!=='deleted'&&(tab==='agent'?x.id==='role:agent':tab==='method'?x.kind==='role'&&x.id!=='role:agent':x.kind==='skill'));
 const heading=draft?.id==='role:agent'?'统一 Agent 基础提示词':draft?.kind==='role'?'编辑任务方法':'编辑 Skill';
 return <section className="capabilities">
  <div className="capability-summary"><h3>统一 Agent 与方法</h3><p>一个助手理解需求，按任务采用问答、写作、分析等方法。用户不必切换角色；个人 IP 与本次创作要求在前台填写。</p><div className="capability-composition"><span>统一基础提示词</span><span>任务方法</span><span>启用的 Skills</span><span>本次要求与资料</span></div><p className="muted">Skills 当前作为文本方法进入模型请求，不执行脚本。模型不会因此获得终端、联网或发布权限。安全边界与输出格式由程序保留。</p><a className="settings-link" href="/admin.html#models">模型连接、功能绑定与用户管理 →</a></div>
  <div className="capability-tabs" role="tablist" aria-label="系统能力类型">{[['agent','统一 Agent'],['method','任务方法'],['skill','Skills 方法库'],['deleted','已删除']].map(([key,title])=><button key={key} role="tab" aria-selected={tab===key} disabled={busy} onClick={()=>switchTab(key)}>{title}</button>)}{tab==='skill'&&<button disabled={busy} onClick={()=>choose({title:'',body:'',kind:'skill',purpose:'writing',status:'draft',origin:'管理员自建'})}>＋ 添加 Skill</button>}</div>
  {error&&<p role="alert" className="form-error">{error}</p>}{notice&&<p role="status" className="capability-notice">{notice}</p>}
  {tab==='method'&&<p className="capability-method-note">这些是同一助手使用的专业方法。原有配置和历史版本继续保留，写作自定义提示词也会继续生效。</p>}
  <div className="capability-layout"><div className="capability-list">{!data&&<p>正在读取配置…</p>}{group?.map((x:any)=><button disabled={busy} key={x.id} className={selected===x.id?'active':''} onClick={()=>choose(x)}><strong>{x.title}</strong><small>{data.purposes[x.purpose]||'所有任务'} · {statusNames[x.status]} · v{x.version}</small></button>)}{data&&!group?.length&&<p className="muted">暂无记录</p>}</div>
  {draft?<div className="capability-editor"><div className="block-heading"><h3>{heading}</h3><small>{draft.id?'版本 '+draft.version:'尚未保存'}</small></div><p className="muted">{draft.origin}{draft.updated?' · '+new Date(draft.updated).toLocaleString('zh-CN'):''}</p>
   {draft.id==='role:agent'&&<p className="capability-method-note">所有任务共享这份基础提示词。平台写作的具体要求在“任务方法 → 平台写作”（已有自定义名称可能仍为“内容创作”）和 Skills 中维护。</p>}
   <fieldset disabled={busy||draft.status==='deleted'}><label className="field">名称<input aria-label="能力名称" value={draft.title} maxLength={120} onChange={e=>setDraft({...draft,title:e.target.value})}/></label>{draft.kind==='skill'&&<label className="field">适用任务<select aria-label="适用功能" value={draft.purpose} onChange={e=>setDraft({...draft,purpose:e.target.value})}>{Object.entries(data.purposes).map(([k,v])=><option key={k} value={k}>{k==='agent'?'统一助手（所有任务）':String(v)}</option>)}<option value="all">所有任务</option></select></label>}<label className="field">{draft.kind==='role'?'目标、表达与任务要求':'方法正文'}<textarea aria-label="能力正文" rows={14} maxLength={60000} value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})}/></label><div className="button-row"><button className="primary" disabled={!draft.title.trim()||!draft.body.trim()} onClick={()=>save('published')}>保存并启用</button>{draft.kind==='skill'&&<><button onClick={()=>save('draft')}>保存为未启用草稿</button>{draft.id&&<button onClick={()=>save('disabled')}>停用</button>}</>}</div></fieldset>
   <div className="button-row capability-secondary">{draft.id&&draft.kind==='skill'&&draft.status!=='deleted'&&<button disabled={busy} onClick={()=>{if(confirm('删除后此方法不再参与后续 AI 请求。历史版本保留，可在“已删除”中恢复。'))save('deleted')}}>删除 Skill</button>}{draft.id&&draft.origin!=='管理员自建'&&<button disabled={busy} onClick={()=>{if(confirm('将恢复系统内置内容并生成新版本，是否继续？'))run(()=>api('/admin/capabilities/'+encodeURIComponent(draft.id)+'/restore',{version:draft.version,target:'default'}),'已恢复内置版本')}}>恢复内置默认</button>}<label className="capability-preview-task">预览任务<select aria-label="预览任务" disabled={busy} value={previewPurpose} onChange={e=>{setPreviewPurpose(e.target.value);setPreview('')}}>{Object.entries(data.purposes).map(([key,label])=><option key={key} value={key}>{String(label)}</option>)}</select></label><button disabled={busy} onClick={()=>run(async()=>{const d=await api('/admin/capabilities/preview/'+previewPurpose);setPreview(d.text)},'预览已保存的生效配置，不调用模型、不产生模型费用。')}>预览生效提示词</button></div>
   <details className="capability-history"><summary>历史版本 · {draft.history?.length||0}</summary>{[...(draft.history||[])].reverse().map((h:any)=><div key={h.version}><strong>v{h.version} · {h.title}</strong><small>{h.updated?new Date(h.updated).toLocaleString('zh-CN'):'系统初始版本'} · {h.status}</small><button disabled={busy} onClick={()=>{if(confirm('恢复为新版本并沿用该版本启用状态，是否继续？'))run(()=>api('/admin/capabilities/'+encodeURIComponent(draft.id)+'/restore',{version:draft.version,target:h.version}),'已恢复为新版本')}}>恢复此版本</button></div>)}</details>{preview&&<details open className="capability-preview"><summary>已保存配置预览 · {data.purposes[previewPurpose]}（含当前管理员偏好；不含会话资料与执行结果）</summary><pre>{preview}</pre></details>}
  </div>:<div className="capability-empty"><h3>选择左侧一项进行维护</h3><p>基础提示词定义统一助手，任务方法与启用的 Skills 补充专业要求。没有启用的方法不会进入请求。</p><p>修改不会覆盖已有对话、人工编辑和历史文稿。</p></div>}</div>
 </section>
}
