import {useState} from 'react';
import {ArrowRight} from 'lucide-react';
import './video-scenarios.css';

const modes=[
 {key:'pitch',name:'商品口播',summary:'商品图 + 卖点 + 出镜方式',hint:'适合用人物展示商品和讲卖点。精准口型与固定数字人请使用独立“数字人口播”。'},
 {key:'display',name:'商品展示',summary:'商品图 + 场景 + 运镜',hint:'以产品细节、使用场景和镜头运动为主。'},
 {key:'store',name:'门店引流',summary:'门店照片 + 地址 + 服务亮点',hint:'用真实门店素材讲清所在位置与到店理由。'},
 {key:'remix',name:'爆款复刻',summary:'参考视频 + 结构拆解 + 自有素材',hint:'这里只借鉴结构与节奏；参考视频需由你提供结构说明，当前不会自动识别画面。'},
] as const;
export default function VideoScenarios({assets,onApply,onModeChange,initial,compact=false,manageHref='#studio/assets'}:{assets:any[];onApply:(prompt:string,imageId:string,scenario:string,videoId:string)=>Promise<void>;onModeChange?:(key:string,name:string)=>void;initial?:string;compact?:boolean;manageHref?:string}){
 const [mode,setMode]=useState((modes.find(x=>x.key===initial)?.key||'pitch') as typeof modes[number]['key']);
 const [product,setProduct]=useState(''),[points,setPoints]=useState(''),[style,setStyle]=useState(''),[image,setImage]=useState(''),[reference,setReference]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const current=modes.find(x=>x.key===mode)!;
 const apply=async()=>{if(!product.trim()||!points.trim()){setError('请先填写产品或门店名称，以及要表达的卖点/服务信息');return}if(mode==='remix'&&(!reference||!style.trim())){setError('爆款复刻需要参考视频和你确认的结构/节奏说明');return}setBusy(true);setError('');try{const prompt=[`场景：${current.name}。`,`主体：${product.trim()}。`,`已确认的信息与卖点：${points.trim()}。`,mode==='pitch'?'镜头：出镜人物自然介绍商品，展示使用动作和产品细节；不要杜撰价格、效果或资质。':mode==='display'?'镜头：从产品整体到关键细节，再到真实使用场景；保持产品外观一致。':mode==='store'?'镜头：从门头与周边进入，展示真实服务场景、位置线索和到店动线；不要编造店址。':'镜头：仅参考用户描述的节奏和分镜结构，替换为自己的产品、人物和素材；不要复制原视频中的人物、商标或文案。',style.trim()?`画面风格与结构：${style.trim()}。`:'','适合短视频竖屏，画面清楚，动作自然。'].filter(Boolean).join('\n');await onApply(prompt,image,mode,reference)}catch(e){setError(e instanceof Error?e.message:'无法保存场景')}finally{setBusy(false)}};
 if(compact)return <section className="vs-page vs-compact"><nav className="vs-tabs" aria-label="AI 视频场景">{modes.map(x=><button key={x.key} type="button" className={mode===x.key?'active':''} onClick={()=>{setMode(x.key);setError('');onModeChange?.(x.key,x.name)}}><strong>{x.name}</strong></button>)}</nav><p className="vs-compact-hint">{current.hint}</p><div className="vs-form"><div className="vs-inputs"><label>{mode==='store'?'门店或服务名称':'商品或服务名称'}<input value={product} onChange={e=>setProduct(e.target.value)} placeholder={mode==='store'?'例如：电梯体验店':'例如：家用电梯'}/></label><label>{mode==='store'?'地址与服务亮点':mode==='remix'?'自己的产品与已确认卖点':'卖点与使用场景'}<textarea value={points} onChange={e=>setPoints(e.target.value)} placeholder="只填写已确认的事实"/></label><label>{mode==='remix'?'参考视频的结构与节奏':mode==='display'?'场景、产品细节与运镜':mode==='store'?'门店动线与画面':'人物出镜方式与镜头'}<textarea value={style} onChange={e=>setStyle(e.target.value)} placeholder={mode==='remix'?'请描述开头、转折和镜头顺序；Seedance会读取已选参考视频':'例如：自然光、手持跟拍、近景展示细节'}/></label>{mode==='remix'&&<label>参考视频<select value={reference} onChange={e=>setReference(e.target.value)}><option value="">选择已上传视频</option>{assets.filter(x=>x.asset_type==='video'&&x.status==='ready').map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label>}</div><div className="vs-actions"><a href={manageHref}>管理素材 →</a><button type="button" className="primary" disabled={busy} onClick={()=>void apply()}>{busy?'正在填写…':'填入创作要求'} <ArrowRight size={14}/></button></div>{error&&<p className="vs-error" role="alert">{error}</p>}</div><p className="vs-compact-hint">需要多张图片、视频或音频时，在下方“参考素材”中继续添加；实际数量按所选模型显示。</p></section>;
 return <section className={'vs-page'+(compact?' vs-compact':'')}><header><div><small>AI 视频 · 场景化创作</small><h1>先说你要做哪种视频</h1><p>选场景、填关键事实，生成要求会带入本页草稿。</p></div><span>Seedance 2.0 / 2.5</span></header><nav className="vs-tabs" aria-label="AI 视频场景">{modes.map(x=><button key={x.key} className={mode===x.key?'active':''} onClick={()=>setMode(x.key)}><strong>{x.name}</strong><small>{x.summary}</small></button>)}</nav><div className="vs-form"><p>{current.hint}</p><div className="vs-inputs"><label>{mode==='store'?'门店或服务名称':'商品或服务名称'}<input value={product} onChange={e=>setProduct(e.target.value)} placeholder={mode==='store'?'例如：华宝南路电梯体验店':'例如：某品牌家用电梯'}/></label><label>{mode==='store'?'地址与服务亮点':'卖点与使用场景'}<textarea value={points} rows={2} onChange={e=>setPoints(e.target.value)} placeholder="只写已确认的事实，缺少的信息可先留空"/></label><label>{mode==='remix'?'参考结构与镜头节奏（必填）':'画面风格与镜头要求（可选）'}<textarea value={style} rows={2} onChange={e=>setStyle(e.target.value)} placeholder={mode==='remix'?'描述开头、转折、镜头顺序和节奏；Seedance会读取已选参考视频':'例如：自然光、手持跟拍、近景展示产品细节'}/></label><label>{mode==='store'?'门店照片':'商品图片'}<select value={image} onChange={e=>setImage(e.target.value)}><option value="">暂不选择，使用文字生成视频</option>{assets.filter(x=>x.asset_type==='image'&&x.status==='ready').map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label>{mode==='remix'&&<label>参考视频<select value={reference} onChange={e=>setReference(e.target.value)}><option value="">选择已上传的视频</option>{assets.filter(x=>x.asset_type==='video'&&x.status==='ready').map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label>}</div><div className="vs-actions"><a href={manageHref}>上传或管理素材 →</a><button className="primary" disabled={busy} onClick={()=>void apply()}>{busy?'正在保存…':'带入本页草稿'} <ArrowRight size={16}/></button></div>{error&&<p className="vs-error" role="alert">{error}</p>}</div></section>;
}
