import {useEffect,useLayoutEffect,useMemo,useRef,useState} from 'react';
import {Download,ImagePlus,LoaderCircle,RefreshCw} from 'lucide-react';
import DOMPurify from 'dompurify';
import {marked} from 'marked';
import {api} from './api';
import {AssetThumbnail,StudioModal} from './AssetPicker';
import type {OptimizeScope} from './WechatOptimizePage';
import WechatLayoutProof,{defaultWechatStyle,type WechatStyle} from './WechatLayoutProof';
import WechatRichEditor,{type RichEditorHandle,type RichFormat} from './WechatRichEditor';
import './wechat-article.css';

type Asset={id:string;title:string;asset_type:string;status:string;file_url?:string};
type Props={draft:any;assets:Asset[];busy:boolean;generating:boolean;onChange:(key:string,value:any)=>void;onSave:()=>void;onDownload:()=>void;onOptimize:(scope:OptimizeScope)=>void;onCreateCover:()=>void;onAssetsChanged:()=>Promise<unknown>;worksHref:string};
const IMAGE=/!\[([^\]]*)\]\(\/api\/(?:(studio\/assets\/([a-f0-9]{32}|[a-f0-9]{64})\/file)|(illustrations\/([a-f0-9]{32})\/file))\)/g;
const imageMarkdown=(asset:Asset)=>`![${(asset.title||'正文图片').replace(/[\[\]]/g,'')} ](/api/studio/assets/${asset.id}/file)`.replace(' ]',']');
const bodyImages=(value:string)=>Array.from(value.matchAll(IMAGE)).map(m=>({id:m[3]||m[5],kind:m[3]?'asset':'illustration',text:m[0],index:m.index||0}));

function IllustrationPreview({id}:{id:string}){
 const [url,setUrl]=useState('');
 useEffect(()=>{let active=true;setUrl('');api('/illustrations/'+id+'/file').then(result=>{if(active)setUrl(result.data_uri||'')}).catch(()=>{});return()=>{active=false}},[id]);
 return url?<img src={url} alt="正文插图" draggable={false}/>:<span className="asset-thumb-placeholder">插图暂不可预览</span>;
}

export default function WechatArticleForm({draft,assets,busy,generating,onChange,onSave,onDownload,onOptimize,onCreateCover,onAssetsChanged,worksHref}:Props){
 const body=String(draft.body||''),pictures=assets.filter(x=>x.asset_type==='image'&&x.status==='ready');
 const [picker,setPicker]=useState<number|null>(null),[uploading,setUploading]=useState(false),[uploadError,setUploadError]=useState(''),[preview,setPreview]=useState(true),[previewMode,setPreviewMode]=useState<'publish'|'images'>('publish');
 const wechatStyle:WechatStyle={...defaultWechatStyle,...(draft.wechat_style||{})};
 const rich=useRef<RichEditorHandle>(null),file=useRef<HTMLInputElement>(null);
 const bodyRef=useRef(body),onChangeRef=useRef(onChange);
 useLayoutEffect(()=>{bodyRef.current=body;onChangeRef.current=onChange},[body,onChange]);
 const changeBody=(value:string)=>{bodyRef.current=value;onChangeRef.current('body',value)};
 const images=useMemo(()=>bodyImages(body),[body]);
 const missing=[!draft.title?.trim()?'标题':'',!body.trim()?'正文':'',!draft.cover_asset_id?'封面':''].filter(Boolean);
 const applyImages=(selectedAssets:Asset[])=>{if(!selectedAssets.length)return;const currentBody=bodyRef.current,tags=selectedAssets.map(imageMarkdown).join('\n\n');if(picker!==null&&picker>=0){const image=bodyImages(currentBody)[picker];if(!image)return;changeBody(currentBody.slice(0,image.index)+tags+currentBody.slice(image.index+image.text.length))}else rich.current?.insertImages(selectedAssets);setPicker(null)};
 const upload=async(files:FileList|null)=>{if(!files?.length)return;setUploading(true);setUploadError('');const uploaded:Asset[]=[];let applied=false;try{for(const f of Array.from(files)){if(!f.type.startsWith('image/'))throw Error('只能上传图片');const data=new FormData();data.append('file',f);const result=await api('/studio/upload',data);uploaded.push((result.asset||result) as Asset)}applyImages(uploaded);applied=true;await onAssetsChanged()}catch(e:any){if(uploaded.length&&!applied){applyImages(uploaded);try{await onAssetsChanged()}catch{/* Keep uploaded references editable even if the list refresh failed. */}}setUploadError(e.message||'上传失败')}finally{setUploading(false);if(file.current)file.current.value=''}};
 const removeImage=(index:number)=>{const currentBody=bodyRef.current,image=bodyImages(currentBody)[index];if(image)changeBody(currentBody.slice(0,image.index)+currentBody.slice(image.index+image.text.length))};
 const formatBody=(kind:RichFormat,value?:string)=>rich.current?.format(kind,value);
 const previewParts=useMemo(()=>{const result:Array<{text?:string;id?:string;kind?:string;ordinal?:number}>=[];let last=0;images.forEach((image,ordinal)=>{if(image.index>last)result.push({text:body.slice(last,image.index)});result.push({id:image.id,kind:image.kind,ordinal});last=image.index+image.text.length});if(last<body.length)result.push({text:body.slice(last)});return result},[body,images]);
 useEffect(()=>{if(picker!==null&&picker>=images.length)setPicker(null)},[images.length,picker]);
 return <div className="wa-form">
  <div className="td-editor-meta"><span>{draft.id?'已保存草稿 v'+draft.version:'待保存的发布稿'} · 尚未发布</span><span>{missing.length?'还需补充：'+missing.join('、'):'主要内容已齐，请检查文字和图片'}</span></div>
  <div className="wa-layout"><div className="wa-main">
   <section className="wa-card"><h3><span>01</span> 文章标题 <button type="button" className="wa-optimize" disabled={busy||generating} onClick={()=>onOptimize('title')}><RefreshCw size={15}/>AI 优化标题</button></h3><label>标题 <small>公众号最多 32 字 · {(draft.title||'').length}/32</small><input value={draft.title||''} maxLength={32} placeholder="一句话说明文章回答的问题" onChange={e=>onChange('title',e.target.value)}/></label></section>
   <section className="wa-card"><h3><span>02</span> 文章正文 <small>选中文字可直接设置格式</small><button type="button" className="wa-optimize" disabled={busy||generating} onClick={()=>onOptimize('body')}><RefreshCw size={15}/>AI 优化正文</button></h3><div className="wa-editor-actions wa-compact-actions"><button type="button" onClick={()=>setPicker(-1)}><ImagePlus size={16}/>从素材库插图</button><button type="button" disabled={uploading} onClick={()=>file.current?.click()}>{uploading?<LoaderCircle className="spin" size={16}/>:<ImagePlus size={16}/>}上传图片并插入</button><button type="button" onClick={()=>setPreview(v=>!v)}>{preview?'隐藏预览':'显示预览'}</button>{preview&&<button type="button" onClick={()=>setPreviewMode(v=>v==='publish'?'images':'publish')}>{previewMode==='publish'?'图片替换':'公众号排版'}</button>}<input ref={file} hidden type="file" accept="image/*" multiple onChange={e=>void upload(e.target.files)}/></div>
    <details className="wa-style-details"><summary>全篇排版设置</summary><div className="wa-base-style"><strong>全篇基础样式</strong><div className="wa-style-controls"><label>正文默认字号<select aria-label="公众号正文字号" value={wechatStyle.font_size} onChange={e=>onChange('wechat_style',{...wechatStyle,font_size:e.target.value})}><option value="15">15 px</option><option value="16">16 px</option><option value="17">17 px</option></select></label><label>行距<select aria-label="公众号正文行距" value={wechatStyle.line_height} onChange={e=>onChange('wechat_style',{...wechatStyle,line_height:e.target.value})}><option value="1.6">紧凑</option><option value="1.8">适中</option><option value="2.0">舒展</option></select></label><label>段距<select aria-label="公众号正文段距" value={wechatStyle.paragraph_gap} onChange={e=>onChange('wechat_style',{...wechatStyle,paragraph_gap:e.target.value})}><option value="8">紧凑</option><option value="12">适中</option><option value="18">舒展</option></select></label><label>标题强调色<select aria-label="公众号排版强调色" value={wechatStyle.accent} onChange={e=>onChange('wechat_style',{...wechatStyle,accent:e.target.value})}><option value="forest">墨绿</option><option value="blue">深蓝</option><option value="ink">深灰</option></select></label></div></div></details>
    <div className={'wa-editor '+(preview?'with-preview':'')}><WechatRichEditor ref={rich} value={body} onChange={changeBody} fontSize={wechatStyle.font_size} lineHeight={wechatStyle.line_height} paragraphGap={wechatStyle.paragraph_gap} accent={wechatStyle.accent} onDropAsset={id=>{const asset=pictures.find(x=>x.id===id);if(asset)applyImages([asset])}} onDropFiles={files=>void upload(files)}/>{preview&&(previewMode==='publish'?<WechatLayoutProof body={body} settings={wechatStyle}/>:<div className="wa-preview" aria-label="公众号正文图片预览">{previewParts.map((part,i)=>part.id?<figure key={i}>{part.kind==='illustration'?<IllustrationPreview id={part.id}/>:<AssetThumbnail asset={pictures.find(x=>x.id===part.id)||{id:part.id,title:'正文图片',asset_type:'image',file_url:'/api/studio/assets/'+part.id+'/file'}}/>}<figcaption>正文图片 {(part.ordinal||0)+1} · <button type="button" onClick={()=>setPicker(part.ordinal||0)}>替换</button> <button type="button" onClick={()=>removeImage(part.ordinal||0)}>移除</button></figcaption></figure>:<div key={i} dangerouslySetInnerHTML={{__html:DOMPurify.sanitize(String(marked.parse(part.text||'',{async:false})))}}/>)}{!body.trim()&&<p>正文预览会显示在这里。</p>}</div>)}</div>
    {images.length>0&&<p className="wa-image-count">正文含 {images.length} 张图片；同步草稿时会逐张上传到微信。</p>}{uploadError&&<p className="wa-error" role="alert">{uploadError}</p>}
   </section>
   <section className="wa-card"><h3><span>03</span> 封面图片 <button type="button" className="wa-optimize" disabled={busy||generating} onClick={()=>onOptimize('cover_brief')}><RefreshCw size={15}/>AI 优化画面建议</button></h3><p>封面用于文章卡片，不会自动插入正文。可以从本次作品或素材库换图。</p><div className="wa-cover">{draft.cover_asset_id&&<AssetThumbnail asset={pictures.find(x=>x.id===draft.cover_asset_id)||{id:draft.cover_asset_id,title:'封面',asset_type:'image'}}/>}<select aria-label="公众号封面图片" value={draft.cover_asset_id||''} onChange={e=>onChange('cover_asset_id',e.target.value)}><option value="">请选择封面</option>{pictures.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></div><label>封面画面建议<textarea rows={3} value={draft.cover_brief||''} placeholder="建议应结合正文内容，例如文章主题、核心场景和标题信息" onChange={e=>onChange('cover_brief',e.target.value)}/></label><button type="button" className="wa-cover-create" onClick={onCreateCover}>按文章内容生成新封面 →</button></section>
   <section className="wa-card"><h3><span>04</span> 摘要 <button type="button" className="wa-optimize" disabled={busy||generating} onClick={()=>onOptimize('summary')}><RefreshCw size={15}/>AI 优化摘要</button></h3><label>分享时显示的简介 <small>最多 120 字 · {(draft.summary||'').length}/120</small><textarea rows={3} value={draft.summary||''} maxLength={120} placeholder="概括文章能帮读者解决什么问题" onChange={e=>onChange('summary',e.target.value)}/></label></section>
   <div className="td-actions td-sticky"><button className="td-primary" disabled={busy||generating} onClick={onSave}>{busy&&<LoaderCircle className="spin" size={15}/>} {busy?'正在保存…':'保存发布稿'}</button><button disabled={busy} onClick={onDownload}><Download size={15}/>导出文稿</button></div>
  </div><aside className="wa-guide"><strong>公众号文章准备</strong><ol><li>核对标题与正文，插入需要的图片</li><li>选封面、检查摘要</li><li>保存后同步到公众号草稿箱</li></ol><div className="wa-ai-explain"><b>AI 优化可以做什么？</b><p>按你的目标优化整篇，或只调整标题、正文、摘要和封面建议。结果先在独立页面对照审核，确认后才写入本地发布稿。</p><p>若要控制篇幅，请在优化方向中说明目标字数与必须保留的内容。</p></div><button type="button" className="wa-all-optimize" disabled={busy||generating} onClick={()=>onOptimize('all')}><RefreshCw size={15}/>AI 优化整篇文章</button><small>生成不会自动同步公众号，也不会公开发布。</small><a href={'#'+worksHref}>查看或上传作品素材 →</a></aside></div>
  {picker!==null&&<StudioModal title={picker<0?'选择正文图片':'替换正文图片'} onClose={()=>setPicker(null)}><div className="wa-picker">{pictures.map(asset=><button key={asset.id} type="button" onClick={e=>{e.stopPropagation();applyImages([asset])}}><AssetThumbnail asset={asset}/><span>{asset.title||'图片素材'}</span></button>)}{!pictures.length&&<p>暂无图片，请先上传素材。</p>}</div></StudioModal>}
 </div>;
}
