import {useEffect,useRef,useState} from 'react';
import {AlertCircle,CheckCircle2,Copy,ExternalLink,LoaderCircle,RefreshCw} from 'lucide-react';
import {api} from './api';
import './wechat-publish.css';

type Account={id:string;name:string;app_id:string;enabled:boolean;has_secret:boolean};
type PublishRecord={id:string;account_id:string;delivery_id:string;delivery_version:number;status:string;draft_media_id?:string;publish_id?:string;article_url?:string;checked_at?:string;synced_at?:string;publish_history?:Array<{status:string;publish_id?:string;checked_at?:string}>};
const statusText:Record<string,string>={draft:'已同步到公众号草稿箱',publishing:'微信正在处理发布',published:'微信确认已发布',failed:'微信发布失败',removed:'文章已删除或被平台下架',uncertain:'微信请求结果待人工核查'};
const developerPlatform='https://developers.weixin.qq.com/platform/';

export default function WechatPublishPanel({delivery,dirty}:{delivery:any;dirty:boolean}){
 const [accounts,setAccounts]=useState<Account[]>([]),[records,setRecords]=useState<PublishRecord[]>([]),[selected,setSelected]=useState('');
 const [editing,setEditing]=useState(''),[name,setName]=useState(''),[appId,setAppId]=useState(''),[showConfig,setShowConfig]=useState(false);
 const secretInput=useRef<HTMLInputElement>(null);
 const [busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [publicIp,setPublicIp]=useState(''),[ipBusy,setIpBusy]=useState(false),[ipError,setIpError]=useState(''),[ipNotice,setIpNotice]=useState('');
 const loadAccounts=async()=>{const result=await api('/wechat-publish/accounts');setAccounts(result.items||[]);setSelected(old=>old||(result.items?.[0]?.id||''))};
 const loadRecords=async()=>{if(!delivery.id){setRecords([]);return}const result=await api('/wechat-publish/records/'+delivery.id);setRecords(result.items||[])};
 useEffect(()=>{void loadAccounts().catch(e=>setError(e.message))},[]);
 useEffect(()=>{void loadRecords().catch(e=>setError(e.message))},[delivery.id]);
 const account=accounts.find(x=>x.id===selected),record=records.find(x=>x.account_id===selected);
 const missing=[!String(delivery.title||'').trim()&&'标题',!String(delivery.body||'').trim()&&'正文',!delivery.cover_asset_id&&'封面'].filter(Boolean).join('、');
 useEffect(()=>{if(!delivery.id||!selected||record?.status!=='publishing'||!record.publish_id)return;let attempts=0;const timer=setInterval(()=>{if(++attempts>24){clearInterval(timer);return}void api('/wechat-publish/status/'+delivery.id,{account_id:selected}).then(value=>setRecords(items=>items.map(item=>item.account_id===selected?value:item))).catch(e=>{clearInterval(timer);setError(e.message||'自动查询失败，请手动查询微信结果')})},5000);return()=>clearInterval(timer)},[delivery.id,selected,record?.status,record?.publish_id]);
 const action=async(label:string,fn:()=>Promise<any>,message:string)=>{setBusy(label);setError('');setNotice('');try{await fn();await Promise.all([loadAccounts(),loadRecords()]);setNotice(message)}catch(e:any){setError(e.message||'操作失败')}finally{setBusy('')}};
 const saveAccount=()=>void action('account',async()=>{const saved=await api('/wechat-publish/accounts',{...(editing?{id:editing}:{}),name,app_id:appId,app_secret:secretInput.current?.value||''});if(secretInput.current)secretInput.current.value='';setSelected(saved.id);setEditing('');setName('');setAppId('');setShowConfig(false)},'公众号连接已加密保存。请先测试连接，再同步草稿。');
 const edit=(item:Account)=>{setEditing(item.id);setName(item.name);setAppId(item.app_id);setShowConfig(true);if(secretInput.current)secretInput.current.value=''};
 const checkPublicIp=async()=>{setIpBusy(true);setPublicIp('');setIpError('');setIpNotice('');try{const result=await api<{ip:string}>('/wechat-publish/public-ip');setPublicIp(result.ip)}catch(e:any){setIpError(e.message||'公网出口 IP 检测失败')}finally{setIpBusy(false)}};
 const copyPublicIp=async()=>{if(!publicIp)return;setIpError('');setIpNotice('');try{await navigator.clipboard.writeText(publicIp);setIpNotice('已复制公网出口 IP')}catch{setIpError('复制失败，请手动选中 IP 复制')}};
 const sync=()=>{const retry=record?.status==='failed';if(retry&&!window.confirm('微信已确认上一轮发布失败。请确认你已修改并保存本页稿件；继续将新建一份公众号草稿，旧发布记录会保留。'))return;void action('sync',()=>api('/wechat-publish/drafts/'+delivery.id,{account_id:selected,version:delivery.version,...(retry?{confirmed_retry:true}:{})}),'微信已接收当前稿件；请到公众号后台草稿箱核对封面、标题、摘要和正文。')};
 const publish=()=>{if(!window.confirm('请确认：你已在微信公众号后台核对这份草稿。继续将向微信提交公开发布，不会群发给粉丝。'))return;
  void action('publish',()=>api('/wechat-publish/publish/'+delivery.id,{account_id:selected,confirmed:true}),'发布任务已提交，尚不能视为发布成功。请点击“查询微信结果”。')};
 return <section className="wp-panel" aria-label="公众号连接与发布">
  <div className="wp-heading"><div><span>03 · 公众号连接</span><h3>同步草稿与确认发布</h3><p>先保存本页发布稿，再同步到公众号草稿箱；核对后由你决定是否公开发布。</p></div><a href="https://mp.weixin.qq.com/" target="_blank" rel="noreferrer">打开公众号后台 <ExternalLink size={15}/></a></div>
  <div className="wp-account-row"><label>发布账号<select aria-label="选择公众号" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">请选择公众号</option>{accounts.map(x=><option value={x.id} key={x.id}>{x.name}{x.enabled?'':' · 已停用'}</option>)}</select></label><button type="button" onClick={()=>{setEditing('');setName('');setAppId('');setShowConfig(true)}}>添加账号</button>{account&&<><button type="button" onClick={()=>edit(account)}>修改连接</button><button type="button" disabled={!!busy} onClick={()=>void action('state',()=>api('/wechat-publish/accounts/'+selected+'/state',{enabled:!account.enabled}),account.enabled?'已停用连接，历史记录保留。':'已启用连接。')}>{account.enabled?'停用':'启用'}</button></>}</div>
  {(showConfig||!accounts.length)&&<div className="wp-config"><strong>{editing?'修改公众号连接':'添加公众号连接'}</strong><p>在微信开发者平台对应服务号的「基础信息」中查看 AppID、AppSecret 和 API IP 白名单。密钥只在服务端加密保存。</p><div><label>账号备注名<input value={name} onChange={e=>setName(e.target.value)} placeholder="例如：公司官方公众号"/></label><label>AppID<input value={appId} onChange={e=>setAppId(e.target.value)} placeholder="wx…"/></label><label>AppSecret<input ref={secretInput} type="password" autoComplete="new-password" placeholder={editing?'留空保留原密钥':'仅保存时提交'}/></label></div><button type="button" disabled={!!busy||!name.trim()||!appId.trim()} onClick={saveAccount}>{busy==='account'?<LoaderCircle className="spin" size={16}/>:null}保存连接</button>{!!accounts.length&&<button type="button" onClick={()=>{setEditing('');setShowConfig(false)}}>取消</button>}</div>}
  <div className="wp-ip-guide" aria-label="公众号 API IP 白名单引导"><div className="wp-ip-intro"><strong>API IP 白名单</strong><p>检测工作台后端当前访问公网时的 IPv4 出口地址。若使用代理、多个出口或更换网络，请以微信报错中显示的 IP 再核对。</p></div><div className="wp-ip-controls"><button type="button" disabled={ipBusy} onClick={()=>void checkPublicIp()}>{ipBusy?<LoaderCircle className="spin" size={15}/>:<RefreshCw size={15}/>}检测出口 IP</button>{publicIp&&<><output aria-label="当前服务器公网出口 IP">{publicIp}</output><button type="button" onClick={()=>void copyPublicIp()}><Copy size={15}/>复制 IP</button></>}<a href={developerPlatform} target="_blank" rel="noopener noreferrer">打开微信开发者平台 <ExternalLink size={15}/></a></div><p className="wp-ip-steps">登录后进入「我的业务与服务 → 对应服务号 → 基础信息 → API IP 白名单」，由你自行添加并保存。遇到 <strong>40164</strong>，先核对微信报错里的 IP 与上方检测值；保存后再重试原操作。</p>{ipError&&<p className="wp-ip-error" role="alert">{ipError}</p>}{ipNotice&&<p className="wp-ip-notice" role="status">{ipNotice}</p>}</div>
  {account&&<div className="wp-actions"><div className="wp-connection"><span className={account.enabled?'wp-dot':'wp-dot off'}/><strong>{account.name}</strong><small>{account.enabled?'已启用':'已停用'} · {account.app_id}</small><button type="button" disabled={!!busy} onClick={()=>void action('test',()=>api('/wechat-publish/accounts/'+selected+'/test',{}),'当前 AppID 与 AppSecret 已向微信重新验证；草稿和发布权限将在实际调用时确认。')}>{busy==='test'?<LoaderCircle className="spin" size={15}/>:<RefreshCw size={15}/>}测试连接</button></div>
   <div className="wp-steps"><div><b>1</b><span><strong>同步到草稿箱</strong><small>{missing?'请先补齐：'+missing:dirty?'有未保存的修改，请先点上方“保存发布稿”':!delivery.id?'请先保存本页发布稿':record?.status==='draft'?'已同步，可修改后重新同步':record?.status==='failed'?'上次发布已确认失败；修改并保存本页后，可新建草稿':'正文图片将上传微信，再建立公众号草稿'}</small></span><button type="button" disabled={!!busy||!!missing||!delivery.id||dirty||!account.enabled||['publishing','published','uncertain','removed'].includes(record?.status||'')} onClick={sync}>{busy==='sync'?<LoaderCircle className="spin" size={16}/>:null}{record?.status==='draft'?'更新公众号草稿':record?.status==='failed'?'修订后重新同步草稿':'同步公众号草稿'}</button></div>
   <div><b>2</b><span><strong>在公众号后台核对</strong><small>核对封面裁剪、排版和内容。公众号后台的修改不会自动回写本页。</small></span><a href="https://mp.weixin.qq.com/" target="_blank" rel="noreferrer">查看草稿 ↗</a></div>
   <div><b>3</b><span><strong>确认公开发布</strong><small>使用微信 freepublish 发布，不会主动群发粉丝；微信审核或处理可能需要时间。</small></span><button type="button" disabled={!!busy||dirty||!account.enabled||record?.status!=='draft'} onClick={publish}>{busy==='publish'?<LoaderCircle className="spin" size={16}/>:null}核对无误，提交发布</button></div></div>
   {record&&<div className={'wp-status '+(['failed','removed','uncertain'].includes(record.status)?'wp-status-warning':'')} role="status">{record.status==='publishing'?<LoaderCircle className="spin" size={18}/>:['failed','removed','uncertain'].includes(record.status)?<AlertCircle size={18}/>:<CheckCircle2 size={18}/>}<span>{statusText[record.status]||record.status}{record.synced_at&&<small> · 草稿同步于 {new Date(record.synced_at).toLocaleString('zh-CN')}</small>}{!!record.publish_history?.length&&<small> · 已保留 {record.publish_history.length} 次历史发布记录</small>}</span>{record.publish_id&&record.status!=='draft'&&<button type="button" disabled={!!busy} onClick={()=>void action('status',()=>api('/wechat-publish/status/'+delivery.id,{account_id:selected}),'已从微信接口读取最新发布状态。')}>{busy==='status'?<LoaderCircle className="spin" size={16}/>:<RefreshCw size={16}/>}查询微信结果</button>}{record.article_url&&<a href={record.article_url} target="_blank" rel="noreferrer">查看文章 ↗</a>}</div>}
  </div>}
  {error&&<div className="wp-error" role="alert">{error}{error.includes('40164')&&<p>这是微信 API IP 白名单拦截。请在上方检测出口 IP，并按引导由你在微信开发者平台添加；若微信错误信息给出的 IP 不同，以微信显示的地址为准。</p>}{error.includes('40125')&&<button type="button" onClick={()=>{if(account)edit(account)}}>重新填写此账号的 AppSecret</button>}</div>}{notice&&<p className="wp-notice" role="status">{notice}</p>}
  <p className="wp-foot">账号接口权限取决于公众号类型与认证状态。保存连接不会发文；发布必须由你再次点击确认。</p>
 </section>;
}
