import {DeleteRecord} from './DeleteRecord';
import {ExtractKnowledge} from './KnowledgeFlow';
import {localDay} from './dates';
import {useEffect,useState} from 'react';
import {api,type Item} from './api';
const labels:Record<string,string>={task:'对话',source:'原始资料',content:'作品',benchmark:'对标账号',profile:'IP定位',knowledge:'知识',memory:'记忆',plan:'内容计划',metric:'表现数据',publication:'发布记录',feed:'信源',issue:'待处理',channel:'平台账号',weread_subscription:'免费公众号订阅',job:'执行任务记录',wechat_sync:'公众号目录查询记录',wechat_article:'公众号文章目录',wechat_notice:'公众号更新提醒',news:'雷达资讯'};
export {PlatformAccounts} from './PlatformAccounts';
export function RecordManager(t:any){
 const [kind,setKind]=useState('task'),[date,setDate]=useState(()=>localDay()),[trash,setTrash]=useState(false),[q,setQ]=useState('');
 const items=t.state.objects.filter((x:Item)=>x.kind===kind&&!!x.archived===trash&&(x.title||'').includes(q)&&(!date||localDay(new Date(x.created||x.updated))===date));
 return <section className="surface"><h2>资料与对话管理</h2><p>删除会移入回收站，不再用于 AI；可恢复。原始文件保留在工作区。</p><div className="filters"><select value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><input aria-label="按日期查看" type="date" value={date} onChange={e=>setDate(e.target.value)}/><input placeholder="搜索标题" value={q} onChange={e=>setQ(e.target.value)}/><button onClick={()=>setTrash(!trash)}>{trash?'返回资料':'回收站'}</button>{!['issue','knowledge','publication','channel','job','wechat_sync','wechat_article','wechat_notice','weread_subscription','news'].includes(kind)&&<button onClick={()=>t.newItem(kind,'新增'+labels[kind],[{key:'title',label:'标题',required:true},{key:'body',label:'正文',type:'textarea'}])}>新增</button>}<button onClick={()=>document.getElementById('file-import')?.click()}>上传文档</button></div>{items.map((x:Item,i:number)=><div key={x.id}>{(i===0||localDay(new Date(items[i-1].created||items[i-1].updated))!==localDay(new Date(x.created||x.updated)))&&<h3>{localDay(new Date(x.created||x.updated))}</h3>}<div className="work-row"><span><strong>{x.title}</strong></span>{!trash&&<>{!['issue','job','wechat_sync','wechat_article','wechat_notice','weread_subscription','news'].includes(kind)&&<button onClick={()=>t.editItem(x,[{key:'title',label:'标题',required:true},...(kind==='task'?[]:[{key:'body',label:'正文',type:'textarea'}]),...(['benchmark','feed'].includes(kind)?[{key:'url',label:'主页链接'},{key:'feed_url',label:'RSS订阅地址'},{key:'reason',label:'说明',type:'textarea'}]:[])])}>编辑</button>}{kind==='task'&&<><button onClick={()=>{location.hash='task/'+x.id}}>继续对话</button><ExtractKnowledge item={x} t={t}/><button onClick={()=>t.action(async()=>{const j=await api<Item>('/tasks/'+x.id+'/distill',{});location.hash='tasks';return j},'已开始整理对话摘要')}>整理对话摘要</button></>}</>}{trash?<button onClick={()=>t.action(()=>api('/objects/'+x.id+'/restore',{}),'已恢复')}>恢复</button>:<DeleteRecord item={x} t={t} compact/>}</div></div>)}{!items.length&&<p>当前条件下没有记录。</p>}</section>
}
export function PromptEditor(t:any){const [data,setData]=useState<any>(null),[mode,setMode]=useState('research');useEffect(()=>{api('/prompts').then(setData).catch((e:Error)=>t.setError(e.message))},[]);if(!data)return null;return <section className="surface"><h2>个人工作偏好</h2><p>仅影响当前用户。可补充篇幅、语气与呈现习惯；留空时遵循管理员配置的系统角色和方法。</p><select value={mode} onChange={e=>setMode(e.target.value)}>{Object.entries({daily:'日常沟通',research:'资料研究',writing:'内容创作',benchmark:'对标分析',topics:'选题策划',profile:'定位访谈'}).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select><label className="field"><span>个人偏好（可留空）</span><textarea rows={7} value={data.overrides[mode]??''} onChange={e=>setData({...data,overrides:{...data.overrides,[mode]:e.target.value}})}/></label><div className="button-row"><button className="primary" onClick={()=>t.action(()=>api('/prompts',data.overrides,'PUT'))}>保存个人偏好</button><button onClick={()=>{const overrides={...data.overrides};delete overrides[mode];setData({...data,overrides});t.action(()=>api('/prompts',overrides,'PUT'),'已恢复默认')}}>恢复默认</button></div></section>}
